OceanLES.jl
Fixed so that index X was correct for averaging
=> Fix avg_x indexing

src/grids.jl
This pull request adds the type of `xC`, `yC`, `zC`, `xF`, `yF`, and `zF` as a parameter to `RegularCartesianGrid`. It also adds constructors that will permit phasing out `ModelMetadata` and a default float type, `Float64`.
=> Adds type of xC, xF, etc to RegularCartesianGrid

.gitignore, docs/make.jl, docs/src/algorithm.md
I would also suggest to change notation from `v` to `\upsilon` because `v` and `\nu` are very similar.
=> Fixes in docs

examples/free_convection.jl, examples/utils.jl, src/output_writers.jl
Just some small things from testing free convection with @SandreOuza
=> Free convection test

examples/free_convection.jl, src/poisson_solvers.jl, src/time_steppers.jl
... and cleans up free convection example, and adds verbose flag to GPU Poisson solver.
=> Fixes bug in adams_bashforth_update

src/time_steppers.jl
=> Fixed z BC bug on GPU.

src/output_writers.jl
=> Multiple NetCDF file naming schemes

src/Oceananigans.jl, src/equation_of_state.jl, src/time_steppers.jl, test/runtests.jl, test/test_golden_master.jl
=> Buoyancy update in linear time.

examples/wind_stress.jl
=> Wind stress example.

examples/seasonal_cycle.jl
=> Mixed layer seasonal cycle simulation example

Project.toml, src/Oceananigans.jl
=> Add version check for Julia 1.1.

src/planetary_constants.jl
=> Planetary constants for Europa and Enceladus, and f(latitude).

Project.toml, examples/baroclinic_instability.jl, src/Oceananigans.jl, src/boundary_conditions.jl
Note: this is essentially how we'd tackle #163.
=> Adapting BoundaryCondition with AbstractArray to play nice with CUDA

examples/deep_convection.jl, examples/utils.jl
fix few problems in deep_convection example (and in plotting utils)
=> Fix deep convection 01

src/Oceananigans.jl, src/diagnostics.jl
Will be useful for pressure solver and time stepping tests, and long running simulations.
=> Velocity divergence kernel and diagnostic.

test/runtests.jl, test/test_time_stepping.jl
It will fail right now but should start passing once #161 is fixed (this test will tell us whether we actually fixed it).
=> Incompressibility test.

examples/internal_wave.jl, examples/utils.jl, src/time_steppers.jl, test/runtests.jl, test/test_dynamics.jl, test/test_time_stepping.jl
Looks like the velocity field is now fully incompressible over time but we need better tests to show this. Will merge once tests are implemented.
Fully resolves #161
cc @sandreza
=> Recompute w from continuity to enforce incompressibility.

README.md, docs/src/index.md, examples/rising_thermal_bubble_2d.jl, examples/rising_thermal_bubble_3d_gpu.jl
=> Update rising thermal bubble examples in README and docs

src/Oceananigans.jl, src/boundary_conditions.jl, src/fieldsets.jl, src/models.jl, test/runtests.jl, test/test_boundary_conditions.jl, test/test_output_writers.jl, test/test_regression.jl, test/test_time_stepping.jl
Builds off @vchuravy's work in #261.
Preliminary design of user API for concrete models. Probably most of the time the user will have to specify boundary conditions prior to building the model. We'll have to come up with good syntax for that. What we have is ok, but can be improved.
The checkpointing tests currently fail, I think because they attempt to change the types of the some of the model fields.
=> Be more concrete

src/time_steppers.jl
Requires https://github.com/JuliaGPU/CUDAdrv.jl/pull/144 and https://github.com/JuliaGPU/CUDAnative.jl/pull/416 (i.e. master of both packages).
=> Dynamic launch config.

src/poisson_solvers.jl, src/time_steppers.jl, test/test_poisson_solvers.jl
`launch_config` could probably be generalized with an `arch` argument to work on both GPUs and CPUs, but I'll leave that to you guys.
=> Use a dynamic launch config for more kernels

src/diagnostics.jl, src/poisson_solvers.jl, src/time_steppers.jl, test/test_poisson_solvers.jl
Cube blocks should facilitate shared memory reuse.
=> Generalize indices in the z dimension

README.md
cc @leios @maleadt Hope this is okay with you guys!
=> Add James and Tim to dev team

benchmark/benchmark_eddying_channel.jl, benchmark/benchmark_free_convection.jl, benchmark/benchmark_static_ocean.jl, benchmark/benchmark_utils.jl
```
1xCPU 256^3 Float64
Static ocean:    4.80 s
Free convection: 4.86 s
Eddying channel: 5.45 s
P100 256^3 Float64
Static ocean:    87.4 ms (55x)
Free convection: 86.9 ms (56x)
Eddying channel: 145  ms (38x)
```
=> More benchmarks

sandbox/idealized_seasonal_cycle.jl, src/Oceananigans.jl, src/fields.jl, src/models.jl, src/time_step_utils.jl
A new PR combining #291 and #292.
cc @sandreza
=> Idealized seasonal cycle simulation v2

src/boundary_conditions.jl
Should be `Δz^2` instead of `Δz`.
=> Fix calculation of Value boundary conditions

examples/utils.jl, sandbox/eddying_channel.jl, src/fields.jl, src/time_steppers.jl, src/utils.jl, test/test_models.jl
Reverts climate-machine/Oceananigans.jl#337
=> Revert "Kernel for setting initial conditions so set_ic! runs fast on GPUs"

docs/src/algorithm.md, examples/deepening_mixed_layer.jl, sandbox/do_cthulhu.jl, sandbox/plot_channel_frames.py, sandbox/plot_oceananigans_output_contourf3d.py, sandbox/rayleigh_benard_passive_tracer.jl, sandbox/simple_flux.jl, src/boundary_conditions.jl, src/fields.jl, src/halo_regions.jl, src/models.jl, src/output_writers.jl, src/poisson_solvers.jl, src/time_steppers.jl, src/utils.jl, test/test_boundary_conditions.jl, test/test_forcings.jl, test/test_regression.jl
This has been bothering me for a while...
=> Clean trailing whitespace and convert tabs to spaces.

test/test_diagnostics.jl
I forgot I left it at 128^3 when it should have been 16^3.
=> Fix diagnostics test problem size

Manifest.toml, Project.toml, examples/deepening_mixed_layer.jl, src/Oceananigans.jl, src/models.jl
Reverts climate-machine/Oceananigans.jl#378
=> Revert "Update CUDA packages to get rid of CUDA errors on CPU and use CUDAapi.has_cuda()"

Project.toml
=> Bump version to 0.10.1

Project.toml
=> Bump version to v0.11.0

examples/deepening_mixed_layer.jl, test/runtests.jl, test/test_examples.jl
Thanks @jm-c and @christophernhill for the idea.
Currently fails as examples have gone stale so I'll fix this.
I'll also add one for `internal_wave.jl`.
Resolves #415
=> Search and replace testing for example scripts

README.md
=> Update rising thermal bubble example in README

examples/netcdf_ouput_example.jl
=> Fixes netcdf example

Project.toml
For automatic package registration: https://github.com/JuliaRegistries/General/pull/5943
=> Add compat bounds for Cassette

docs/src/library.md
Things got out of date once things started moving to submodules.
=> Update public API documentation

src/utils.jl
=> Document convinient unit definitions

src/Oceananigans.jl, src/buoyancy.jl, test/test_time_stepping.jl
Obviously we haven't used it yet...
=> Fix and test `RoquetIdealizedNonlinearEquationOfState`

Project.toml, docs/src/model_setup/forcing_functions.md
@suyashbire1 and I found some typos.
=> Update forcing function model setup documentation

src/Models/model.jl, src/TimeSteppers/kernels.jl
Should be useful for @arnscheidt's 2D models (also @masonrogers14).
=> Allow 2D GPU models

src/Fields/set!.jl, test/test_fields.jl
=> Import CUDAnative in Fields submodule

.gitignore, docs/make.jl, examples/eady_turbulence.jl, examples/internal_wave.jl, examples/ocean_convection_with_plankton.jl, examples/ocean_wind_mixing_and_convection.jl, examples/one_dimensional_diffusion.jl, examples/two_dimensional_turbulence.jl, src/BoundaryConditions/apply_flux_bcs.jl, test/test_examples.jl
=> Update examples and test them again

.github/workflows/CompatHelper.yml
For more information, see: https://github.com/bcbi/CompatHelper.jl
=> Add CompatHelper as a GitHub action

src/Fields/field_tuples.jl, test/test_fields.jl
This PR redoes the work of #701, except it adds a few more methods to make it even more robust.
After this is merged we should revisit #707.
=> Fix has_velocities again

Project.toml, examples/two_dimensional_turbulence.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/Fields/field.jl
This PR simply cherry picks the commits from #698, which were accidentally reverted with #697 was merged.
=> Consistent Field API again

src/Forcing/parameterized_forcing.jl, src/Oceananigans.jl
Will include with v0.29.0 (#738)
=> Export `ParameterizedForcing` and fix docstring

src/Oceananigans.jl
Looks like I forgot to do this in #731. Will include with v0.29.0 (#738).
=> Export `TEOS10`

examples/internal_wave.jl
Initial condition did not satisfy the continuity equation.
Also the PR improves the plot aesthetics.
=> Fix the internal wavegroup example

docs/make.jl, examples/internal_wave.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, src/SurfaceWaves.jl
In addition to fixing a bug in `SurfaceWaves.jl`, this example adds `langmuir_turbulence.jl` to the docs build.
=> Fixes a bug in SurfaceWaves.jl, plus examples touch up

README.md
=> Update new repository's URLs

README.md
=> Fix bitly link in README

.appveyor.yml, .gitlab-ci.yml, .travis.yml, Manifest.toml, Project.toml, src/AbstractOperations/AbstractOperations.jl, src/Architectures.jl, src/BoundaryConditions/BoundaryConditions.jl, src/Fields/field.jl, src/Fields/set!.jl, src/Models/incompressible_model.jl, src/Oceananigans.jl, src/OutputWriters/OutputWriters.jl, src/Solvers/Solvers.jl, src/TimeSteppers/TimeSteppers.jl, src/TurbulenceClosures/TurbulenceClosures.jl, src/Utils/launch_config.jl, test/runtests.jl
Need to update README and docs to mention the new Julia 1.4+ requirement.
=> Update to Julia 1.4 and CUDA.jl

.gitignore, docs/Manifest.toml, docs/Project.toml, docs/bibliography.jl, docs/citations.jl, docs/make.jl, docs/oceananigans.bib, docs/src/appendix/fractional_step.md, docs/src/appendix/staggered_grid.md, docs/src/numerical_implementation/large_eddy_simulation.md, docs/src/numerical_implementation/poisson_solvers.md, docs/src/numerical_implementation/spatial_operators.md, docs/src/numerical_implementation/turbulence_closures.md, docs/src/physics/turbulence_closures.md, docs/src/references.md, docs/src/verification/lid_driven_cavity.md, docs/src/verification/stratified_couette_flow.md, docs/src/verification/taylor_green_vortex.md
This PR **finally** adds proper citations that link to a references page all generated from an `oceananigans.bib` file. This is now possible thanks to the new Bibliography.jl package which I've used to hack in a Documenter.jl "plugin" at https://github.com/ali-ramadhan/DocumenterBibliographyTest.jl
This is currently the last action item for the JOSS submission.
The code that handles citations and bibliography expansion is a little messy and will hopefully evolve into a proper Documenter.jl plugin but for now I've copy pasted the code into Oceananigans.jl until the plugin has stabilized in some form. The `@cite` and `@bibliography` syntax should remain the same though.
=> BibTeX citations and references in the docs

README.md
Forgot to do this as part of resolving issue #773
=> Update README: bitly to direct link

src/OutputWriters/checkpointer.jl, src/OutputWriters/output_writer_utils.jl, test/test_output_writers.jl
Fixes GPU to CPU loading and writing fields with function boundary conditions
=> Fixes checkpointer GPU to CPU loading and writing fields with function boundary conditions

src/OutputWriters/checkpointer.jl, src/OutputWriters/output_writer_utils.jl, test/test_output_writers.jl
Reverts CliMA/Oceananigans.jl#797
@glwagner Think you accidentally merged #797 as we weren't fully done with it yet. I might have accidentally requested review...
=> Revert "Fixes checkpointer GPU to CPU loading and writing fields with function boundary conditions"

docs/make.jl
=> Fixes wrong page list for example_pages in docs

src/BoundaryConditions/apply_flux_bcs.jl, src/BoundaryConditions/apply_normal_flow_bcs.jl, src/BoundaryConditions/apply_value_gradient_bcs.jl, src/BoundaryConditions/fill_halo_regions.jl, src/TimeSteppers/adams_bashforth.jl, src/TimeSteppers/generic_time_stepping.jl, src/TimeSteppers/time_stepping_kernels.jl, src/TurbulenceClosures/turbulence_closure_implementations/verstappen_anisotropic_minimum_dissipation.jl
Hopefully resolves #816, and addresses https://github.com/CliMA/Oceananigans.jl/pull/805#pullrequestreview-454050354.
=> Adds barriers at the top of many kernel launches

examples/two_dimensional_turbulence.jl
Not a big issue, but can confuse a beginner trying to play with the examples (like me).
=> Fix plot in example

README.md
=> Fix performance benchmarks dead link in README

examples/ocean_wind_mixing_and_convection.jl
=> fix tradient -> gradient

src/BoundaryConditions/boundary_condition_types.jl
=> Explanation of `Flux` BC in docstring

src/Oceananigans.jl
=> Export `{Isotropic, Anisotropic}Diffusivity`

src/OutputWriters/netcdf_output_writer.jl
=> Recast `global_attributes` into `Dict{Any,Any}`

docs/make.jl, docs/src/library.md, docs/src/model_setup/boundary_conditions.md, docs/src/numerical_implementation/boundary_conditions.md
Last minute doc improvements for JOSS. Resolves #610
=> Small documentation improvements and fixes for JOSS

src/Grids/grid_utils.jl
=> Update docstrings for `{x,y,z}nodes` functions

src/Solvers/channel_pressure_solver.jl, src/Solvers/triply_periodic_pressure_solver.jl, test/test_pressure_solvers.jl
=> Fix some CuArray scalar operations

benchmark/benchmark_static_ocean.jl, src/Oceananigans.jl
=> Use `FFTW.set_num_threads` if more than 1 thread is available

src/Diagnostics/average.jl, test/test_diagnostics.jl
=> Fix size for averages with halos of face-centered fields along bounded dimensions

test/test_time_stepping.jl
=> Update test to also catch multiple of 16 bug

src/Models/incompressible_model.jl
=> Updates docstring for IncompressibleModel

src/AbstractOperations/computations.jl, src/BoundaryConditions/zero_halo_regions.jl, src/Diagnostics/average.jl, src/Fields/abstract_field.jl, src/Grids/grid_utils.jl, src/Oceananigans.jl
=> Fixes bug in zero_halo_regions that uses wrong indices for face-located fields in Bounded directions

src/TurbulenceClosures/TurbulenceClosures.jl, src/TurbulenceClosures/turbulence_closure_implementations/nothing_closure.jl, src/Utils/with_tracers.jl, test/test_time_stepping.jl
=> Support closure=nothing; resolves #939

src/Fields/computed_field.jl
~~Since this wasn't caught by tests, I think this PR should add a test.~~
A test will be added in an imminent PR.
=> Fixes bug in adapt_structure for ComputedField

src/Fields/computed_field.jl
=> More specific imports from KernelAbstractions in Fields module to solve identifier conflict warnings

paper/paper.bib
cx https://github.com/openjournals/joss-reviews/issues/2018#issuecomment-694858923
=> Updating Julia DOI

src/Models/incompressible_model.jl, src/OutputWriters/checkpointer.jl, src/TimeSteppers/TimeSteppers.jl, src/TimeSteppers/quasi_adams_bashforth_2.jl, src/TimeSteppers/runge_kutta_3.jl
=> Fixes timestepper docstrings and simplifies constructor

docs/src/model_setup/coriolis.md
=> Fixes typo in docs for non-traditional beta plane and simplifies language

src/Buoyancy/seawater_buoyancy.jl
=> Completes docstring for SeawaterBuoyancy constructor

src/TimeSteppers/velocity_and_tracer_tendencies.jl
=> Cleans up docstrings for tendency kernels

src/Simulations/run.jl, src/Simulations/simulation.jl
=> Changes default progress from nothing to an innocuous function

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/computations.jl, src/Diagnostics/Diagnostics.jl, src/Diagnostics/average.jl, src/Diagnostics/nan_checker.jl, src/Diagnostics/time_series.jl, src/Oceananigans.jl, src/OutputWriters/OutputWriters.jl, src/OutputWriters/checkpointer.jl, src/OutputWriters/jld2_output_writer.jl, src/OutputWriters/netcdf_output_writer.jl, src/OutputWriters/windowed_time_average.jl, src/Simulations/run.jl, test/runtests.jl, test/test_output_writers.jl
=> Adds bangs and conventionalizes signatures of run_diagnostic! and write_output!

src/BoundaryConditions/coordinate_boundary_conditions.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/BoundaryConditions/fill_halo_regions.jl, test/test_boundary_conditions.jl, test/test_time_stepping_bcs.jl
Adds some tests too.
Resolves #637
=> Moves boundary condition aliases to FieldBoundaryConditions

Project.toml
Would be good to tag a release once the current batch of PRs is merged.
=> Bump v0.38.0

examples/two_dimensional_turbulence.jl, test/test_examples.jl
This PR uses the latest of the time-stepping and advection schemes to produces a two-dimensional turbulence example that resembles two-dimensional turbulence :)
=> Better two-dimensional turbulence Docs example

src/OutputWriters/checkpointer.jl
=> Fix bug in `restore_from_checkpoint`

.buildkite/pipeline.yml
Should at least help with detecting doctest failures and we want to build+deploy docs on Buildkite anyways.
=> Build and test but do not deploy docs on Buildkite

src/Fields/field.jl, src/Forcings/continuous_forcing.jl, src/Forcings/discrete_forcing.jl, src/Forcings/forcing.jl, src/Forcings/model_forcing.jl, src/Forcings/relaxation.jl, test/test_forcings.jl
Resolves #1010
This PR also adds an annotation to `DiscreteForcing` that may help with GPU compilation (its not 100% clear now however).
=> Adds adapt_structure for ContinuousForcing

src/Utils/Utils.jl, src/Utils/units.jl
For the ultimate in bike-shedding PRs.
=> Teach Oceananigans about plural nouns

Project.toml
Should tag a new release once PRs #1014 and #997 are merged.
=> Bump v0.41.0

Project.toml
To be merged once #1093 and #1099 are in.
Release notes:
* Adds support for "picking up" a simulation from a checkpoint via the keyword `pickup=true`, `pickup=checkpoint_iteration::Int` and `pickup=checkpont_filepath::String` in `run!(simulation)` (#1082)
* Adds a function `set!(model, checkpoint_filepath)` for "setting" a model state to the state recorded in a checkpoint file (#1082)
* Adds support for "field-dependent" boundary conditions similar to field-dependent forcing terms (#1093)
* Beautifies and cleans up many of the examples, including getting them to build faster on Travis (#1099)
=> Bump version to 0.44.0

Dockerfile, Manifest.toml, Project.toml, README.md, docs/src/installation_instructions.md, src/Oceananigans.jl
Gotta keep up with all the improvements in CUDA v2. Merging this PR means that Oceananigans.jl will now require Julia 1.5+.
=> Upgrade to CUDA v2

examples/kelvin_helmholtz_instability.jl
This PR brings back K-H example in manageable resolution...
[I accidentally pushed a high-resolution version I was running last night.... 🤦‍♂️ Moral of the story: never merge before making sure caffeine has kicked in...]
=> Brings back sanity in KH example

examples/langmuir_turbulence.jl
The preview will be available here:
https://clima.github.io/OceananigansDocumentation/previews/PR1148/generated/langmuir_turbulence/
=> Fixes broken admonition in langmuir_turbulence.jl

src/OutputWriters/netcdf_output_writer.jl
=> Append to NetCDF file if it already exists

examples/convecting_plankton.jl, examples/eady_turbulence.jl, examples/internal_wave.jl, examples/kelvin_helmholtz_instability.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/one_dimensional_diffusion.jl, examples/two_dimensional_turbulence.jl
This PR adds explicit install of required packages for each example.
This is related to the discussion in #1149.
=> Explicit install of deps in Examples

src/Simulations/run.jl
=> Allow `pickup=true` with zero checkpoints

examples/eady_turbulence.jl
Enhancement in the Eady turbulence example.
=> Slight terminology upgrade in eady example

src/Simulations/time_step_wizard.jl, test/test_simulations.jl
=> Teach wizard about minimum time step

Project.toml
Been a lot of changes since v0.44.1 (including some bug fixes) but don't think there have been any breaking changes (or massive new features) so was thinking we should tag and release v0.44.2.
=> Bump v0.44.2

src/Models/IncompressibleModels/incompressible_model.jl, test/test_dynamics.jl, test/test_incompressible_models.jl
Apologies to everyone who's been frustrated by this in the past... (@suyashbire1, @whitleyv, @tomchor, ...)
Resolves #1204
=> Error if expected input is not a NamedTuple

src/OutputWriters/netcdf_output_writer.jl
=> Respect create/clobber mode in NetCDFOutputWriter

.buildkite/pipeline.yml, validation/convergence_tests/ConvergenceTests/OneDimensionalCosineAdvectionDiffusion.jl
=> Properly clean up Buildkite environments

.buildkite/pipeline.yml
(the PR subject is, pretty much, self explanatory)
=> Use latest Julia in buildkite pipeline

src/OutputWriters/netcdf_output_writer.jl, src/Simulations/run.jl, test/test_output_writers.jl
Resolves #1227
cc @suyashbire1 @tomchor
=> Open/close NetCDF at the start/end of `run!`

src/Simulations/run.jl, src/TimeSteppers/quasi_adams_bashforth_2.jl, src/TimeSteppers/runge_kutta_3.jl
Resolves #1254
Resolves #1247 (hopefully)
=> Handle edge case of Δt = 0 for `IncompressibleModel`

Project.toml, src/Models/IncompressibleModels/set_incompressible_model.jl, test/test_abstract_operations.jl, test/test_incompressible_models.jl
Resolves #1027
Resolves #1252
~~Needs tests.~~
=> Adds incompressiblity enforcement and state update to set!

test/test_shallow_water_models.jl
=> Set h=1 in shallow water time stepping tests

src/Fields/field.jl
=> Fixes mangled docstring for Field

Manifest.toml, Project.toml
Updated CUDA.jl to v2.3.0 since it was downgraded in PR #1295 for some reason.
Waiting for https://github.com/JuliaGPU/CUDA.jl/pull/626 and tagged release to update to Adapt v3.0.0 as well.
=> Update to CUDA v2.4.0

src/OutputWriters/netcdf_output_writer.jl
Closes #1208 
This is my first PR to this repository, so let me know if I did anything that wasn't considered best practices!
=> Creates long_name and units attributes for the time dimension in netcdf outputs

examples/kelvin_helmholtz_instability.jl
I reminded myself that there is some motivation/explanation just before the beginning of the section **A Powerful algorithm**.
I added some more clarifications. @jklymak what do you think?
=> Adds explanatory remark on KH power-method

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/binary_operations.jl, src/AbstractOperations/derivatives.jl, src/AbstractOperations/multiary_operations.jl, src/AbstractOperations/unary_operations.jl, src/Buoyancy/buoyancy_field.jl, src/Fields/abstract_field.jl, src/Fields/averaged_field.jl, src/Fields/computed_field.jl, src/OutputWriters/fetch_output.jl, test/test_abstract_operations.jl, test/test_averaged_field.jl
This PR extends the capability of our "conditional computation" framework wherein the "re-calculation" of expensive diagnostics and computations may be avoided if possible.
Previously, expensive field recalculations were avoided *only* at the outermost level (if the field were used directly in output), which in hindsight doesn't seem very useful since we often average or otherwise reduce expensive calculations for output (if we were not reducing an expensive calculation, we could simply calculate it offline).
Avoiding recalculation for field "dependencies" requires adding a third function for field computation: we now have `compute_at!(field, time)`, `conditional_compute!(field, time)`, and `compute!(field, time)`.
`compute_at!(field, time)` is the outermost function called by …
=> Implements compute_at! pattern for conditional computation

src/Advection/upwind_biased_advective_fluxes.jl, src/Models/ShallowWaterModels/calculate_shallow_water_tendencies.jl, src/Models/ShallowWaterModels/shallow_water_advection_operators.jl, src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl
Co-authored with @francispoulin .
=> Adds div_uhvh for calculating mass flux divergence in h_tendency

src/Fields/kernel_computed_field.jl
Same typo fix as #1333 but done securely for Buildkite
=> Tiny doc typo in kernel_computed_fields

examples/langmuir_turbulence.jl, src/Models/IncompressibleModels/calculate_tendencies.jl, src/Models/IncompressibleModels/incompressible_model.jl, src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl, src/Oceananigans.jl, src/StokesDrift.jl, test/runtests.jl, test/test_stokes_drift.jl, test/test_surface_waves.jl
Changed every instance of `surface_waves` to `stokes_drift`.
Closes #1331
=> Changed notation from surface_waves to stokes_drift

src/Models/ShallowWaterModels/shallow_water_model.jl
=> Add missing import for shallow water model

src/Fields/kernel_computed_field.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/1370
=> Changed KernelComputedField's docstring to the user-facing dfunction

src/Fields/kernel_computed_field.jl, test/test_kernel_computed_field.jl
=> Changed field_dependencies to computed_dependencies in KernelComputedField

src/Models/IncompressibleModels/non_dimensional_model.jl, src/Models/Models.jl, src/Oceananigans.jl, test/test_incompressible_models.jl
=> Rename NonDimensionalModel to NonDimensionalIncompressibleModel

src/Diagnostics/Diagnostics.jl, src/OutputWriters/OutputWriters.jl, src/OutputWriters/windowed_time_average.jl, src/Simulations/run.jl, test/test_output_writers.jl
=> Fix warnings about conflicting existing identifiers

src/Coriolis/hydrostatic_spherical_coriolis.jl
cc @sandreza this affects your Rossby-Haurwitz test.
=> Fixes sign error in HydrostaticSphericalCoriolis!

src/BoundaryConditions/show_boundary_conditions.jl
=> Adds a bctype_str method for Nothing boundary conditions

examples/shallow_water_Bickley_jet.jl
I know that we need U to be defined as a constant for this to work.  I figured why not define the other constants as well but don't think we need to.  I'm happy with only making the required changes if people prefer.
=> Make Bickley example work on GPU

Project.toml, docs/make.jl, docs/src/library.md, docs/src/model_setup/boundary_conditions.md, examples/convecting_plankton.jl, examples/eady_turbulence.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, src/BoundaryConditions/show_boundary_conditions.jl, src/Oceananigans.jl
Resolves #1140
This is a breaking change unfortunately.
cc @drozzy
=> Long-form boundary condition constructors

README.md, docs/make.jl, docs/src/index.md, docs/src/publications.md
This PR updates the README and cleans it up a bit since it was out of date, and adds a section on "citing" Oceananigans.jl and a page with a list of publications using Oceananigans.jl.
Open to suggestions if anyone thinks something is missing or could be better!
Resolves #973
Resolves #1101
=> Add "citing" section and list of publications using Oceananigans.jl (also update README)

src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
=> Extends PrescribedVelocityField to support concrete Fields (not just functions)

src/Fields/field_slicer.jl, test/test_jld2_output_writer.jl, test/test_netcdf_output_writer.jl
Resolves #1512.
Needs tests. Docstring for `FieldSlicer` could probably be spruced up too.
=> Extends FieldSlicer to support StepRange indices

src/Fields/abstract_field.jl, test/test_field.jl
Reverts CliMA/Oceananigans.jl#1557
See https://github.com/CliMA/Oceananigans.jl/pull/1559#issuecomment-816169253
=> Revert "Adding norm for fields with some tests."

Project.toml
We need this to tag a new release.
=> Add compat bounds for Tullio.jl

docs/oceananigans.bib, docs/src/physics/coriolis_forces.md
As discusse in #1591 .   Now I have to create a reference.
=> Fix typo in coriolis_forces.md

src/CubedSpheres/CubedSpheres.jl, src/CubedSpheres/cubed_sphere_faces.jl, src/CubedSpheres/cubed_sphere_halo_filling.jl, src/CubedSpheres/cubed_sphere_kernel_launching.jl, src/CubedSpheres/cubed_sphere_set!.jl, src/CubedSpheres/cubed_sphere_utils.jl, src/Fields/field.jl, src/Fields/kernel_computed_field.jl, test/test_cubed_sphere_halo_exchange.jl, test/test_cubed_spheres.jl
=> KernelComputedField CubedSphere support plus internal CubedSpheres refactoring

docs/src/appendix/staggered_grid.md, docs/src/numerical_implementation/finite_volume.md
PR title is self-explanatory.
Closes #1615.
=> Fix for schematic not showing in Docs/Appandix/Staggered Grid

src/Fields/set!.jl
Noticed while perusing code with @tomchor
=> Use copyto! to transfer data from GPU to CPU

docs/make_example.jl, docs/src/library.md
=> Adds Grids/vertically_stretched_rectilinear_grid.jl in Docs

src/Distributed/distributed_shallow_water_model.jl, src/Models/ShallowWaterModels/shallow_water_model.jl, test/test_distributed_models.jl, test/test_shallow_water_models.jl
Assert that the topology is Flat in the vertical and also have a test that `Periodic` or `Bounded` in the vertical creates an error.
=> assert shallow water model is flat and add test

docs/src/using_gpus.md
=> Replaces a leftover Julia 1.5 -> 1.6

benchmark/benchmark_advection_schemes.jl, benchmark/benchmark_equations_of_state.jl, benchmark/benchmark_fft_based_poisson_solvers.jl, benchmark/benchmark_fourier_tridiagonal_poisson_solver.jl, benchmark/benchmark_incompressible_model.jl, benchmark/benchmark_lagrangian_particle_tracking.jl, benchmark/benchmark_shallow_water_model.jl, benchmark/benchmark_time_steppers.jl, benchmark/benchmark_topologies.jl, benchmark/benchmark_tracers.jl, benchmark/benchmark_turbulence_closures.jl, benchmark/benchmark_vertically_stretched_incompressible_model.jl
Doing exactly what the title says.  This was done with @henryg888.
=> Changed -> to to in the benchmark scripts

docs/make.jl
This PR homogenizes the title of the model section in the Docs/Physics section.
=> Docs/Physics: Shallow Water Dynamics -> Shallow Water Model

docs/Manifest.toml, docs/oceananigans.bib
=> Updates packages used for building the Docs

docs/src/library.md
This PR updates the Docs/Library section with latest docstrings.
Closes #1713.
=> Update Docs/API Library section

src/BoundaryConditions/continuous_boundary_function.jl, src/Coriolis/hydrostatic_spherical_coriolis.jl, src/Grids/grid_utils.jl, src/Grids/regular_rectilinear_grid.jl, src/ImmersedBoundaries/ImmersedBoundaries.jl, src/ImmersedBoundaries/grid_fitted_immersed_boundary.jl, src/Oceananigans.jl, validation/barotropic_gyre/barotropic_gyre.jl, validation/barotropic_gyre/visualize_barotropic_gyre.jl
Supercedes #1717 .
The validation NaN's right now with the implemented immersed boundary.
@christophernhill take over from here?
=> Bunch o' fixes to get `ImmersedBoundaryGrid(RegularLatitudeLongitudeGrid)` working

benchmark/benchmark_shallow_water_model.jl, benchmark/strong_scaling_shallow_water_model.jl, benchmark/strong_scaling_shallow_water_model_single.jl, benchmark/weak_scaling_shallow_water_model.jl, benchmark/weak_scaling_shallow_water_model_single.jl, src/Distributed/distributed_shallow_water_model.jl
With @henryg888, we made these changes to make these shallow water benchmarks.
Next, we will introduce code to plot the results, as can be found in #1722
=> Introduce `Flat` to shallow water benchmarks

examples/ocean_wind_mixing_and_convection.jl
I believe there were a couple of typos in the units of the surface heat flux
=> Fixed units in ocean wind mixing example

docs/src/appendix/fractional_step.md, docs/src/numerical_implementation/poisson_solvers.md, docs/src/numerical_implementation/pressure_decomposition.md, docs/src/numerical_implementation/time_stepping.md
=> Docs: Change pressure symbol φ -> p

src/AbstractOperations/show_abstract_operations.jl
FIxes this issue:
```julia
julia> grid = RegularRectilinearGrid(size=(8, 8, 8), extent=(1, 1, 1))
RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}
domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
topology: (Periodic, Periodic, Bounded)
resolution (Nx, Ny, Nz): (8, 8, 8)
halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (0.125, 0.125, 0.125)
julia> model = IncompressibleModel(grid=grid, closure=IsotropicDiffusivity(ν=1e-6))
IncompressibleModel{CPU, Float64}(time = 0 seconds, iteration = 0) 
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=8, Ny=8, Nz=8)
├── tracers: (:T, :S)
├── closure: IsotropicDiffusivity{Oceananigans.TurbulenceClosures.ExplicitTimeDiscretization, Float64, NamedTuple{(:T, :S), …
```
=> Added show method to KernelFunctionOperation

docs/src/contributing.md
This PR updates the instructions for building the docs locally.
@tomchor, @francispoulin: could you let me know if these new instructions do the job for you? Please try on a fresh clone of the repo.
Closes #1542. (Or at least that's the hope....)
=> Updates building docs instructions

docs/make.jl
=> Docs: adds Oceananigans' path first in `LOAD_PATH` order

src/Grids/Grids.jl
=> Fix a docstring

CONTRIBUTING.md, docs/src/contributing.md
I've been finding parts of the code that are formatted inconsistently so I think that including this bullet point is important for future contributors.
=> Guidelines for style in CONTRIBUTING.md and clarity about pull requests

test/test_averaged_field.jl
=> Adds test for race condition in `compute!(::AveragedField)`

src/Models/IncompressibleModels/update_hydrostatic_pressure.jl
=> Use correct grid metric for hydrostatic pressure integral

validation/periodic_advection/periodic_advection.jl
=> Updates `validation/periodic_advection.jl`

src/BuoyancyModels/seawater_buoyancy.jl
=> Homogenizes notation for temperature `T` and salinity `S`

src/Grids/regular_latitude_longitude_grid.jl
=> Allows `RegularLatitudeLongitudeGrid` with more general longitude range

Manifest.toml, Project.toml
- FFTW v1.4.2 ⇒ v1.4.3
- JLD2 v0.4.10 ⇒ v0.4.11
- OffsetArrays v1.10.0 ⇒ v1.10.2
- MPI v0.18.0 ⇒ v0.18.1
- Tullio v0.2.14 ⇒ v0.3.0
- StructArrays v0.5.1 ⇒ v0.6.0
=> Update several packages

src/OutputWriters/windowed_time_average.jl, test/test_output_writers.jl
=> Throw ArgumentError for window > interval in AveragedTimeInterval

src/Fields/broadcasting_abstract_fields.jl, src/Fields/mapreduce_abstract_fields.jl
This may have been the cause of #1767.
=> Make broadcasting depend on CUDA default stream

src/ImmersedBoundaries/ImmersedBoundaries.jl
Otherwise we get a warning every time-step on the GPU.
cc @whitleyv
=> Adds warning-less inner constructor for ImmersedBoundaryGrid

docs/Manifest.toml
=> Update packages for docs

docs/src/physics/turbulence_closures.md
Closes https://github.com/CliMA/Oceananigans.jl/issues/1856
=> Fix typo in AMD closure in docs

src/Grids/new_data.jl
=> Updates `offset_indices` docstrings

examples/horizontal_convection.jl
There are always things that got away :)
Main fix is that we no longer save χ as the text was implying but we compute it post run.
=> Some fixes in horizontal convection example

examples/shallow_water_Bickley_jet.jl
=> Use CPU for shallow water Bickley jet

docs/Manifest.toml, docs/make.jl
There was breaking changes in Literate.jl v2.9; see https://github.com/fredrikekre/Literate.jl/blob/v2.9.0/CHANGELOG.md#290---2021-07-09
=> Updates Docs packages

validation/mpi_shallow_water/mpi_shallow_water_turbulence.jl
Updated the basic _mpi_shallow_water_ example to work with the latest Oceananigans.jl version
=> Fixed mpi_shallow_water example

docs/src/appendix/benchmarks.md
Reverts CliMA/Oceananigans.jl#1930
Resolves #1949
=> Revert "Updating Benchmark Docs"

docs/src/appendix/benchmarks.md
I created a clean branch from the latest version of master that passed the documentation buildkite test. Looking at my old updated `benchmarks.md` through a markdown viewer/editor and I saw that a table that's written in HTML might be causing trouble so I replaced it with a code block quote table.
=> Update benchmarks.md - attempt 2.0

README.md
@navidcy had some second thoughts about the word "rectangle" after merger. What do you think of this change?
=> Rectangular cuboids are not rectangles

docs/src/appendix/library.md, src/Fields/averaged_field.jl
Also adds `AveragedField`, `FunctionField`, and `KernelComputedField` to the docs library.
Resolves #1965 .
@maeckha let me know if this is helpful!
=> Improves AveragedField docstring

src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl, validation/vertical_mixing_closures/gpu_tkevd_ensemble.jl
cc @adelinehillier let us know that this works!
=> Adds support for Arrays of coriolis forces with single column ensemble mode and fixes halo bug

Project.toml
=> Bumps patch release after bug fixes via #1744

src/Coriolis/beta_plane.jl, src/Coriolis/f_plane.jl, src/Coriolis/non_traditional_beta_plane.jl
=> Adds clarification for `latitude` units in `Oceananigans.Coriolis`

CITATION.cff
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
=> Create CITATION.cff file

validation/stratified_couette_flow/stratified_couette_flow.jl
=> Uses ValueBoundaryCondition in stratified couette flow validation test

src/Fields/regridding_fields.jl
=> Adds docstring + example for `regrid!`

Project.toml
Bumping down to 0.64.0 since #1971 accidentally bumped too far to 0.65.0.
=> Bump down to 0.64.0

Project.toml
=> Bump to 0.64.1

examples/ocean_wind_mixing_and_convection.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/2043
=> Changes vertical stretching function back in Ocean wind + convection example

src/CubedSpheres/CubedSpheres.jl, src/Simulations/nan_checker.jl
~This removes the warning mentioned in #2068 but does not fully resolve the issue.~
Closes #2068
=> Fix `NaNChecker` for cubed sphere

src/BuoyancyModels/seawater_buoyancy.jl
=> Fix `SeawaterBuoyancy` docstring

src/Fields/field_tuples.jl, src/Models/NonhydrostaticModels/NonhydrostaticModels.jl, src/Models/NonhydrostaticModels/update_hydrostatic_pressure.jl, src/Models/NonhydrostaticModels/update_nonhydrostatic_model_state.jl, src/Models/NonhydrostaticModels/velocity_and_tracer_tendencies.jl, src/Operators/derivative_operators.jl
=> Avoid computing hydrostatic pressure when z is Flat

docs/src/appendix/library.md, src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl, src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl, src/Solvers/batched_tridiagonal_solver.jl, src/Solvers/fft_based_poisson_solver.jl, src/Solvers/preconditioned_conjugate_gradient_solver.jl
Before this PR:
After this PR:
=> Add `Solvers` docstrings in Docs/Library  + better docstring for `ImplicitFreeSurface`

src/Grids/Grids.jl, src/Grids/grid_utils.jl
=> Remove duplicate `size` method redefinitions

docs/src/model_setup/grids.md, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl
=> Even clearer `show(io, ::AbstractGrid)`

Project.toml, docs/src/model_setup/buoyancy_and_equation_of_state.md, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
=> Removes warning from `HydrostaticFreeSurfaceModel`

Project.toml
=> Bump to 0.67.1

src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
=> Resolves conflict between `CUDA.device` and `Oceananigans.Architectures.device`

validation/cubed_sphere_eddying_aquaplanet/cubed_sphere_eddying_aquaplanet.jl
This has drifted a bit from latest APIs. 
This updates to make validation cube sphere eddying aquaplanet great again. 
Will allow to be used to start testing @simone-silvestri @jm-c @glwagner fixed up immersed boundaries with functioning implicit vertical terms plus working stretched grid 👍 awesomeness.
=> Rehabilitating validation/cubed_sphere_eddying_aquaplanet

Project.toml
This captures a few changes, such as updates to `show`, `Callback` `parameters`, new field types, and boundary condition validation.
=> Bump to 0.68.3

src/AbstractOperations/conditional_operations.jl, src/Fields/constant_field.jl
Quick fixes as I recklessly merged a _non-test-passing_ PR
=> quick fixes

src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
=> Only show free surface info when there is a free surface

Project.toml, src/OutputWriters/checkpointer.jl, src/OutputWriters/output_writer_utils.jl, test/test_checkpointer.jl
Let's be real; we need tests.
Closes #2223 maybe
=> Tries to generalize checkpointer to work for `HydrostaticFreeSurfaceModel`

Project.toml, docs/src/numerical_implementation/time_stepping.md, src/CubedSpheres/cubed_sphere_faces.jl, src/TimeSteppers/quasi_adams_bashforth_2.jl, src/TimeSteppers/runge_kutta_3.jl, test/test_time_stepping.jl
This PR is an attempt/discussion on how to resolve #2259.
=> Fix bug in `QuasiAdamsBashforth2TimeStepper`

Project.toml
A PR was merged accidentally with the version up to 0.71.5.
=> Downbump to 0.71.4

docs/src/numerical_implementation/boundary_conditions.md
Pointed out by [iury simoes-sousa](https://app.slack.com/team/U034V0WA8TC) -- thanks!
=> Fix missing tracer equation reference in Docs

src/Grids/latitude_longitude_grid.jl
Adds information about setting `topology`.
Closes #1823
=> Updates docstring for `LatitudeLongitudeGrid`

validation/stratified_couette_flow/stratified_couette_flow.jl
=> Update friction velocity definition in `stratified_couette_flow.jl`

docs/oceananigans.bib, src/TimeSteppers/TimeSteppers.jl, src/TimeSteppers/clock.jl, src/TimeSteppers/quasi_adams_bashforth_2.jl, src/TimeSteppers/runge_kutta_3.jl
=> Enhances docstrings for timesteppers

Project.toml
Captures the breaking changes in #2246 .
=> Bump to 0.72.0

.buildkite/pipeline.yml, test/runtests.jl
Timestep tests gave yet again become too long. (~3hrs on gpu)
This PR attempts to split them. Closes #2325.
=> Split timestep tests

docs/src/installation_instructions.md
Based on the discussion with @iuryt on slack I realized that our "Installation instructions" session was a bit barebones.
Here's attempt to re-write with a bit more explanation and "hand-holding", which I think will help users in general. Basically I think we need to touch on how to install Julia (both for personal computers and HPC systems), since that's often the hardest step, and also touch on running the simulations on HPC systems when you need GPUs (which basically means you have to deal with the job scheduler).
This is only my first draft, but suggestions are welcome!
=> A more detailed session for installation instructions

Project.toml, src/OutputWriters/output_writer_utils.jl
=> Serialize grids with CPU architecture

Project.toml, src/BoundaryConditions/fill_halo_regions.jl, src/Operators/products_between_fields_and_grid_metrics.jl
=> Bugfix in `fill_halo` for julia < 1.7

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/computed_field.jl, src/AbstractOperations/metric_field_reductions.jl, src/Fields/field_reductions.jl
=> Add `show` for `Reductions`

src/OutputWriters/output_writer_utils.jl
This PR removes some of the warnings that output writers throw when trying to save or serialize functions to disk.
These warnings are outdated in a way because they are really aimed at users trying to restore models from a checkpoint. Previously, we used to require that an entire model could be deserialized from disk when restoring from a checkpoint. This created special headaches for models that involved user-defined functions. 
But now we have a much better and simpler way for restoring models from a checkpoint. As a result we rarely care whether or not boundary conditions are serialized to disk if they are functions.
=> Fewer warnings from output writers

src/Fields/field_reductions.jl
Removes a sentence that may have been left over from some previous PR.
=> Improve `Reduction` docstring

Project.toml, src/AbstractOperations/computed_field.jl, src/Fields/field.jl, test/test_computed_field.jl, test/test_field.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/2391
=> Fixes and tests `Field(u::Field; indices)` and `Field(u::AbstractOperation; indices)`

src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
=> fix the show for nonhydrostatic model

validation/barotropic_gyre/barotropic_gyre.jl, validation/barotropic_gyre/visualize_barotropic_gyre.jl
Brings barotropic_gyre.jl in sync current code.
=> Make barotropic_gyre.jl work with current code

Project.toml, src/AbstractOperations/show_abstract_operations.jl
=> Fix bug showing AbstractOperations

benchmark/Manifest.toml, benchmark/Project.toml, validation/bickley_jet/bickley_jet.jl, validation/bickley_jet/bickley_utils.jl, validation/bickley_jet/immersed_bickley_jet.jl
This PR splits `validation/bickley_jet.jl` into two scripts (one for the "immersed bickley jet" and one for the "ordinary" bickley jet) and somewhat improves the script for the ordinary bickley jet.
@simone-silvestri I left the "immersed bickley jet" unchanged so you can continue to use it as is.
=> Bickley jet, continued

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/unary_operations.jl
Might help with one of the problems on #2415 .
=> Support `+` as `UnaryOperation`

src/Oceananigans.jl
This solves #2438 
I tested with the following code and it is working
```julia
grid = RectilinearGrid(size=(1, 1, 1), extent=(1, 1, 1))
b = CenterField(grid)
location(b)
```
Returns:
```julia
(Center, Center, Center)
```
=> Add location to export list

Project.toml, src/OutputWriters/jld2_output_writer.jl, src/OutputWriters/netcdf_output_writer.jl, src/OutputWriters/output_writer_utils.jl, test/test_output_writers.jl
=> Updates output writers interface to append extension automatically

src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
This draft PR introduces a few enhancements to `RiBasedVerticalDiffusivity`.
`RiBasedVerticalDiffusivity` imposes viscosities and diffusivities of the form
```
ν₀ * tapering(Ri, Ri_c, Ri_d)
```
where `Ri_c` is a "critical" Richardson number where tapering starts and `Ri_d` is the width of the tapering function.
We have piecewise-linear tapering
```julia
piecewise_linear_tapering = 1 - min(1, max(0, (Ri - Ri_c) / Ri_d))
```
This PR introduces an exponential tapering
```julia
exponential_tapering = exp(- max(0, (Ri - Ri_c) / Ri_d))
```
and hyperbolic tangent tapering
```julia
hyperbolic_tangent_tapering = (1 - tanh((x - x₀) / δ)) / 2
```
(which I haven't tested yet).
I calibrated the piecewise linear case and exponential case using https://github.com/glwagner/LocalOceanClosureCalibration. …
=> Enhancements to `RiBasedVerticalDiffusivity`

Project.toml, src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl, src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl, src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/turbulent_kinetic_energy_equation.jl, validation/vertical_mixing_closures/windy_convection.jl
Part of CATKE's numerics overhaul along with #2426.
@simone-silvestri hope this also improves (CA)TKE + mass flux!
=> Move CATKE diffusivities to vertical cell interfaces

docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md
@zhazorken and I couldn't find information easy on the docs.
=> Adds tracer-specific diffusivity subsection to `model_setup`

examples/langmuir_turbulence.jl, examples/one_dimensional_diffusion.jl, examples/shallow_water_Bickley_jet.jl, examples/tilted_bottom_boundary_layer.jl
=> Convert more examples to plot with Makie

src/ImmersedBoundaries/immersed_boundary_condition.jl, src/Solvers/heptadiagonal_iterative_solver.jl
=> Adapt for `ImmersedBoundaryCondition`

docs/src/model_setup/boundary_conditions.md, src/BoundaryConditions/continuous_boundary_function.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/ImmersedBoundaries/immersed_boundary_condition.jl
=> Regularize Number boundary conditions to eltype(grid)

docs/Manifest.toml, docs/Project.toml, docs/make.jl, docs/make_example.jl, docs/src/model_setup/grids.md, examples/convecting_plankton.jl, examples/horizontal_convection.jl, examples/kelvin_helmholtz_instability.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/shallow_water_Bickley_jet.jl, examples/tilted_bottom_boundary_layer.jl
Follow up to #2553 and #2556.
Deals with partly of what's discussed in #2326 and #2448, namely use Makie for plots.
=> Eliminate Plots as dependency in Docs; use Makie

test/test_matrix_poisson_solver.jl
Just realized I left a bug... the solution was initialized with random numbers and as such was not converging some times. This finally solves the issue of the test not passing (hopefully)
=> Fix matrix solver test take 2

src/Advection/momentum_advection_operators.jl, src/Advection/tracer_advection_operators.jl, src/ImmersedBoundaries/conditional_fluxes.jl
Probably doesn't really matter because of impenetrability....
=> Bug fix in conditional `advective_tracer_flux`

Project.toml, src/Grids/grid_utils.jl, src/Grids/input_validation.jl, src/Grids/rectilinear_grid.jl, src/OutputReaders/field_time_series.jl
=> Fix fatal interaction between FieldTimeSeries construction and input validation

Project.toml, src/TurbulenceClosures/abstract_scalar_biharmonic_diffusivity_closure.jl
Maybe closes #2591 
@mukund-gupta can you check?
=> Add `@inline` to `biharmonic_mask_x`, etc

src/Grids/Grids.jl, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
=> Check for CUDA-enabled device on `grid` construction rather than in model constructors

src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl
Discussed with @simone-silvestri
=> Fix `ShallowWaterModel` closure for tracers in the vector invariant form

src/Utils/schedules.jl
=> Add docstring for `SpecifiedTimes`

src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl
=> Diffusivity for Leith

Project.toml, src/LagrangianParticleTracking/update_particle_properties.jl
I ve introduced a small bug in the previous PR, this solves it
=> Small bugfix

docs/src/appendix/benchmarks.md, src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl, src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl, validation/implicit_free_surface/implicit_surface_solvers_benchmark.jl
=> Fix bug in `validate_fft_implicit_solver_grid `

.github/workflows/TagBot.yml
=> Increase TagBot lookback

Project.toml, src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
=> Fix location of Integrated areas derivatives in the PCG solver

test/test_implicit_free_surface_solver.jl
=> Add test for implicit free surface with immersed boundary

src/Advection/reconstruction_coefficients.jl
=> Fix bug in `num_prod`

src/Simulations/callback.jl
Summary of Callback with parameters gave an error before
=> Fixed bug in Callback summary

src/AbstractOperations/at.jl, src/AbstractOperations/binary_operations.jl, src/AbstractOperations/computed_field.jl, src/AbstractOperations/conditional_operations.jl, src/AbstractOperations/derivatives.jl, src/AbstractOperations/grid_metrics.jl, src/AbstractOperations/unary_operations.jl, src/Advection/centered_reconstruction.jl, src/Advection/momentum_advection_operators.jl, src/Advection/tracer_advection_operators.jl, src/Advection/upwind_biased_reconstruction.jl, src/Fields/field.jl, src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl, src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_variables.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl, src/Models/HydrostaticFreeSurfaceModels/vertical_vorticity_field.jl
@simone-silvestri should we include something in the docstring related to changes induced by #2740 before we register new version?
=> Fix some docstrings

src/BoundaryConditions/field_boundary_conditions.jl
=> Only `BoundaryCondition`s as default_boundary_conditions

Manifest.toml, docs/src/model_setup/buoyancy_and_equation_of_state.md
this is a follow up from #2777
=> Bump SeawaterPolynomials to v0.3.0

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl, test/test_matrix_poisson_solver.jl
=> Speed up matrix Poisson solver test + minor code cleanup

src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
=> Fixing a small bug in VerticallyImplicitTimeDiscretization vertical momentum fluxes

docs/src/index.md
Just adding three papers to the list of papers using Oceananigans 🎉
=> Add three papers using Oceananigans to list

.buildkite/pipeline.yml, src/Coriolis/hydrostatic_spherical_coriolis.jl
=> Avoid type instability in HydrostaticSphericalCoriolis

.buildkite/pipeline.yml, test/data_dependencies.jl, test/dependencies_for_runtests.jl, test/regression_tests/shallow_water_bickley_jet_regression.jl
=> Brings back ShallowWater regression test

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
Removes formatting irregularity
=> Better momentum advection message

src/Models/ShallowWaterModels/shallow_water_model.jl
Creating different parameter types for clock and gravitational acceleration.
closes https://github.com/CliMA/Oceananigans.jl/issues/2954
=> Added another parameter for gravitational acceleration

examples/ocean_wind_mixing_and_convection.jl
=> Changes "heating" to "cooling" in ocean wind mixing and convection example comment

Project.toml, src/Coriolis/hydrostatic_spherical_coriolis.jl
=> Fix bug in hydrostatic spherical Coriolis

docs/src/model_setup/forcing_functions.md
Change u⃗ -> 𝐮
See https://clima.github.io/OceananigansDocumentation/stable/model_setup/forcing_functions/#AdvectiveForcing
=> Fix docs rendering in Model setup/Forcing

.buildkite/pipeline.yml
I was under the impression that it was brought back long ago...
=> Brings back SWE regression

src/BoundaryConditions/continuous_boundary_function.jl
=> Use grids' native coordinates in continuous BCs 

src/OutputWriters/netcdf_output_writer.jl
=> Fix `default_dimension_attributes` in NetCDFwriter to work with IBG

src/BoundaryConditions/continuous_boundary_function.jl
Follows the post-merge discussion in https://github.com/CliMA/Oceananigans.jl/pull/3074
=> Reduce memory fetch for ContinuousBoundaryFunction BCs

Project.toml, src/BuoyancyModels/BuoyancyModels.jl, src/BuoyancyModels/buoyancy_field.jl, src/BuoyancyModels/buoyancy_tracer.jl, src/BuoyancyModels/g_dot_b.jl, src/BuoyancyModels/linear_equation_of_state.jl, src/BuoyancyModels/no_buoyancy.jl, src/BuoyancyModels/seawater_buoyancy.jl, src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl, src/Models/NonhydrostaticModels/update_hydrostatic_pressure.jl, src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
Buoyancy wasn't being reconstructed at the velocity locations.
Closes #3036
=> Fix bug in buoyancy implementation

Manifest.toml, docs/Manifest.toml
amongst other updates it also bumps CUDA 4.1.2->4.2.0 and KA 0.9.1->0.9.4
=> Updates dependencies

src/TurbulenceClosures/implicit_explicit_time_discretization.jl, src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl, src/TurbulenceClosures/turbulence_closure_utils.jl
I noticed it was a bit convoluted. I refactored the viscosity computation to hopefully be a bit more readable and understandable.
=> Simplify implementation of SmagorinskyLilly + some other closure doc fixes

docs/make.jl
See below for a MWE.
```Julia
$ julia --project=docs
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.9.0 (2023-05-07)
_/ |\__'_|_|_|\__'_|  |
|__/                   |
julia> using Glob
julia> glob("src/*.jl")
6-element Vector{String}:
"src/Architectures.jl"
"src/Biogeochemistry.jl"
"src/Logger.jl"
"src/Oceananigans.jl"
"src/StokesDrift.jl"
"src/Units.jl"
julia> glob("src/**/*.jl")
213-element Vector{String}:
"src/AbstractOperations/AbstractOperations.jl"
"src/AbstractOperations/at.jl"
"src/AbstractOperations/binary_operations.jl"
"src/AbstractOperations/broadcasting_abstract_operations.jl"
"src/AbstractOperations/computed_field.jl" …
```
=> Ensure that all `.jld2`/`.nc` files are deleted before docs deployment

docs/Manifest.toml, docs/Project.toml, docs/make.jl
=> Find output files recursively after a doc build

docs/make.jl
=> More doc built optimizations -- run computationally expensive examples first

src/OutputWriters/checkpointer.jl, src/Simulations/run.jl
`run!` does not need `Glob` + fix the docstring of `checkpointer`.
=> Minor cleanup

Project.toml, src/Utils/schedules.jl
=> (0.84.1) Fixes string generator for `summary(::SpecifiedTimes)`

examples/shallow_water_Bickley_jet.jl
=> Make shallow water Bickley jet less expensive

src/Advection/Advection.jl, src/Advection/reconstruction_coefficients.jl, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl, src/ImmersedBoundaries/immersed_grid_metrics.jl
=> Rename `return_metrics` -> `coordinates`

src/Grids/rectilinear_grid.jl
=> Fix docstring for `RectilinearGrid` grid metrics

src/BoundaryConditions/boundary_condition.jl
Closes #3286 .
@simone-silvestri wouldn't this have affected your stuff with `FieldTimeSeries`? Confused about that.
=> Fix bug in `adapt_structure` for `Field` and `OffsetArray` boundary conditions

src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
Just something that was hard to read
=> Minor formatting fix

src/Grids/orthogonal_spherical_shell_grid.jl
Issue that was pointed out from deliberations in #3302. Thanks @siddharthabishnu.
=> Add `Lz` property for `OrthogonalSphericalShellGrid`

src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
thanks @simone-silvestri 
resolves some confusion that was brought up in https://github.com/CliMA/Oceananigans.jl/pull/3302
=> Add more clarification in a comment

src/Operators/README.md
=> Fix typo in `Face` -> `Center` interpolation explanation in `Operators/README.md`

src/BuoyancyModels/seawater_buoyancy.jl
Noticed while working on #3329
=> Fix docstring for `SeawaterBuoyancy`

Project.toml
Captures the new Enzyme extension.
=> Bump to 0.89.3

.buildkite/pipeline.yml, test/runtests.jl
=> Move Enzyme extension tests to dedicated test group

test/data_dependencies.jl
=> Update regression test data

Project.toml
=> (0.90.1) Bump to 0.90.1 to fix docs issue

src/Forcings/relaxation.jl
Added some methods to allow relaxation forcing to work again.
=> Updates `Relaxation` to work with grids with `Flat` dimensions

README.md
=> Add link to arXiv for scalings in README

src/Models/Models.jl, src/Models/ShallowWaterModels/shallow_water_model.jl, src/MultiRegion/multi_region_models.jl, src/MultiRegion/multi_region_reductions.jl, src/Utils/multi_region_transformation.jl, src/Utils/tuple_utils.jl
=> Fix docs for `@apply_regionally`

examples/horizontal_convection.jl, examples/shallow_water_Bickley_jet.jl, examples/tilted_bottom_boundary_layer.jl, src/BuoyancyModels/buoyancy.jl, src/Utils/prettytime.jl, validation/mesoscale_turbulence/eady_turbulence.jl
This PR fixes a few latex rendering related issues in the tilted BBL and HC example.
Let's make sure we resolve any issues related with #3412 here before merging.
=> Few fixes in few examples

Manifest.toml, docs/Manifest.toml, docs/Project.toml, docs/oceananigans.bib, docs/src/model_setup/grids.md, examples/baroclinic_adjustment.jl, examples/convecting_plankton.jl, examples/horizontal_convection.jl, examples/internal_wave.jl, examples/kelvin_helmholtz_instability.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/shallow_water_Bickley_jet.jl, examples/tilted_bottom_boundary_layer.jl, examples/two_dimensional_turbulence.jl, src/AbstractOperations/conditional_operations.jl
There is a breaking change in CairoMakie v0.10 -> v0.11
`Figure(resolution=(..., ...))` -> `Figure(size=(..., ...))`
=> Use CairoMakie v0.11 for example/docs

Project.toml, src/StokesDrifts.jl
(Btw I came across this trying to pass parameters that aren't just a named tuple of numbers.)
=> Add missing `adapt_structure` for stokes drift

Project.toml, test/test_field.jl
=> (0.90.6) Bump

examples/kelvin_helmholtz_instability.jl
=> Friendlier KH example for GPU

examples/two_dimensional_turbulence.jl
=> Use adaptive timestep in two-dimensional turbulence example

Project.toml
=> (0.90.13) Bump version

Project.toml, src/Fields/interpolate.jl
=> Fix `interpolator` for left side of periodic domain

Project.toml, src/AbstractOperations/constant_field_abstract_operations.jl, test/test_abstract_operations.jl
=> Extend operations for two `ZeroField`s

.buildkite/distributed/pipeline.yml
🤖 Beep boop. I am GabrieleBOT. 🤖 Please, check the [release notes](https://github.com/CliMA/ClimaModules/blob/main/NEWS.md) before merging this PR. Modifications might be required.
=> Update climacommon to 2024_04_30

src/ImmersedBoundaries/ImmersedBoundaries.jl
I basically just added `PartialCellBottom` to the export list on `ImmersedBoundaries`
=> Add PartialCellBottom to the export list on ImmersedBoundaries

docs/src/model_setup/callbacks.md
=> Fix typo in callbacks example

Project.toml
=> (0.91.3) Bump

docs/src/quick_start.md, src/AbstractOperations/conditional_operations.jl
Makes the code a little cleaner. Plus change the aspect ratio to 1.
=> Leverage Makie extension in quick start

docs/src/grids.md
Little improvement for the grid tutorial.
=> Use the word "grid" in the grid tutorial

Project.toml, docs/make.jl
Captures the masking of immersed cells for visualization in #3725.
We can use this in https://github.com/CliMA/ClimaOcean.jl/pull/156
=> Bump patch release

Project.toml, docs/src/model_setup/output_writers.md, src/OutputReaders/field_time_series_indexing.jl, src/OutputWriters/windowed_time_average.jl, test/test_output_readers.jl
=> Bugfix for #3731

src/ImmersedBoundaries/ImmersedBoundaries.jl
=> Add node_names and others to ImmersedBoundaryGrid

src/OutputWriters/output_writer_utils.jl, test/test_jld2_output_writer.jl
=> Fix `auto_extension` for short filenames

src/ImmersedBoundaries/ImmersedBoundaries.jl
Resolves #3771
Not sure where to add tests for this though. Do we need a `test_immersed_grids.jl`?
=> Add 3-location `*nodes` functions for `ImmersedBoundaryGrid`

src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Surprised it hung on this long
=> Remove vestigial `immersed_boundary` from `NonhydrostaticModel`

src/Fields/background_fields.jl, test/test_time_stepping.jl
See https://github.com/CliMA/Oceananigans.jl/pull/3813
=> Add method to permit creating `BackgroundField`s out of `Number`s directly

src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl, test/test_turbulence_closures.jl, validation/vertical_mixing_closures/tupled_vertical_diffusion.jl
Resolves #3804
@hengdiliang let me know if this solves your issue
=> Bring back support for closure tuples with CATKE

src/Advection/immersed_advective_fluxes.jl, src/Advection/tracer_advection_operators.jl
Leftover from #3847.
closes #3851
=> Resolve precompilation of `_advective_fluxes`

Project.toml
Hope this is allowed but was just hoping to tag a new version since it's been a few weeks since v0.92.0 and there have been a good number of bug fixes merged since then.
=> (0.92.1) Tag v0.92.1

src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
https://github.com/CliMA/Oceananigans.jl/pull/3646#issuecomment-2433267716 @glwagner implementing the fix suggested by Greg
=> Correct accessing velocities from the background field

docs/src/index.md
=> Add papers using Oceananigans

Project.toml, ext/OceananigansMakieExt.jl, src/Advection/vector_invariant_advection.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, test/test_hydrostatic_free_surface_models.jl
Closes #3863 (+ fixes FluxFormAdvection docstring)
Closes #3865
=> Add more advection scheme tests; fix order adapting with tracer-specific schemes; fix WENOVectorInvariant

Project.toml, src/Grids/latitude_longitude_grid.jl, test/test_grids.jl
=> Fix bug calling domain for LatitudeLongitudeGrid

docs/src/numerical_implementation/boundary_conditions.md
=> Fix equation rendering in `boundary_conditions.md`

test/test_turbulence_closures.jl
=> Actually test instantiation on GPU and also skip LagrangianAveragedDynamicSmagorinsky test

src/ImmersedBoundaries/immersed_grid_metrics.jl
=> Dont import Grids.coordinates

Project.toml, src/Fields/set!.jl, src/OutputWriters/checkpointer.jl, src/OutputWriters/output_writer_utils.jl, src/Simulations/run.jl, test/test_checkpointer.jl
This will allow us to extend the interface for special `Simulation`s that require special checkpointing procedures.
=> Generalized Checkpointing plus interface for `set!(::Simulation, pickup)`

Project.toml, src/ImmersedBoundaries/immersed_boundary_nodes.jl, test/test_grids.jl
=> (0.95.5) Bugfix in immersed phi-node

ext/OceananigansMakieExt.jl
This PR allows the automatic finding of the axis labels for immersed boundaries and for Observables of Fields.
=> Minor enhancement in OceananigansMakieExt

ext/OceananigansMakieExt.jl
=> Makie extension: tweaks the xticks for domains that wraps around the globe

validation/z_star_coordinate/lock_release.jl
I tried playing around with it and ended up finding a small typo (leading to a bug) that this PR fixes.
=> Fix bug in validation of `MutableVerticalDiscretization()`

src/OutputWriters/checkpointer.jl
=> Add a fallback `set_timestepper!` 

src/Oceananigans.jl
following the discussion in #4053
=> Some changes to `supported_float_types`

.buildkite/pipeline.yml
=> Use 1.10.8 in tests

Project.toml
=> (0.95.8) Bump to 0.95.8

test/test_jld2_output_writer.jl, test/test_netcdf_output_writer.jl
Going over this PR again today I noticed that there were several comments that were unresolved about wrong indentations. This PR resolves them (and a few more as well).
=> Correct indentation in two test files

validation/mesoscale_turbulence/coarse_baroclinic_adjustment.jl, validation/mesoscale_turbulence/immersed_coarse_baroclinic_adjustment.jl
=> Fix Corsican bug in validation test

src/BoundaryConditions/fill_halo_regions_open.jl
Fixes a typo of no importance, but a typo nonetheless. (Also it's been bugging me!)
=> Fix small typo

examples/horizontal_convection.jl
=> Fix Prandtl definition

src/OutputWriters/jld2_output_writer.jl, src/OutputWriters/netcdf_output_writer.jl, test/test_jld2_output_writer.jl, test/test_netcdf_output_writer.jl
=> Change default output type to Float32

README.md
seems they stopped working?
(https://julialang.slack.com/archives/C6A044SQH/p1739218618413509)
=> Drop the downloads stats badges

src/ImmersedBoundaries/immersed_boundary_condition.jl
Seems like this is warranted now.
=> Remove warning for ImmersedBoundaryCondition

src/Utils/schedules.jl
=> Allow schedules to use different float types

Project.toml
We never registered 0.95.13 so might as well bump down to that here.
=> Bump down to 0.95.13

Project.toml
=> Bump to 0.95.14

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/unary_operations.jl, test/test_computed_field.jl
=> Add more UnaryOperations with @unary

Project.toml, src/Solvers/batched_tridiagonal_solver.jl
=> Remove if-statement from tridiagonal solver sweep

src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_vertical_diffusivity.jl
=> Clean up diffusivity fields for CATKE and TKEDissipation

Project.toml
=> (0.95.22) bump minor version

src/Operators/interpolation_operators.jl
Thanks to @luraess for identifying this
=> Fix bug in active-weighted interpolation

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl, src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl, src/Models/ShallowWaterModels/shallow_water_model.jl, src/TurbulenceClosures/TurbulenceClosures.jl, src/TurbulenceClosures/diffusivity_fields.jl, src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/smagorinsky.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_vertical_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl, src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
Plus correctly determine type of CATKE's `previous_compute_time`.
=> Change DiffusivityFields to build_diffusivity_fields and add clock arg

src/Advection/centered_reconstruction.jl
=> Use default FloatType in Centered advection

Project.toml
to capute the tripolar grid PR #3913
=> (0.95.25) bump minor version

Project.toml, ext/OceananigansReactantExt/OceananigansReactantExt.jl, ext/OceananigansReactantExt/TimeSteppers.jl, ext/OceananigansReactantExt/TurbulenceClosures.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl
=> Modify CATKE to work with Reactant when using fixed time step size

ext/OceananigansReactantExt/OceananigansReactantExt.jl
=> Use correct eltype on abstractarray override

src/Fields/field.jl
@avik-pal am I doing this right?
=> Define parent type correctly?

src/TimeSteppers/clock.jl
... to make Reactant happy, perhaps.
ref: https://github.com/PRONTOLab/GB-25/pull/68
=> Capture `Clock.stage` with a type parameter

.buildkite/pipeline.yml, test/reactant_test_utils.jl, test/runtests.jl, test/test_reactant.jl, test/test_reactant_latitude_longitude_grid.jl
The GPU Reactant tests were reaching 2h which is a bit long.
=> Add a second Reactant test group

docs/src/index.md
cc @DJmath1729, @CallumJShakespeare
=> Add Johnston et al. 2025

src/Grids/latitude_longitude_grid.jl
=> Try to make LatitudeLongitudeGrid traceable

src/Simulations/simulation.jl
Needed to replace Float64 with TracedRNumber{Float64} for example.
=> Generalize Simulation struct

src/TimeSteppers/runge_kutta_3.jl
=> Removes warning from implicit-explicit RK3

src/Simulations/run.jl
=> Increment run_wall_time during time_step! again

src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/step_split_explicit_free_surface.jl
this PR does not change anything in oceananigans, but might solve an issue when using Oceananigans with Reactant, see https://github.com/EnzymeAD/Reactant.jl/issues/1154 and https://github.com/EnzymeAD/Enzyme-JAX/issues/681
=> Correcting split explicit barotropic velocities 

src/ImmersedBoundaries/immersed_reductions.jl
=> Respect user condition for `ConditionalOperation` of reduced fields

.buildkite/pipeline.yml, Project.toml, docs/src/grids.md, ext/OceananigansAMDGPUExt.jl, ext/OceananigansMetalExt.jl, ext/OceananigansOneAPIExt.jl, test/runtests.jl, test/test_amdgpu.jl, test/test_init.jl, test/test_oneapi.jl
Similar to #4376, tested this morning by @michel2323 on Aurora.
The tests passed.
Should be merged after #4376.
=> Add extensions for AMDGPU.jl and oneAPI.jl

.buildkite/pipeline.yml
There's still a lot of work to do but this is a start since we don't have separate CPU and GPU pipelines anymore.
=> Clean up buildkite pipeline slightly

src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_vertical_diffusivity.jl
Hit this when doing gradient on your test case
=> Fix adapt for TKEDissipationDiffusivityFields

src/TurbulenceClosures/turbulence_closure_utils.jl
Fixes the issue discussed on https://github.com/CliMA/Oceananigans.jl/discussions/4436
=> Ensure user diffusivity NamedTuple have correct ordering

docs/src/index.md
cc @ngrisouard, @erin-atkinson
=> Add Atkinson et al 2024 in papers list

docs/src/index.md
=> Add Bisits et al. 2025

src/Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl
=> Fill halo regions before interpolating rotated velocities

src/Utils/kernel_launching.jl
=> Constructor for 1-dimensional `KernelParameters`

src/Solvers/conjugate_gradient_poisson_solver.jl
Not sure if this impacts anything...
=> Fix small typo in `conjugate_gradient_poisson_solver.jl`

src/Models/NonhydrostaticModels/solve_for_pressure.jl, src/Solvers/batched_tridiagonal_solver.jl, src/Solvers/fourier_tridiagonal_poisson_solver.jl, src/Solvers/plan_transforms.jl
Resolves #4580. Thanks @xkykai for finding this.
=> Fix transform planning for uniform grids used by FourierTridiagonalPoissonSolver

src/Utils/kernel_launching.jl, src/Utils/multi_region_transformation.jl, src/Utils/ordered_dict_show.jl, src/Utils/output_writer_diagnostic_utils.jl
So I tried to not change any of the logic but made the code a little more idiomatic. For the ordered dict show function, the code contains more lines now but is more readable in my opinion.
This shouldn't create merge conflits.
=> Small code refactorings in Utils

src/TurbulenceClosures/TurbulenceClosures.jl, src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/lilly_coefficient.jl, src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/smagorinsky.jl, src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/4630#issuecomment-3024509112
=> Change `closure_constant()` to `closure_coefficient()`

src/AbstractOperations/metric_field_reductions.jl
=> Small improvement in `Average` constructor

docs/make.jl, docs/src/appendix/library.md, ext/OceananigansNCDatasetsExt.jl
=> Add NetCDFWriter docstring in Docs/Appendix/Library

src/DistributedComputations/distributed_fields.jl
It might be a synchronization issue. Let's try like this
=> Fix for distributed unit tests

src/ImmersedBoundaries/conditional_differences.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/4684
Here the changes now expose `ibg` to active cells (which includes partial cells), and then using `ᵃ`-type difference operators for the case then the cells are not at the immersed boundaries.
Applying this fix now to the MWE in https://github.com/CliMA/Oceananigans.jl/issues/4684 we get 
which is the expected behavior.
Also note that this fix addresses the MWE in https://github.com/CliMA/Oceananigans.jl/issues/4634 for the flat bottom case where there is a row of flat bottomed-partial cells, but does not fully solve the problem as divergence issues persists with other nontrivial bottom topography such as a linear slope.
@glwagner @simone-silvestri
=> Make nested functions in conditional differences immersed metric-aware

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
=> Informative error when using LagrangianParticles on Distributed archs

docs/src/index.md
Paper published last month :), updating reference in docs
=> Update Atkinson et al. 2025

src/Models/Models.jl, src/Simulations/simulation.jl
xref: https://github.com/TUM-PIK-ESM/Terrarium.jl/issues/26#issuecomment-3248713100
=> Add function for resetting the model clock

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl, src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl
=> Change closure_turbulent_velocity to closure_auxiliary_velocity

docs/oceananigans.bib, src/OrthogonalSphericalShellGrids/generate_tripolar_coordinates.jl, src/OrthogonalSphericalShellGrids/tripolar_grid.jl
Adds proper reference/citation in the tripolar grid docstring + few minor enhancements.
=> Clarify few things in tripolar grid docstring
