Manifest.toml, Project.toml, benchmark/benchmarks.jl, examples/deep_convection_2d.jl, examples/horizontal_2d.jl, examples/isotropic_diffusion_2d.jl, examples/rayleigh_taylor_2d.jl, examples/rising_thermal_bubble.jl, src/Oceananigans.jl, src/fields.jl, src/grids.jl, src/operators/ops_regular_cartesian_grid.jl, src/problem.jl, src/spectral_solvers.jl, src/time_steppers.jl
Coded some difference and averaging operators using the `@views` macro. Just a proof of concept right now as the model goes run on a GPU when creating a `Problem` with `arch=:gpu`, but because the kernels are very small (and there are many of them) it's very slow. At least we have something that runs, now we can worry about how to optimize for performance.
Some hacks were used to get this to work but the operators and time stepping is completely shared. The only bit that is different is the quasi-spectral solver as cuFFT does not perform R2R or DCT transforms (`FFTW.REDFT01` and `FFTW.REDFT10`) in particular. A GPU-compatible DCT/IDCT transform was coded that calculates the DCT/IDCT in terms of  `fft!` and `ifft!`.
=> Proof of concept: CPU+GPU shared kernels.

Manifest.toml, examples/deep_convection_3d.jl, src/Oceananigans.jl, src/forcing.jl, src/model.jl, src/time_steppers.jl, test/runtests.jl
Just hacked something together that allows for user-defined forcing functions for the CPU. Have not tested on the GPU yet.
Basically there's a struct `Forcing` that stores the user-defined forcing functions. It will replace the old `ForcingFields` struct. See `examples/deep_convection_3d.jl` for how I switched to using a forcing function for T to enforce a cooling surface heat flux.
A big issue is that the current implementation slows down the time stepping by a factor of 2-3x. So we'll have to figure out why before merging.
The function must have a signature like `F(u, v, w, T, S, Nx, Ny, Nz, Δx, Δy, Δz, i, j, k)` right now so this won't produce a nice solution as we will have to figure out #59 before the function signature can look as nice as `surface_cooling_disk(grid, velocities, …
=> Support for user-defined forcing functions.

src/output_writers.jl
Just merging this so I can work on cleaning up the examples.
Couple of NetCDF related issues I hit:
* [NetCDF.jl](https://github.com/JuliaGeo/NetCDF.jl) seems to be missing some features and isn't really being maintained (See https://github.com/JuliaGeo/NetCDF.jl/issues/62 about saving time values and https://github.com/JuliaGeo/NetCDF.jl/issues/39). Maybe it's worth switching to [NCDatasets.jl](https://github.com/Alexander-Barth/NCDatasets.jl) which takes a more data frames approach to NetCDF and is actively maintained and grew out of bugs that weren't being fixed in NetCDF.jl. Unfortunately we're choosing between two relatively young packages. An alternative would be to use the much more mature [netcdf4-python](http://unidata.github.io/netcdf4-python/) but I'd rather not have to use …
=> read_output function for NetCDF.

.gitignore, docs/src/algorithm.md
Fixes some typos and smoothes out notation (e.g., replaces **u** with **v**).
I'm still puzzled about the `v`--`\nu` issue. I tried using `\upsilon` in place of `v` *but leave* **v** for the 3D vector? Just saying...
Here's how equations look now: 
and here's how they look with the proposed change:
=> Fixes docs again

src/Oceananigans.jl, src/models.jl
Also:
* Print available `CuDevice`s at startup
* Throw `ArgumentError` when attempting to construct a `Model{GPU}` when no CUDA-enabled GPU is detected.
Resolves #82
=> Disable scalar operations on CuArrays

src/Oceananigans.jl, src/diagnostics.jl
A NaN checker diagnostic that aborts the simulation when NaN values are detected.
We could have some shell script that look for this and sends an email or something. Julia could do this too but then we'd add a big dependency for a small diagnostic.
Resolves #38
=> NaN checker diagnostic

src/Oceananigans.jl, src/boundary_conditions.jl, src/time_steppers.jl, test/runtests.jl, test/test_boundary_conditions.jl
In addition, this PR solves #213: boundary conditions in `z` can now be set by writing
```julia
model.boundary_conditions.T.z.top = top_bc
model.boundary_conditions.T.z.bottom = bottom_bc
```
for any field `T`.
In a future PR: physics tests that verify the boundary bc is correct.
=> Adds Value Boundary Condition (BC), improves BC function signatures, GPU BC tests

src/models.jl
This PR fixes a bug in the `Model` constructor that swapped the user-specified viscous and diffusive coefficients when constructing the `ModelConfiguration` object.
=> Bugfix in Model constructor

test/runtests.jl, test/test_poisson_solvers.jl
Until the CPU and GPU Poisson solvers are unified this should give us confidence that the GPU Poisson solver is doing its job.
Found it easier to write the test independently so this supersedes PR #238 
Resolves #200
=> Test that the GPU Poisson solver solution is numerically divergence-free

examples/internal_wave.jl, examples/rising_thermal_bubble_2d.jl, examples/rising_thermal_bubble_3d_gpu.jl, examples/utils.jl
This PR updates the examples to account for the fact that `field.data` returns the full offset array including all halos so you need to use `data(field)` which returns a view into the interior of the field with no halos.
cc @navidcy internal wave example works for me now. Can you try on this branch?
In hindsight, maybe a more sophisticated fields API would avoid issues like this where we're so reliant on the `data(::Field)` function. Maybe things should "just work" for the user.
Resolves #254
=> Fix examples to account for halos

src/Oceananigans.jl, src/fields.jl, src/models.jl
This PR fixes a recent regression in `Model` construction time due to broadcasting over an `OffsetArray{CuArray}` getting converted to a scalar operation. Constructing models should be fast again.
I've also completely disabled scalar operations on CuArrays so this shouldn't happen again.
cc @sandreza 
Actually fixes #82
=> No more scalar operations on CuArrays.

Manifest.toml, examples/rising_thermal_bubble_2d.jl, examples/rising_thermal_bubble_3d_gpu.jl, src/Oceananigans.jl, src/closures/closure_operators.jl, src/closures/turbulence_closures.jl, src/fields.jl, src/operators/ops_regular_cartesian_grid.jl, src/time_steppers.jl, src/utils.jl, test/runtests.jl, test/test_dynamics.jl, test/test_halo_regions.jl, test/test_poisson_solvers.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl
This PR is part 2 of n implementing halo regions (originally PR #167). n = 2 probably.
Here I actually start using the halos and integrate them with the code. This involves filling in the halo regions as needed to enforce the periodic boundary conditions. I also rewrite the operators to use `i-1` and `i+1` instead of `decmod1` and `incmod1`. Hopefully this will speed things up a bit, especially on the GPU.
I will release v0.6 once this is merged.
Resolves #104
=> Halo regions v2: filling halos and faster operations

src/fields.jl
This PR directly indexes the underlying Array or CuArray to avoid the issue that broadcasting over an `OffsetArray{CuArray}` is extremely inefficient.
cc @sandreza
=> Fill halo regions on CuArrays instead of OffsetArrays

src/Oceananigans.jl, src/boundary_conditions.jl, src/fieldsets.jl, src/models.jl, test/runtests.jl, test/test_boundary_conditions.jl, test/test_output_writers.jl, test/test_regression.jl, test/test_time_stepping.jl
Reverts climate-machine/Oceananigans.jl#263 because boundary conditions API broke. Seems that the tests did not catch this maybe?
```
(base) alir_mit_edu@oceananigans-debug:~/Oceananigans.jl$ julia --project newscript.jl 
WARNING: Method definition overdub(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir_mit_edu/.julia/packages/Cassette/xggAf/src/overdub.jl:508 overwritten in module GPUifyLoops at …
```
=> Revert "Be more concrete"

src/Oceananigans.jl, src/diagnostics.jl, src/fields.jl, src/output_writers.jl
cc @sandreza 
Model is back to normal speed. NaN checker and NetCDF output writer were the issues.
```
(base) alir_mit_edu@oceananigans-debug:~/Oceananigans.jl$ julia --project newscript.jl 
WARNING: Method definition overdub(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir_mit_edu/.julia/packages/Cassette/xggAf/src/overdub.jl:508 overwritten in module GPUifyLoops at /home/alir_mit_edu/.julia/packages/Cassette/xggAf/src/overdub.jl:508.
WARNING: Method …
```
=> No more scalar ops in NaN checker and NetCDF output writer

docs/src/algorithm.md
This PR (i) fixes typos in eqs.(34), (37), and (42).
Also, it changes `v` to `υ` which (in the particular font used in the docs) it renders much better and does not lead to confusion with `\nu`.
Regarding factors of `1/ρ0`: I added them in eqs. (1)-(2) to be consistent with eqs. (7)-(8).
But still the issue #222 remains: eq. (13) can't be true if pressure has units of Pa.
=> Polishing docs

.appveyor.yml
This should speed up Appveyor builds which currently take forever.
Also not sure how much we get out of testing x86/32-bit Windows...
Helps with #89
=> Only run Appveyor builds on x64.

src/Oceananigans.jl, src/boundary_conditions.jl, src/time_steppers.jl
This PR gets rid of default and non-default boundary conditions. Default boundary conditions are now explicitly `Periodic` in x,y and `FreeSlip` in z.
This will make implementing multiple wall-bounded dimensions easier/cleaner.
=> Explicit default boundary conditions

src/time_step_utils.jl
Copy pasting from @glwagner's fork.
Adaptive time stepping with a `TimeStepWizard` that computes time steps for you.
I just need to modify `time_step!` with a flag like `first_step_Euler=true` to take forward Euler steps at first iteration and when changing the time step, but with the ability to turn it off for tests where we actually don't want to do this. 
I'll add some more docstrings and a couple of tests.
cc @sandreza 
Resolves #189
=> Adaptive time stepping through wizardry

Manifest.toml, src/diagnostics.jl, src/time_steppers.jl, test/test_poisson_solvers.jl
This PR integrates Tim's changes from the GPU hackathon. By using dynamic launch configurations and splitting up the interior source term calculation kernel (+ https://github.com/JuliaGPU/CUDAnative.jl/pull/417) we get a pretty sweet ~25% overall speedup (so the most expensive kernel which was a bottleneck is sped up by ~40%).
Needs https://github.com/vchuravy/GPUifyLoops.jl/pull/90 to work for now.
cc @maleadt Sorry it took so long for me to merge these improvements.
Actually resolves #64 
```
──────────────────────────────────────────────────────────────────────────────────────
Oceananigans.jl static ocean bench...        Time                   Allocations      
──────────────────────   ───────────────────────
Tot / % measured:                409s / 28.8%           15.0GiB / 0.50% …
```
=> Faster model with dynamic launch configuration by @maleadt

src/Oceananigans.jl, src/closures/anisotropic_minimum_dissipation.jl, src/closures/closure_operators.jl, src/closures/constant_diffusivity_closures.jl, src/closures/constant_smagorinsky.jl, src/closures/turbulence_closures.jl, src/equation_of_state.jl, src/time_steppers.jl, test/test_turbulence_closures.jl
This PR starts the processes of integrating LES functionality from glwagner/pass-tests into Oceananigans master. It is very much WIP at the moment.
=> [WIP] Integrate LES functionality

Dockerfile
Simple Dockerfile to build a Docker image with Oceananigans installed, precompiled, and with dependencies built.
Should be useful for debugging and maybe speeding up CI. Image can be built then just downloaded by CI server, but usually testing is done before Docker image is built...
We also have a Dockerhub repository where images will be published: https://cloud.docker.com/repository/docker/aliramadhan/oceananigans
We can look into automated builds: https://docs.docker.com/docker-hub/builds/
For GPU-accelerated container we can look into: https://github.com/NVIDIA/nvidia-docker
cc @christophernhill we're finally in the 21st century!
Resolves #151
=> Dockerfile for Oceananigans

examples/deepening_mixed_layer.jl, examples/utils.jl, sandbox/eddying_channel.jl, src/Oceananigans.jl, src/fields.jl, src/models.jl, src/operators/ops_regular_cartesian_grid.jl, src/time_steppers.jl, src/utils.jl, test/runtests.jl, test/test_examples.jl, test/test_fields.jl, test/test_models.jl
Just combining my commits from PRs #337 and #341.
Idea is to make life more comfortable by getting `set!` to work out of the box for CPU and GPU fields, and for setting them with functions or arrays.
The functions should be evaluated on the CPU as not every function is available through CUDAnative (notably `rand` and `randn` are missing).
Will switch to using `copyto!`.
=> Robust setting of fields

src/Oceananigans.jl, src/boundary_conditions.jl
Somehow I always find myself saying Dirchlet and Neumann in real-life so I'd like to use the names in the code.
Wish Value/Gradient was the accepted nomenclature...
=> Dirchlet and Neumann aliases for Value and Gradient boundary conditions

Manifest.toml, Project.toml, examples/deepening_mixed_layer.jl, src/Oceananigans.jl, src/models.jl
=> Update CUDA packages to get rid of CUDA errors on CPU and use CUDAapi.has_cuda()

src/halo_regions.jl, src/time_steppers.jl
This fixes a bug in which halo regions were not filled for subgrid-scale LES diffusivities. 
To do this robustly for various diffusivity structures with different nesting hierarchies, a recursive halo region filling functionality is implemented that dispatches on `bcs::NamedTuple{(:x, :y:, :z)}`, corresponding to a `FieldBoundaryCondition`. Thus, when `fill_halo_regions!(fields, bcs, grid)` is called with matching tuples for *both* `fields` and `bcs`, a simultaneous loop is done over the members of the two tuples. However, when `fill_halo_regions!(fields, bcs, grid)` is called and `bcs` is a `FieldBoundaryCondition`, a loop is performed over the members of `fields` *only*, and `bcs` is reused for every member of `fields`. Thus halo regions for fields embedded in nested structures (like …
=> Fill halo regions for diffusivity

src/diagnostics.jl, src/halo_regions.jl, src/output_writers.jl, src/planetary_constants.jl, src/time_steppers.jl, src/utils.jl
This PR improves the `HorizontalAverage` utility to allow users to specify a return type, and refactors the code a bit to dispatch on the length of `fields`. This will be useful in the future when more sophisticated functions for computing horizontal averages (which, for example, interpolate fields to a common location) are implemented.
It also refactors the time to write function and eliminates some boilerplate.
=> Improve HorizontalAverage and time to write function

Manifest.toml, Project.toml, examples/deepening_mixed_layer.jl, src/Oceananigans.jl, src/models.jl, test/test_forcings.jl
The main point of upgrading is to get rid of CUDA errors on the CPU and use `CUDAapi.has_cuda()` which replaces the `HAVE_CUDA` variable we've been using.
This was originally in PR https://github.com/climate-machine/Oceananigans.jl/pull/378 (this PR is mostly cherry picked commits) but when it was merged @glwagner reported issues with forcing functions on the GPU.
So now I've added a test that makes sure that forcing functions don't crash when used in a CPU or GPU model (one with and one without `const`).
=> Update CUDA packages (attempt 2)

benchmark/benchmark_forcing_functions.jl, src/boundary_conditions.jl, src/models.jl, src/time_steppers.jl, test/test_forcings.jl, test/test_regression.jl
This PR adds a field `parameters` to `Model`. The field is intended to be utilized by users for setting parameters in user-defined forcing functions and boundary conditions functions. 
The forcing functions now have the function signature
```julia
F.u(i, j, k, grid, time, U, C, params)
```
whereas boundary conditions have the function signature
```julia
boundary_condition(i, j, grid, time, iteration, U, C, params)
```
This PR resolves #394 and #390.
=> Parameters field in Model for user convenience

src/boundary_conditions.jl
This PR implements a minor performance optimization that changes the 'default' boundary condition type to `BoundaryCondition{Flux, Nothing}`.
Using this type elides the adding of 0's in the case of zero flux boundary conditions.
The functionality for eliding computation in this case was already implemented; however it was not used by default. 
This may address #397, but @ali-ramadhan we need to benchmark.
=> Use {Flux, Nothing} for default boundary condition type rather than {Flux, 0}

src/models.jl, test/test_models.jl
Add a warning if trying to create a GPU model with a grid where `Nx` or `Ny` are not a multiple of 16.
Some GPU kernels still use the hard-coded `Tx = Ty = 16` for calculating thread-block layouts. See PR https://github.com/climate-machine/Oceananigans.jl/pull/308 for why.
Even if we were to get rid of the hard-coded `Tx, Ty` there will always be weird grid sizes like 17x33x47 that you can run no problem on a CPU, but might not be able to create a perfect thread-block layout for without having extra threads that do nothing, but extra threads can do bad stuff like apply a boundary condition twice if we're not careful.
Apologies to @beta-effect who was burned by this in the past.
=> Add warning if GPU model grid Nx, Ny are not multiple of 16

README.md, examples/deepening_mixed_layer.jl, examples/internal_wave.jl, src/Oceananigans.jl, src/diagnostics.jl, src/grids.jl, src/models.jl, src/output_writers.jl, src/time_steppers.jl, test/test_boundary_conditions.jl, test/test_diagnostics.jl, test/test_dynamics.jl, test/test_forcings.jl, test/test_models.jl, test/test_output_writers.jl, test/test_regression.jl, test/test_time_stepping.jl
This PR simplifies and generalizes the model constructor, which is a major change to the API. Except for `initialize_tracers` and `float_type`, all of the keyword arguments to `Model` now correspond semantically to the fields of model. In addition to clarifying the arguments of the model constructor, this will make checkpointing easier. 
In addition, model fields that contain arrays, and thus are involved with large amounts of memory allocation, can be initialized through the model constructor. This should enable upgrades to the checkpointer that make it possible to checkpoint very large models that fill GPU memory.
Finally, we add three new convenience constructors that retain the legacy behavior of model, and provide convenient ways to initialize particular models: `BasicModel`, …
=> Simplification and generalization of Model constructors

src/Oceananigans.jl, src/boundary_conditions.jl, src/halo_regions.jl, src/models.jl, src/poisson_solvers.jl, src/time_steppers.jl, test/test_boundary_conditions.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl
This PR refactors the boundary conditions container to reflect the fact that there are three boundary conditions: a tuple of `FieldBoundaryConditions` for the `solution`, a tuple of `FieldBoundaryConditions` for the `tendencies`, and a single `FieldBoundaryConditions` for the `pressures` (which is also used to set boundary conditions on `diffusivities`.
To reflect these facts, this model creates a new tuple called `SolutionBoundaryConditions` to hold the boundary conditions for solution. `ModelBoundaryConditions` then becomes a named tuple with fields `solution`, `tendency`, and `pressure`.
The model constructor may be passed either a `SolutionBoundaryConditions` (preserving existing behavior), or a `ModelBoundaryConditions` (convenient for checkpointing). Ditto for `PoissonBCs` --- …
=> Refactor boundary conditions container

benchmark/benchmark_utils.jl, examples/internal_wave.jl, src/Oceananigans.jl, src/boundary_conditions.jl, src/diagnostics.jl, src/equation_of_state.jl, src/fields.jl, src/grids.jl, src/halo_regions.jl, src/models.jl, src/output_writers.jl, src/planetary_constants.jl, src/poisson_solvers.jl, src/time_steppers.jl, src/turbulence_closures/TurbulenceClosures.jl, src/turbulence_closures/closure_operators.jl, src/turbulence_closures/rozema_anisotropic_minimum_dissipation.jl, src/turbulence_closures/smagorinsky.jl, src/turbulence_closures/velocity_tracer_gradients.jl, src/turbulence_closures/verstappen_anisotropic_minimum_dissipation.jl, src/utils.jl, test/test_boundary_conditions.jl, test/test_dynamics.jl, test/test_fields.jl, test/test_grids.jl, test/test_regression.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl
Started to write documentation and docstrings but some parts of the code were a little too messy to be documented easily, so I ended up doing some cleanup that seems to deserve its own PR.
I mainly renamed all the abstract types to have the `Abstract` prefix (following the Julia style guide) and simplified `LinearEquationOfState`, `PlanetaryConstants`, and `RegularCartesianGrid` where I removed properties that weren't being used or that were redundant/useless.
Resolves #190 (because the constants in question have been removed)
Resolves #285
=> Pre-documentation cleanup

src/Oceananigans.jl, src/diagnostics.jl, src/models.jl, src/output_writers.jl, src/turbulence_closures/TurbulenceClosures.jl, src/turbulence_closures/rozema_anisotropic_minimum_dissipation.jl, src/turbulence_closures/smagorinsky.jl, src/turbulence_closures/turbulence_closure_diagnostics.jl, src/turbulence_closures/turbulence_closure_utils.jl, src/turbulence_closures/verstappen_anisotropic_minimum_dissipation.jl, src/utils.jl, test/runtests.jl, test/test_diagnostics.jl
This PR adds a new `Diagnostic` type called `Timeseries`, which takes a function or callable object of model (anything that has a method of the form `obj(model)`), and stores the result in `data` vector and the time-of-collection in a `time` vector.
It also adds an object called `CFL` which computes the Courant-Freidrichs-Lewy number. `CFL` associates with a function `timescale`, which is used to provide convenience constructors `AdvectiveCFL` and `DiffusiveCFL`.
We also add an object for computing `maximum(f, field.data.parent)` for `field`s, for an element wise operation `f`.
The PR includes tests and docstrings for this functionality.
=> Timeseries diagnostic and CFL utilities

src/Oceananigans.jl, src/grids.jl, src/models.jl, src/turbulence_closures/TurbulenceClosures.jl, src/turbulence_closures/turbulence_closure_diagnostics.jl
This PR is ready for merger when approved, and tests pass.
=> Simplify AbstractModel, fixes show for RegularCartesianGrid

src/Oceananigans.jl, src/fields.jl, src/grids.jl, src/models.jl, src/utils.jl
This PR refactors the implementation of the Field abstraction. There is now only one type of `Field`,  with the type signature 
```julia
Field{Lx, Ly, Lz, A, G}
```
where `Lx, Ly, Lz` denote the 'locations' of the field within a cell. For example, a `CellField` is now defined via
```julia
const CellField = Field{Cell, Cell, Cell}
```
Let's consider this PR carefully and ensure that it makes sense.
Resolves #298.
=> More general and compact Field implementation

examples/deepening_mixed_layer.jl, test/test_examples.jl
Cherry picked some commits from PR #381 to fix the example test.
One thing that's going to be annoying about testing example scripts is that they evaluate in global scope when including them, so it's going to be easy to get variable name conflicts...
Not sure how to get around this as we agreed not to use functions for examples.
=> Fix example test

src/fields.jl
We used docstrings above the `@hascuda` macro to document the `set!` function for GPUs, but on CPUs `@hascuda` evaluates to `nothing` and Julia thinks we're trying to override the docstring for `nothing`.
```
┌ Warning: Replacing docs for `Core.nothing :: Union{}` in module `Oceananigans`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `Core.nothing :: Union{}` in module `Oceananigans`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `Core.nothing :: Union{}` in module `Oceananigans`
└ @ Base.Docs docs/Docs.jl:223
```
Since the main `set!` function is public and documented, these backend GPU `set!` functions can live with comments instead of docstrings.
These warnings would show up whenever someone imported or ran `using Oceananigans` so they were very public and …
=> Get rid of docs replacement warnings on CPU

CONTRIBUTING.md, README.md
For JOSS we need to have a helpful `CONTRIBUTING.md` file, and I thought it would be good to put one up for Hacktoberfest.
I'm a big fan of MetPy's contributor's guide so I heavily based it on theirs, I don't think I could have done a better job.
MetPy uses a [BSD-3-Clause](https://tldrlegal.com/license/bsd-3-clause-license-(revised)) license so I think this means we'd have to license our `CONTRIBUTING.md` file under BSD-3-Clause? @christophernhill is this an issue?
cc MetPy devs @dopplershift @jrleeman: Your MetPy contributor's guide is really excellent! I hope you don't mind if I borrowed heavily from it.
=> Add contributing section to README and contributor's guide

.gitlab-ci.yml
Until we figure out why v1.3 and DEV jobs time out on GitLab CI we can just allow v1.3 to fail.
v1.3 hasn't been released yet so makes sense to allow failures anyways.
=> Allow v1.3 GPU tests to fail on GitLab CI

.gitlab-ci.yml
Not sure if this will fix the failing coverage job so I've also allows failures on coverage.
Coverage will be reported from v1.2
=> Use coverage job from earlier GitLab CI yaml

Project.toml
Going to release a new version as quite a bit has been merged since v0.11.0, and arbitrary tracers (PR #452) will probably be the focus of v0.12.0.
=> Bump version to 0.11.1

Project.toml
I've added `[compat]` entries in `Project.toml` which we need for automatic package registration: https://github.com/JuliaRegistries/General/pull/4485
Someone please approve/merge.
=> Add compatiblity entries to Project.toml

Project.toml
This is an important tag/release because the model now has `k=1` at the bottom which effects post-processing and plotting scripts.
=> Bump version to 0.13.0

src/grids.jl, test/test_grids.jl
Plus some cleanup of input validation, and a test.
=> Adds halo argument to constructor to `RegularCartesianGrid`

src/Oceananigans.jl, src/boundary_conditions.jl, test/test_boundary_conditions.jl
This PR adds a wrapper for boundary-conditions-as-functions called `BoundaryFunction`.
From the docstring:
```julia
""" 
BoundaryFunction{B, X1, X2}(func)
A wrapper for user-defined boundary condition functions on the
boundary specified by symbol `B` and at location `(X1, X2)`.
Example
=======
julia> using Oceananigans: BoundaryCondition, BoundaryFunction, Flux, Cell
julia> top_tracer_flux = BoundaryFunction{:z, Cell, Cell}((x, y, t) -> cos(2π*x) * cos(t))
(::BoundaryFunction{:z,Cell,Cell,getfield(Main, Symbol("##7#8"))}) (generic function with 1 method)
julia> top_tracer_bc = BoundaryCondition(Flux, top_tracer_flux);
```
=> BoundaryFunction wrapper for simple boundary condition functions

docs/make.jl
Once merged I'll run BFG Repo-Cleaner to remove all the big JLD2 files that got stuck in git history.
Resolves #509
=> Delete leftover JLD2 files after running examples

docs/src/index.md, docs/src/manual/large_eddy_simulation.md, docs/src/manual/physics.md, docs/src/manual/poisson_solvers.md, docs/src/manual/staggered_grid.md, docs/src/manual/time_stepping.md, examples/eady_turbulence.jl
What does *non-linearized around a geostrophic flow* mean (line 64)?
Perhaps better *assumes a geostrophic base flow...*?
=> Fixes a typo in Eady example and in Docs

docs/make.jl, examples/ocean_wind_mixing_and_convection.jl
Maybe not the cleanest solution but this will resolve #509 which has become a rather annoying issue recently.
=> Delete leftover JLD2 files before deploying docs

src/OutputWriters/netcdf_output_writer.jl
Docstring did not match the actual constructor. They do now.
@suyashbire1 Do you think `clobber` should be true or false by default?
Also updated the docstring to make it clear that `outputs` needs to be a `Dict` for now.
Resolves #553
=> Update `NetCDFOutputWriter` docstring and clobber default

test/runtests.jl
=> On CI servers select the GPU with the most memory

src/SurfaceWaves.jl, src/TimeSteppers/kernels.jl
This PR fixes
1. A sign error in the momentum kernels associated with the Stokes drift tendency terms for surface waves and
2. Interpolation (or lack thereof) error in the surface wave pseudovorticity term.
=> Bugfix in SurfaceWaves module

src/coriolis.jl, test/test_coriolis.jl
=> Add default Ω_Earth and R_Earth for FPlane and BetaPlane

test/test_solvers.jl
=> Sometimes if you wait tests fix themselves

src/boundary_conditions.jl, test/regression_tests/ocean_large_eddy_simulation_regression_test.jl, test/regression_tests/rayleigh_benard_regression_test.jl, test/test_boundary_conditions.jl
=> Remove `BoundaryConditions` alias

test/runtests.jl, test/test_abstract_operations.jl, test/test_boundary_conditions.jl, test/test_buoyancy.jl, test/test_coriolis.jl, test/test_diagnostics.jl, test/test_dynamics.jl, test/test_examples.jl, test/test_fields.jl, test/test_forcings.jl, test/test_grids.jl, test/test_halo_regions.jl, test/test_models.jl, test/test_operators.jl, test/test_output_writers.jl, test/test_regression.jl, test/test_solvers.jl, test/test_surface_waves.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl, test/test_verification.jl
Resolves #578 
Updates runtests to use the ModelLogger
Updates tests to use @info instead of println
=> Switch Tests to use the new logger

docs/src/model_setup/boundary_conditions.md, src/BoundaryConditions/BoundaryConditions.jl, src/BoundaryConditions/boundary_condition_types.jl, src/Oceananigans.jl
This PR removes the `Dirchlet` and `Neumann` aliases for boundary condition types.
=> Purge famous people

src/TurbulenceClosures/turbulence_closure_implementations/verstappen_anisotropic_minimum_dissipation.jl, src/TurbulenceClosures/turbulence_closure_utils.jl
This PR differentiates the AMD model constants for eddy viscosity and eddy diffusivity, and permits them to be functions of `x, y, z`. 
For simplicity we will permit just one model constant specification for all tracers. It is possible to permit different constants for different tracers, but 
Also, with this PR the "Verstappen" implementation of AMD is now diverging from the "Rozema" implementation. It may be time to nuke the "Rozema" implementation.
=> Differentiated and variable AMD model constants

README.md, src/Diagnostics/cfl.jl, src/Diagnostics/field_maximum.jl, src/Diagnostics/time_series.jl, src/Fields/set!.jl, src/Forcing/model_forcing.jl, src/Models/Models.jl, src/Models/incompressible_model.jl, src/Models/non_dimensional_model.jl, src/Models/show_models.jl, src/Oceananigans.jl, src/OutputWriters/checkpointer.jl, src/TimeSteppers/adams_bashforth.jl, test/regression_tests/ocean_large_eddy_simulation_regression_test.jl, test/regression_tests/rayleigh_benard_regression_test.jl, test/regression_tests/thermal_bubble_regression_test.jl, test/test_abstract_operations.jl, test/test_boundary_conditions.jl, test/test_diagnostics.jl, test/test_dynamics.jl, test/test_forcings.jl, test/test_models.jl, test/test_output_writers.jl, test/test_regression.jl, test/test_simulations.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl, verification/stratified_couette_flow/stratified_couette_flow.jl
Note: This PR branches off from #621.
Resolves #566 
Resolves #633
=> Rename Model to IncompressibleModel

Project.toml, docs/make.jl, docs/src/library.md, docs/src/model_setup/checkpointing.md, docs/src/model_setup/diagnostics.md, docs/src/model_setup/output_writers.md, src/Fields/Fields.jl, src/Fields/field_tuples.jl, src/Models/incompressible_model.jl, src/Oceananigans.jl, src/OutputWriters/OutputWriters.jl, src/OutputWriters/checkpointer.jl, src/OutputWriters/output_writer_utils.jl, src/TimeSteppers/TimeSteppers.jl, src/TimeSteppers/adams_bashforth.jl, test/test_output_writers.jl
This PR finally upgrades the checkpointer so it can restore large models that take up more than 50% of system memory. It used to create a model then restore the fields which allocates twice as much memory as needed. Now the data needed to restore the fields is passed to the model constructor so no double allocation. Some refactoring had to happen to make this possible.
This PR is also part 2/3 of making boundary conditions a field property.
Should help a lot with #602 and #603.
Resolves #416
Resolves #417
Note: This PR branches off #627.
=> Simplify checkpointer and make it work for large models

.gitlab-ci.yml, .travis.yml, Dockerfile, Manifest.toml, Project.toml, README.md, docs/src/installation_instructions.md, docs/src/using_gpus.md
Would be nice to get this into v0.23.0
Resolves #625
=> Make Julia 1.3 the new minimum required version

src/Models/show_models.jl, src/Simulations.jl, src/Utils/ordered_dict_show.jl
This PR allows simulations to hold parameters, useful if you need to access stuff from the `progress` function (e.g. see https://github.com/thabbott/JULES.jl/pull/63) going with the idea that we'll probably get rid of `model.parameters` in favor of more local parameters.
It also cleans up show functions for models and simulations.
=> Simulation parameters and prettier show methods

src/Simulations.jl
=> Improves getting time step from Simulation type

Project.toml, src/OutputWriters/checkpointer.jl
Fixes #655
`convert_to_arch` was defined in two places.
Will release patch v0.24.1 once merged.
=> Fix method redefinition warnings

src/Fields/field_tuples.jl, src/Models/incompressible_model.jl, src/OutputWriters/checkpointer.jl, src/TimeSteppers/TimeSteppers.jl
This PR consolidates the `tracers` and `tracer_fields` kwargs to `IncompressibleModel`, and the `timestepper` and `timestepper_method` kwargs to `IncompressibleModel`.
Resolves #647.
=> Model constructor cleanup

src/OutputWriters/netcdf_output_writer.jl
Makes more sense as we usually work with °C (probably true for most of oceanography).
=> Change default NetCDF temperature units: K to °C

src/TimeSteppers/adams_bashforth.jl, test/test_time_stepping.jl
This PR fixes an error in the Adams-Bashforth time-stepping algorithm so that tendencies from time-step `n-1` are computed correctly. This PR also computes tendencies after a time-step is complete rather than at the beginning of a time-step.
This change causes the regression tests to fail. We should merge this change and correct the regression tests in a subsequent PR.
=> Store tendencies correctly after time-step

src/BoundaryConditions/BoundaryConditions.jl, src/BoundaryConditions/boundary_function.jl, src/Fields/Fields.jl, src/Fields/boundary_function.jl, src/Fields/field.jl, src/Oceananigans.jl, test/test_boundary_conditions.jl
This PR reorganizes the functionality for `BoundaryFunction` so that it is entirely contained within `src/BoundaryConditions/boundary_function.jl`. This requires defining placeholders for `xnode`, `ynode`, and `znode` in `Oceananigans.jl`.
=> Reorganize boundary function functionality

.gitignore, src/BoundaryConditions/apply_flux_bcs.jl
My fault, must have messed up and forgot to skip `_apply_*_bcs!` for `NotFluxBC` in PR #631. 
Fixes #675 and should fix failing tests on PR #671.
Before:
```
──────────────────────────────────────────────────────────────────────────────────────
Static ocean benchmarks                Time                   Allocations      
──────────────────────   ───────────────────────
Tot / % measured:                24.3s / 2.17%           1.83GiB / 18.1%    
Section                       ncalls     time   %tot     avg     alloc   %tot      avg
──────────────────────────────────────────────────────────────────────────────────────
32× 32× 32  [CPU, Float32]       10    256ms  48.6%  25.6ms    170MiB  50.0%  17.0MiB
32× 32× 32  [CPU, Float64]       10    270ms  51.4%  27.0ms    170MiB  50.0%  17.0MiB …
```
=> Fix memory allocations on CPU

src/TimeSteppers/TimeSteppers.jl, src/TimeSteppers/generic_time_stepping.jl, src/TimeSteppers/time_stepping_kernels.jl, src/TimeSteppers/velocity_and_tracer_tendencies.jl
This PR modifies the time-stepping algorithm so that the tendencies for wall-normal velocity components are calculated on boundaries in `Bounded` directions.
In other words, when `x` is `Bounded`, the algorithm now calculates `Gu` on east boundaries, where `i=Nx+1`. Previously `Gu` was only calculated on west boundaries where `i=1`. The same applies to `y` and `z`.
This change is necessary because, in general, the values of `Gu`, `Gv`, and `Gw` on `x`, `y`, or `z` boundaries are needed to impose predictor velocity and pressure boundary conditions when `x`, `y`, or `z` are `Bounded` --- respectively.
The changes in this PR also motivated a slight refactoring of the way "equations" are specified. There is now a file dedicated to equation / tendency specification, called …
=> Calculate tendencies on boundaries

examples/eady_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, src/BoundaryConditions/BoundaryConditions.jl, src/BoundaryConditions/apply_no_penetration_bcs.jl, src/BoundaryConditions/boundary_function.jl, src/BoundaryConditions/fill_halo_regions.jl, src/BoundaryConditions/parameterized_boundary_condition.jl, src/Forcing/Forcing.jl, src/Forcing/model_forcing.jl, src/Forcing/parameterized_forcing.jl, src/Forcing/simple_forcing.jl, src/Models/Models.jl, src/Models/clock.jl, src/Models/incompressible_model.jl, src/TimeSteppers/TimeSteppers.jl, src/TimeSteppers/generic_time_stepping.jl, src/TimeSteppers/time_stepping_kernels.jl, src/TimeSteppers/velocity_and_tracer_tendencies.jl, test/regression_tests/rayleigh_benard_regression_test.jl, test/test_forcings.jl, test/test_solvers.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl, verification/stratified_couette_flow/stratified_couette_flow.jl
This PR simplifies the function signatures for boundary condition functions and forcing functions. 
It also nukes the `model.parameters` field in favor of more local "parameters" functionality, and adds `ParameterizedForcing` and `ParameterizedBoundaryCondition` convenience types and functions.
The new forcing function signature is
```julia
F(i, j, k, grid, clock, state)
```
while the new boundary condition function signature is
```julia
bc(i, j, grid, clock, state)
```
where `i, j` are indices along the boundary.
`state` is a `NamedTuple` with fields `:velocities`, `:tracers`, and `:diffusivities`, each corresponding to an `OffsetArray` that references the data associated with each field.
In the future, if we make substantial changes to `model`, the hope is that we can modify/extend …
=> Simpler boundary condition functions and forcing functions

examples/two_dimensional_turbulence.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/Fields/field.jl
This PR refactors the FieldBoundaryConditions constructor to allow a consistent user API for specifying field locations. Field locations are specified with _uninstantiated_ types: in other words, a location is 
```julia
(Face, Cell, Cell)
```
rather than
```julia
(Face(), Cell(), Cell())
```
The latter form was deemed too much `()`. This is open to debate of course. I am slightly worried the former form is non-Julian. But it seems fairly unequivocal that it's easier to read.
I also took the opportunity to clean up field constructors a bit. We now have the concept of _default_ boundary conditions; mostly, this is useful when a user wants to build a field that will never call `fill_halo_regions` and therefore its boundary conditions are irrelevant. I changed the …
=> Consistent API for field locations

src/Fields/field_tuples.jl, test/test_fields.jl
This PR adds a method that short circuits `has_velocities` when passed and empty tuple, which can happen for models with no tracers.
Resolves #700.
=> Fix has_velocities

src/Solvers/triply_periodic_pressure_solver.jl, test/test_pressure_solvers.jl
This PR adapts the analytical pressure solver test to an explicit test for second-order convergence of the pressure solver in all configurations.
The triply periodic solver currently throws an error if we try to construct it, so I'm skipping that test.
=> Test for second-order convergence of pressure solver

src/Fields/field.jl
=> Make generic zeros function work on GPU

Project.toml
A bug was fixed in the `zeros` function that's needed for the computation of HorizontalAverages on the GPU. Because this bug fix is very important, we should bump to 0.27.2.
=> Bump to 0.27.2

src/Grids/grid_utils.jl
Formatting was wrong in REPL. Will include with v0.29.0 (#738).
=> Minor fix in `*nodes` docstrings

Project.toml
Just bumping version 0.29 that adds the TEOS-10 equation of state so LESbrary.jl can depend on it.
=> Bump v0.29.0

examples/ocean_wind_mixing_and_convection.jl, test/test_examples.jl
Also:
* Changes test_examples.jl to spew example file into the build log on error.
* Makes a minor correction to the replace strings for the `ocean_wind_mixing_ and_convection.jl` example.
=> Fixes strange error in ocean wind mixing and convection examples

examples/ocean_convection_with_plankton.jl, src/Forcing/Forcing.jl, src/Forcing/model_forcing.jl, src/Forcing/simple_forcing.jl, test/test_forcings.jl
A 'field-dependent' forcing is a user-specified forcing term that depends on `x, y, z, t, u`, where `u` is the field being forced, and optionally parameters.
=> Allows field-dependent SimpleForcing. Updates plankton growth example.

README.md, docs/src/model_setup/boundary_conditions.md, docs/src/model_setup/checkpointing.md, docs/src/model_setup/diagnostics.md, docs/src/model_setup/forcing_functions.md, docs/src/model_setup/grids.md, docs/src/model_setup/number_type.md, docs/src/model_setup/output_writers.md
Links to documentation probably broke upon changing the org name. Also, the keyword change from `length` to `extent` was apparently not fully propagated through README & doc. Not sure but figured that sending this as PR might be helpful.
=> fix doc links (clima org) and examples (extent keyword)

Project.toml
Just bumping version to 0.30.0 now that you need to use SeawaterPolynomials.jl to access `TEOS10` (a breaking change).
=> Bump v0.30.0

docs/make.jl
In retrospect, this option adds more stuff in the gh-pages branch and it increases the size of the repository's history.
=> Removes push_preview

test/runtests.jl
Should speed up GitLab CI builds. CPU is already well-tested on Travis CI and Appveyor.
=> Only run GPU tests on GPU CI builds

src/Forcing/relaxation.jl, test/test_forcings.jl
This PR permits the syntax
```julia
u_forcing = Relaxation(; rate=1/60, target=0.1)
```
Previously we would have had to write
```julia
u_forcing = Relaxation(; rate=1/60, target=(x, y, z, t) -> 0.1)
```
since `target` was expected to be a function of `x, y, z, t`.
Might help with #789
=> Adds a hook for constant targets in Relaxation

docs/Project.toml, examples/langmuir_turbulence.jl
The Langmuir turbulence example requires JLD2.jl. This PR adds JLD2 in `docs/Project.toml`.
This PR closes #791.
=> Fix Langmuir turbulence example

docs/make.jl
The `GITHUB_REPOSITORY` environment variable is used by GitHub actions. We deploy from Travis so the right environment variable is `TRAVIS_REPO_SLUG`.
=> Fix deploying docs to OceananigansDocumentation

Project.toml
We should merge this after PR #805.
This release fixes a major bug where you couldn't run GPU models so if you're using GPUs you should upgrade to this version.  **Oceananigans.jl now requires Julia 1.4+.**
Major changes:
* Updated the backend to use [KernelAbstractions.jl](https://github.com/JuliaGPU/KernelAbstractions.jl) instead of [GPUifyLoops.jl](https://github.com/vchuravy/GPUifyLoops.jl).
* Updated to using [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl) instead of CuArrays.jl, CUDAnative.jl, and CUDAdrv.jl.
* Updated and slightly expanded the model setup documentation.
* Added a bibliography and citations to the documentation.
* Generalized `ConstantIsotropicDiffusivity` and `ConstantAnisotropicDiffusivity` to accept functions of `x, y, z, t` as well as constants. These types are …
=> Bump v0.31.0

src/Fields/set!.jl, src/Utils/kernel_launching.jl
These things:
```
WARNING: using CUDA.device in module Utils conflicts with an existing identifier.
WARNING: using KernelAbstractions.CPU in module Fields conflicts with an existing identifier.
WARNING: using KernelAbstractions.GPU in module Fields conflicts with an existing identifier.
```
=> Fix existing identifer conflicts

Project.toml
Release notes:
**Everyone should stop using Oceananigans v0.31.0 and upgrade to this version. Oceananigans now requires Julia 1.4 or later.**
This release fixes a major bug concerning a race condition making GPU simulation, especially large models, explode into NaNs in v0.31.0.
It also restores the "Examples" section in the documentation and adds experimental support for higher order advection schemes.
=> Bump v0.32.0

Project.toml
Release notes:
This release adds new features to the `NetCDFOutputWriter` and fixes some bugs.
* The date the file was generated, the Julia version, and the Oceananigans version used are always written as global attributes (metadata) to all NetCDF files.
* Added `with_halos` and `verbose` keyword arguments to `NetCDFOutputWriter`.
* Fixed bug in writing grid coordinates to NetCDF (they were previously offset).
* Fixed bug in printing of grid coordinate ranges for `Bounded` dimensions.
=> Bump v0.33.0

src/Fields/field_tuples.jl, src/Fields/show_fields.jl, src/Models/incompressible_model.jl, src/OutputWriters/checkpointer.jl, src/OutputWriters/output_writer_utils.jl, src/Utils/versioninfo.jl, test/test_output_writers.jl
This PR fixes some checkpointer bugs and improves the `restore_from_checkpoint` interface. The checkpointer has more comprehensive tests now. This PR was originally @sandreza's PR #797 but was accidently merged prematurely then reverted.
* `restore_from_checkpoint` now takes kwargs like a model constructor instead of a dictionary. This should be more intuitive and easier to use.
* Checkpointing and restoring from a checkpoint with function boundary conditions works now. If function boundary conditions are not manually restored, they are replaced with `missing`. They are restored correctly if passed via the `boundary_conditions` kwarg to `restore_from_checkpoint` and the model can be time stepped.
* Checkpointing and restoring between architectures works now. I've tested CPU -> GPU and GPU …
=> Checkpointer bug fixes and improved interface

Project.toml
Release notes:
This release adds some new features, fixes some bugs, and improves the API (so there are some breaking changes, listed below).
Major changes:
* Triply periodic models are now available by passing the `topology = (Periodic, Periodic, Periodic)` keyword argument to grids.
* All 1D, 2D, and 3D averages are now available through the `Average` diagnostic with the `dims` keyword argument.
* Fixed some checkpointing bugs.
* **BREAKING:** Use `Average(..., dims=(1, 2))` instead of `HorizontalAverage(...)`.
* **BREAKING:** Use `iteration_interval` and `time_interval` instead of `frequency` and `interval` for diagnostics and output writers.
* **BREAKING:** Use `iteration_interval` instead of `progress_frequency` for simulations.
* **BREAKING:** Use `IsotropicDiffusivity` and …
=> Bump v0.34.0

Project.toml
Release notes:
This is a bugfix release that disables CuArray scalar operations by default (to avoid surprise scalar operations that can cause huge slowdowns) and **fixes a related bug where writing GPU fields to NetCDF was very slow**. Also includes small updates to the documentation.
=> Bump v0.34.1

benchmark/benchmark_static_ocean.jl, src/Oceananigans.jl
Converted `benchmark_static_ocean.jl` to do a strong scaling test on a 256³ simulation when `Threads.nthreads() > 1`.
Results are pretty sweet for multithreading that we basically got for free from KernelAbstractions.jl. Not sure what kind of speedups to expect for multithreading though. Maybe @leios, @christophernhill, or @vchuravy have a better idea.
Some results on number of threads and wall clock time per time step:
```zsh
#!/bin/zsh
for threads in 1 4 8 16 24 32 40; ~/julia-1.5.0/bin/julia  --project -t $threads benchmark_static_ocean.jl
```
```
Julia 1.5.0 + Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
1 thread:   3.78 s
4 threads:  1.35 s (2.8x)
8 threads:  839 ms (4.5x)
16 threads:  585 ms (6.5x)
24 threads:  551 ms (6.9x)
32 threads:  539 ms (7.0x)
40 threads:  483 ms (10.6x)
48 …
```
=> Multithreading benchmarks

.appveyor.yml, .gitlab-ci.yml, .travis.yml, Dockerfile, README.md, codecov.yml, test/runtests.jl
This PR splits the tests into four test groups, selectable with the `TEST_GROUP` environment variable: `unit`, `integration`, `regression`, and `scripts`. Using `TEST_GROUP=all` (the default if `TEST_GROUP` is not defined) will run all tests.
The purpose of this PR is to address long test build times (see #860) that time out at 50 minutes on Travis CI and at 60 minutes on GitLab CI by splitting tests into multiple jobs (i.e. building a job matrix) that each should individually run much faster.
If the different jobs could be run in parallel this would speed up our test builds significantly, but alas we are stuck with free-tier CI pipelines so we can't run too many jobs in parallel and will probably end up waiting longer. But at least our jobs won't time out.
In working on this PR I was …
=> Split tests into four groups for CI job matrices

src/Fields/field.jl, src/Grids/Grids.jl, src/Grids/grid_utils.jl
This PR nukes the unused, incorrect method `total_size(grid::AbstractGrid)` ~~(and an unused fallback method)~~ and moves `total_size(loc, grid)` from `Fields/field.jl` to `Grids/grid_utils.jl`.
Resolves #883
=> Moves total_size(loc, grid) to grid_utils.jl

Project.toml
This release will go alongside the JOSS paper.
Release notes:
* Support for multithreaded CPU simulations! Set the number of threads via the `JULIA_NUM_THREADS` environment variable or via the `-t` flag in Julia 1.5+.
* New `OceananigansLogger` for fancy log messages with time stamps.
* New experimental diagnostic `WindowedTimeAverage`.
* `Average` diagnostic can include or exclude halos via the `with_halos` keyword argument.
* Improved testing infrastructure made possible by splitting tests into four groups.
* Cleaned up convergence test scripts and plots. Convergence tests can be run via the `TEST_GROUP=convergence`.
* Numerous bug fixes and documentation updates.
=> Bump v0.35.0

src/Simulations/run.jl, test/test_output_writers.jl, test/test_simulations.jl
This PR introduces the concept of an output writer "diagnostic dependency": a diagnostic which must be added to `simulation.diagnostics` in order for output to be correct.
If a type of output has a "diagnostic dependency", it must define the function `add_dependency!(diagnostics, output)`, which will add any appropriate diagnostics to the ordered dictionary `diagnostics`.
Currently we only have one type of output that requires a diagnostic, which is the `WindowedTimeAverage`. For `WindowedTimeAverage`, `add_dependency!` is
```julia
add_dependency!(diags, wta::WindowedTimeAverage) = !(wta ∈ values(diags)) && push!(diags, wta)
```
(As a side note, we could require that all values of `diagnostics` are unique, which would obviate the check above.)
=> Output writer "diagnostic dependencies"

docs/src/model_setup/boundary_conditions.md, examples/eady_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, src/BoundaryConditions/BoundaryConditions.jl, src/BoundaryConditions/boundary_condition.jl, src/BoundaryConditions/boundary_function.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/BoundaryConditions/parameterized_boundary_condition.jl, src/BoundaryConditions/show_boundary_conditions.jl, test/test_boundary_conditions.jl, test/test_time_stepping_bcs.jl
This PR simplifies the API for specifying boundary conditions that are functions.
We build boundary conditions by writing
```julia
bc = BoundaryCondition(BCType, condition)
```
where `BCType` is the "type" of the boundary condition (`Value`, `Gradient`, `Flux`, `NormalFlow`), and `condition` is the boundary condition.
If `condition` is a function, it is now assumed it can be called with the signature `condition(ξ, η, t)`, where `(ξ, η)` are spatial coordinates that vary along the boundary in question (`y, z` for `x`-boundaries, `x, z` for `y`-boundaries, and `x, y` for `z`-boundaries).
Different behavior is achieved by specifying keyword arguments of `BoundaryCondition`. For example, a non-`nothing` `parameters` keyword argument means that the last argument of condition is `parameters`: …
=> Simplifies boundary condition interface, types, and constructors

src/AbstractOperations/show_abstract_operations.jl, src/Fields/show_fields.jl, src/Grids/regular_cartesian_grid.jl, test/test_grids.jl
Before:
```
BinaryOperation at (Cell, Cell, Cell)
├── grid: RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}
│   ├── size: (16, 16, 16)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0625]
└── tree: 
* at (Cell, Cell, Cell) via identity
├── OffsetArray{Float64, 3, Array{Float64,3}}
└── OffsetArray{Float64, 3, Array{Float64,3}}
```
After:
```
BinaryOperation at (Cell, Cell, Cell)
├── grid: RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}
│   ├── size: (16, 16, 16)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
└── …
```
=> Nicer `Base.show` for abstract operations

src/OutputWriters/netcdf_output_writer.jl, test/test_output_writers.jl
This PR refactors the `NetCDFOutputWriter` constructor by getting rid of the `write_grid_and_attributes` function and by changing the boolean `clobber` keyword argument to `mode`, which is passed to NCDatasets.jl and takes on the values `"c"` for create/clobber or `"a"` for append.
Passing `mode="a"` allows you to append to an existing NetCDF file. I added some tests for this.
This is important if we want to keep using the same NetCDF file after restoring from a checkpoint.
cc @suyashbire1 
Resolves #913
=> Fix appending to NetCDF file

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/computations.jl, src/AbstractOperations/interpolation_utils.jl, src/Grids/Grids.jl, src/Grids/grid_utils.jl, src/Oceananigans.jl, src/Utils/Utils.jl, src/Utils/kernel_launching.jl, test/test_abstract_operations.jl
=> Fix computation work layout for faces along bounded dimensions

.travis.yml, Project.toml
OK so looks like this will have to be the JOSS release and include the JOSS paper in the repository (#564).
I'd also like to include PRs #910 and #915 in this release.
@glwagner Do you want to include any PRs in v0.36.0?
Release notes:
This release coincides with the publication of the Oceananigans.jl Journal of Open Source Software (JOSS) paper.
Changelog:
* Simplified boundary condition interface, types, and constructors. (@glwagner do you want add to this, maybe include a list of breaking changes?)
* Support for a `NonTraditionalBetaPlane` Coriolis force implementation.
* The `AnisotropicBiharmonicDiffusivity` closure now works properly in closed domains with zero `Flux` boundary conditions, as higher-order boundary conditions are enforced.
* Bug fix: Appending to NetCDF files with …
=> Bump v0.36.0 (JOSS release)

src/Fields/Fields.jl, src/Fields/field.jl, src/Fields/new_data.jl, src/TurbulenceClosures/diffusivity_fields.jl
This PR cleans up the `Fields` module: previously, `zeros` was overloaded in a confusing way that would return either `Array` / `CuArray` or an `OffsetArray` depending on the arguments. 
This PR introduces a function `new_data` that returns an `OffsetArray`. `new_data` is intended to build `OffsetArrays` that hold the data associated with a field, using the architecture, grid eltype, and the field location to determine array type, size, and indexing.
This PR moves the vanilla `zeros` definitions (convenience methods that use `eltype(grid)` to determine floating point type and `arch` to determine whether or not an array is converted to `CuArray`) to `Fields.jl` top-level.
=> Clean up Fields module

src/Fields/abstract_field.jl, src/OutputWriters/OutputWriters.jl, src/OutputWriters/fetch_output.jl, src/OutputWriters/jld2_output_writer.jl, test/test_output_writers.jl
This PR modifies the `JLD2OutputWriter` so that fields can be used as output.
This renders `FieldOutputs` obsolete; however we leave this in place for now for backward compatibility. Eventually it should be removed.
=> Functionality for output as fields with JLD2

src/Diagnostics/windowed_time_average.jl, src/OutputWriters/jld2_output_writer.jl
Mostly, this PR ensures that `compute!(field)` is called before fetching the "operand" (previously called `kernel`) of the `WindowedTimeAverage`.
This anticipates the new types `AveragedField` and `ComputedField` that will replace `Average` and `Computation`.
=> Starts process of modernizing WindowedTimeAverage

test/test_abstract_operations.jl, test/test_benchmarks.jl, test/test_boundary_conditions.jl, test/test_diagnostics.jl, test/test_forcings.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl
Many models of size (16, 16, 16) are reduced to size (1, 1, 1). Oftentimes the test just executes a time-step to ensure there's no error. For this, a size (1, 1, 1) is sufficient.
=> Slims down model size for many tests

src/Buoyancy/Buoyancy.jl, src/Buoyancy/buoyancy_field.jl, src/Fields/abstract_field.jl, src/Fields/field.jl, test/test_abstract_operations.jl
This PR adds a `BuoyancyField` which is a type of lazily computed field constructed via `b = BuoyancyField(model)`. 
`BuoyancyField` represents model buoyancy in abstract operations:
```julia
b = BuoyancyField(model)
wb = ComputedField(w * b)
```
etc. This is important for nonlinear equations of state, where statistics that depend on buoyancy need to be calculated online.
cc @BrodiePearson
Side note: we need the same for `PressureField`.
=> BuoyancyField

Project.toml
I think we should tag a v0.37.0 release to ensure we have a code checkpoint before which we were recomputing w and after which we were not (since it's a change to the numerical methods). Might be good if we do this before merging in RK3.
=> Bump v0.37.0

src/BoundaryConditions/zero_halo_regions.jl, src/Fields/averaged_field.jl, test/test_averaged_field.jl
This PR adds a `dims` keyword argument to `zero_halo_regions`, so that we can avoid zeroing out halo regions in directions that are not averaged. It also adds tests to ensure that this works.
This PR does not solve all the issues with averaging halo regions, however. In particular, the halo regions are not guaranteed to be correct because they may have been previously zeroed out.
This can be solved by calling `fill_halo_regions` prior to computing an average. However, this solution is not possible with the current syntax, because field boundary conditions can depend on other fields of model that are not available within `compute!(averaged_field)`. I will raise an issue after this PR to discuss this other problem, which involves some difficult trade-offs.
=> Do not zero out halo regions in directions that arent averaged

src/AbstractOperations/averages_of_operations.jl, src/Buoyancy/buoyancy_field.jl, src/Fields/abstract_field.jl, src/Fields/averaged_field.jl, src/Fields/computed_field.jl, src/Fields/pressure_field.jl, src/Models/Models.jl, src/OutputWriters/fetch_output.jl, test/test_abstract_operations.jl, test/test_averaged_field.jl, test/test_fields.jl
This PR implements an optimization that (potentially) avoids redundant recompilation of fields when `compute!(output)` is called in `fetch_output`. This optimization was discussed on #955 .
The idea is to use `model.clock.time` as a "key" which is checked prior to computation. Fields that opt-in to avoid recomputation then check if `model.clock.time == field.status.time`. If the two are equal, no computation is performed.
This will hopefully speed up expressions that involve `AveragedField`s, `ComputedField`s, and `BuoyancyField`. Note that in the case that users specify scratch space for a field, they must opt-in to this optimization by passing `recompute_safely=false` to the field constructor. If scratch space is not specified (and we therefore know it is unique), recomputation is …
=> Avoiding unnecessary recomputation of fields in output evaluation

src/Advection/Advection.jl, src/Advection/centered_advective_fluxes.jl, src/Advection/centered_fourth_order.jl, src/Advection/centered_schemes.jl, src/Advection/topologically_conditional_interpolation.jl, src/Advection/upwind_biased_advective_fluxes.jl, src/Advection/upwind_biased_third_order.jl, src/Operators/interpolation_operators.jl, test/test_time_stepping.jl
This PR implements a new framework for high-order advection schemes.
There are two types of advection schemes: `AbstractCenteredAdvectionScheme` and `AbstractUpwindBiasedAdvectionScheme`.
This PR implements momentum and tracer flux operators such that an centered advection scheme needs only to implement 7 functions: 6 `symmetric_interpolate_*` functions for `x, y, z` at cell centers and interfaces, and a `boundary_buffer` scheme that indicates the buffer needed around boundaries in `Bounded` directions`. 
Upwind biased advection schemes need 19 functions: `halo_buffer`, 12 functions for `left_biased_interpolate_*` and `right_biased_interpolate_*`, and 6 functions for `symmetric_interpolate_*` that use a symmetric interpolation (typically of order `m-1`, where `m` is the order of the …
=> New framework for high-order advection schemes

Manifest.toml, Project.toml, src/Advection/weno_reconstruction.jl, test/test_weno_reconstruction.jl
To make use of the new forcing function API in #989 and to fix #990 and #991 I think we should tag v0.39.0 once the current batch of PRs has been merged.
=> Bump v0.39.0

src/AbstractOperations/averages_of_operations.jl, src/Buoyancy/buoyancy_field.jl, src/Fields/abstract_field.jl, src/Fields/averaged_field.jl, src/Fields/computed_field.jl, test/test_abstract_operations.jl, test/test_averaged_field.jl
The primary issue fixed here are actually the tests themselves, rather than the implementation. However this PR also makes a number of small improvements to the implementation, including a bug in which `recompute_safely` was implemented wrong (despite producing correct behavior, due to a "cancellation of errors").
It looks like computations on `Faces` and along `Bounded` dimensions may not be possible with `BuoyancyField`. I will open an issue with an MWE. This is not a high-priority, because making such computations on boundaries correct in general really requires solving #971 ; otherwise we cannot guarantee that boundary conditions are correct (and they will often be wrong when averages are taken, as they commonly are during output).
Relies on #1016 .
=> Fixes tests with AveragedField and BuoyancyField

Project.toml
We should tag and release v0.40.0 once PR #1020 is merged since GPU tests fail on v0.39.0 and #1020 fixes things so all tests pass.
=> Bump v0.40.0

src/OutputWriters/field_slicer.jl
Converts integer `FieldSlicer` indices to correct parent indices, taking halos into account.
Resolves #1028
=> Proper FieldSlicer indices

.buildkite/pipeline.yml
Kind of a work-in-progress but would be good to merge as PR #997 depends on these changes.
Not the final form of the Buildkite pipeline as I'm still working on improving and expanding it but so far there's an initial job/stage that downloads Julia and instantiates, precompiles, etc. Then all the other jobs can use this new Julia environment to run their tests.
Past behavior was just to reuse my Julia environment. I think it's important that CI always creates a fresh environment from scratch as this is how users will install the code usually, and it will help us catch issues like #991 early.
=> Better Buildkite CI pipeline

.buildkite/pipeline.yml
Was accidently running on the Caltech cluster. Also, now it only downloads Julia if the server version is newer than an existing local file (`wget -N`).
=> Run Buildkite cleanup step on Tartarus

src/OutputWriters/fetch_output.jl, src/OutputWriters/field_slicer.jl
Array conversions when fetching output trigger `copyto!` and then `getindex`, which is in turn disallowed.
This PR fixes an issue with output on the GPU on master.
I'm a bit perplexed why the `jld2_field_output` test didn't pick this up.
=> Use allowscalar when converting output

Project.toml
Release notes:
This release adds support for time averaging and field slicing to `NetCDFOutputWriter`.
**Breaking changes**:
* `NetCDFOutputWriter` constructor: The `filename` keyword argument is now `filepath`.
* `NetCDFOutputWriter` constructor: To specify slices, pass a `FieldSlicer(i, j, k; with_halos)` instead of using the `xC`, `xF`, `yC`, `yF`, `zC`, and `zF` keyword arguments.
=> Bump v0.42.0

Project.toml
In the spirit of getting closer to continuous delivery (see https://www.oxinabox.net/2019/09/28/Continuous-Delivery-For-Julia-Packages.html#what-if-i-dont-want-to-release-right-now--dev-versions) we should probably tag and release v0.43.0 soon since PRs #1070, #1057, and #1061 + couple of bug fix PRs would be useful to have.
Release notes:
* Fixes a bug in `TwoDimensionalLeith` (PR #1073, issue #1034). Previously tests were being skipped due to extreme slowness. Now we run tests on GPU (but not CPU, where the closure is much slower to compile).
* Rewrites the interface for "scheduling" output and diagnostics (PR #1070). Previously output and diagnostics were usually scheduled by specifying either `time_interval` or `iteration_interval` kwargs in the constrcutor for the object in question. …
=> Bump v0.43.0

src/OutputWriters/field_slicer.jl
Would be nice if things like `FieldSlicer(k=grid.Nz/2)` worked out of the box. This PR makes this possible.
cc @suyashbire1
=> Field slicing with floats and other numbers

examples/eady_turbulence.jl
A missing ` created a mess.
[this is probably a demonstration of Lorenz chaos..]
=> Typo in Eady example

src/TurbulenceClosures/turbulence_closure_diagnostics.jl
@mukund-gupta discovered a bug (see #1104) that prevents the use of function diffusivities with the `TimeStepWizard`.
We don't want the wizard to be so all-powerful that it samples a diffusivity function over the whole grid just to compute it's maximum value. So, this PR does the simple thing and avoids limiting the time-step by the diffusivity when it's a function.
A better solution would require users to explicitly ask their time-step to be limited by diffusivities, and for that step to fail when the diffusivity is a function (eg #1087).
It could make sense to add a test for all possible combinations of diffusivities and wizards, but it might be better to wait for a more comprehensive PR that addresses #1087...
Resolves #1104
=> Blending magic and diffusivities-as-functions

examples/ocean_wind_mixing_and_convection.jl, examples/two_dimensional_turbulence.jl
Currently colorbars in some of the examples "oscillate". See, e.g., vorticity colormap as is now:
After this PR:
=> Remove "colorbar oscillations" in examples

docs/make.jl
(and not the deprecated 'latest')
=> "stable" url should be the canonical for Docs

docs/make.jl, examples/kelvin_helmholtz_instability.jl
This PR adds an example that computes the linear instability of a vertically shear mean flow profile U(z) accompanied with a sheared buoyancy profile B(z) and then evolves the unstable eigenmode to its nonlinear equilibration.
[preview of the docs](https://clima.github.io/OceananigansDocumentation/previews/PR1125/generated/kelvin_helmholtz_instability/)
=> Adds Kelvin-Helmholtz instability example

examples/langmuir_turbulence.jl
This PR updates the Langmuir turbulence example to have an initial mixed layer 33 meters deep. This initial mixed layer was prescribed by [McWilliams et al. (1997)](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/langmuir-turbulence-in-the-ocean/638FD0E368140E5972144348DB930A38), which escaped me when I first read that paper.
Thanks to @qingli411 for alerting me to this.
=> Langmuir Turbulence in the Ocean has a mixed layer

src/OutputWriters/netcdf_output_writer.jl, test/test_output_writers.jl
Constructing dictionaries for `NetCDFOutputWriter` can be quite boilerplate-y. This PR also helps unify the JLD2 and NetCDF output writers (see #884).
=> NetCDFOutputWriter accepts named tuples now

src/Models/incompressible_model.jl, test/test_models.jl
Resolves #1118
Needs a `@test_throws`. Ruins the formatting of the `IncompressibleModel` constructor but small price to pay.
=> Make sure users always construct a model with an `AbstractArchitecture`

examples/two_dimensional_turbulence.jl
thanks @francispoulin
closes #1167
=> Fix erroneous double hashes in two_dimensional_turbulence.jl example

CONTRIBUTING.md, README.md
This PR changes our contributor's guide to [ColPrac](https://github.com/SciML/ColPrac), which I think is a pretty useful guide on how to work collaboratively on packages.
We already follow some of the guide's suggestions around PRs so might as well follow the entire guide.
What do people think about it?
Might be good to adopt something like ColPrac as more people start working together on Oceananigans. cc @navidcy @whitleyv @francispoulin
Resolves #1044
=> Switch to ColPrac: Contributor's Guide on Collaborative Practices for Community Packages

benchmark/benchmark_multithreading.jl, src/Oceananigans.jl
Resolves #1113 
Needs new multi-threading benchmarks. Will do as part of #1088 (need to add nice multithreading benchmark script on `ar/benchmarks` branch).
=> Use 4x more threads for FFTW

examples/two_dimensional_turbulence.jl
@suyashbire1 and I noticed that the speed plot was transposed twice so it was oriented wrong.
=> Fix speed plot in `two_dimensional_turbulence.jl`

src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl
Although the implementation looks correct, the docs on the Leith closure were describing its eddy viscosity as being proportional to the magnitude of the vertical vorticity, rather than the magnitude of the gradient of the vertical vorticity.
=> Fix math in Leith documentation

src/Solvers/index_permutations.jl, test/test_pressure_solvers.jl
Thanks to @leios and @francispoulin for feedback that helped locate the issue!
Resolves #1170 
This PR fixes a bug in how index unpermutation is done as part of the Makhoul (1980) fast cosine transform algorithm we use for the GPU. It only affected wall-bounded dimensions of odd length (see below).
Oceananigans was effectively setting the pressure to zero at the topmost grid point (it was actually accessing memory from out-of-bounds but since the bug was pretty consistent I assume it always grabbed some close-to-zero number).
I'm shocked that no test picked this up... But looking at our tests, we don't test dimensions of odd length on the GPU. This is probably because in earlier versions of Oceananigans, GPU models only supported dimension lengths that were multiples of 16 (due to …
=> Fix index permutation for GPU DCT when dimension size is odd

Project.toml
Probably important to tag and release a new version following #1228.
=> Bump v0.45.0

src/Diagnostics/Diagnostics.jl, src/Diagnostics/nan_checker.jl, src/Simulations/simulation.jl, test/test_diagnostics.jl
This PR adds a NaN checker that checks for NaNs in the `[1, 1, 1]` grid point of the velocity fields at every time step (which should be very cheap and not affect performance).
When a NaN is detected, an `ErrorException` is thrown so when running in the REPL it'll error and return control to the REPL, while if running a script from the terminal, it will terminate the Julia session (seems like the behavior we all want).
Resolves #938
Resolves #1196
=> Add NaN checker to simulations by default

Project.toml, src/Simulations/Simulations.jl, src/Simulations/simulation.jl
Shallow water model tests are failing on master because `model.velocities.u` does not exist for `ShallowWaterModel`.
This PR fixes this by checking for NaNs in the model's first field.
=> Check for NaNs in the model's first field

src/Forcings/continuous_forcing.jl, src/Forcings/model_forcing.jl, src/Forcings/relaxation.jl, src/Models/IncompressibleModels/incompressible_model.jl, src/Models/ShallowWaterModels/shallow_water_model.jl, src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl, src/Operators/interpolation_utils.jl, src/TimeSteppers/TimeSteppers.jl, test/test_shallow_water_models.jl
This PR (pair programmed with @francispoulin) allows users to select the `timestepper` and adds support for `forcing` functions as part of the `ShallowWaterModel`. We also added some simple tests.
We also added a `shallow_water_model_forcing` function that should readily generalize to `IncompressibleModel` while being shorter, so we can consider using it to replace `model_forcing`.
Resolves #1284
=> Timesteppers and forcing functions for shallow water models

docs/Manifest.toml, docs/Project.toml, examples/convecting_plankton.jl, examples/eady_turbulence.jl, examples/internal_wave.jl, examples/kelvin_helmholtz_instability.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/one_dimensional_diffusion.jl, examples/two_dimensional_turbulence.jl
This PR brings back `.mp4` file format for animations in the Documentations (instead of much bigger in size `.gif` format). 
For the `.mp4` files generated with Plots.jl to be viewable by all browsers it's required that Plots.jl v1.10.1 or later is used.
Closes #944.
=> Animations in Docs go back in using mp4 instead of gif

docs/src/using_gpus.md, examples/convecting_plankton.jl, examples/eady_turbulence.jl, examples/internal_wave.jl, examples/kelvin_helmholtz_instability.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/one_dimensional_diffusion.jl, examples/two_dimensional_turbulence.jl
This PR instead of executing, e.g.,
```
using Pkg
pkg"add Oceananigans, JLD2, Plots"
```
it just prints them out as markdown "code". This way users can have them in the docs to copy-paste but the Documentation build does not execute them and thus avoids random clutter in Docs like discussed in #1315.
Closes #1315.
=> Avoid executing the lines to install dependencies within examples

src/Simulations/run.jl
This is a temporary fix for #1280 (time stepping a model with `pickup=true` -> it blows up) until schedules can be probably checkpointed.
While this is a temporary fix, it has affected a number of people already (@qwert2266, @suyashbire1, @sandreza, and now @sam12396 in #1300) so would be good to merge this and tag a new release.
=> Always take positive time steps

examples/internal_wave.jl
There were 4 backticks instead of 3.
=> Fixes bug in internal wave example that resulted in mangled text

src/Models/ShallowWaterModels/ShallowWaterModels.jl, src/Models/ShallowWaterModels/shallow_water_cell_advection_timescale.jl, test/test_shallow_water_models.jl
This correctly adds the time-step wizard to `ShallowWaterModel`.  
All the tests pass but there are two warnings that maybe should be adressed?
```
...
[2021/02/01 11:45:05.426] INFO    Testing setting shallow water model fields...
[2021/02/01 11:45:12.752] WARN  Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)` -@-> /home/fpoulin/.julia/packages/GPUArrays/WV76E/src/host/indexing.jl:43
...
[2021/02/01 11:45:39.457] INFO    Testing time-step wizard ShallowWaterModels [GPU(), ((Periodic, Periodic, Bounded), (Periodic, Bounded, Bounded), (Bounded, Bounded, Bounded))[1]]...
[2021/02/01 11:45:39.641] WARN  You have used the default iteration_interval=1. This simulation will recalculate the time step every iteration …
```
=> Creating the time-step wizard for shallow water model.

src/OutputWriters/netcdf_output_writer.jl
Currently `with_halos` is listed as a keyword for NetCDFOutputWriter, but it's really a keyword for `FieldSlicer`.
=> Fixed inconsistency in docs for NetCDFOutputWriter

Project.toml, docs/src/model_setup/grids.md
This PR removes the section discussing grid topology restrictions since all the restrictions were alleviated after #1338.
Also, it removes discussions regarding `Flat` topologies since, at the moment, this functionality is not functional (see #1023 and #1024).
=> Updates Docs (Grids section)

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
It doesn't exist!
Noticed by @navidcy .
=> Deletes reference to PressureSolver in hydrostatic_free_surface_model

src/Fields/reduced_field.jl
This will be needed to make `HydrostaticFreeSurfaceModel.free_surface.η` a `ReducedField`.
=> Conservatively adapt ReducedField for GPUs

examples/geostrophic_adjustment.jl
You can never avoid all typos..
=> Fix typo in Geostrophic Adjustement example

src/BoundaryConditions/BoundaryConditions.jl, src/BoundaryConditions/fill_halo_regions_flat.jl, src/BoundaryConditions/fill_halo_regions_nothing.jl, src/Fields/computed_field.jl, src/Fields/kernel_computed_field.jl, test/test_abstract_operations_computed_field.jl, test/test_kernel_computed_field.jl
This PR adds `boundary_conditions` to `ComputedField`.
I added a new `DefaultComputedFieldBoundaryCondition`, because `DefaultBoundaryCondition` specifies an `ImpenetrableBoundaryCondition` when a field is located on `Face` and the direction is `Bounded`. But I think this is only appropriate for velocities and is not what we want in general. Arguably, we should change `DefaultBoundaryCondition` instead and implement special behavior for velocity fields...
Strictly speaking the boundary conditions are only "correct" in periodic directions, since we have no way of evaluating what the boundary conditions need to be in `Bounded` directions. Should we use a `nothing` default for `Bounded` directions in all cases for `ComputedField`?
Current tests pass, but I still need to add tests to make …
=> Adds boundary conditions to ComputedField and KernelComputedField

src/Coriolis/f_plane.jl, src/Operators/areas_and_volumes.jl
This PR adds areas, volumes, and a few product operators needed to evaluate correct Coriolis terms on curvilinear grids, following
https://mitgcm.readthedocs.io/en/latest/algorithm/algorithm.html#id8
Before merging we should discuss:
- Should I update all the Coriolis terms? (`beta_plane.jl, non_traditional_f_plane.jl`, etc?)
- Are we ok using three-letter codes, even though we only plan to support horizontally-curvilinear grids (rather than vertically curvilinear grids) in the near future?
- Should we add more regression tests / evaluate existing regression tests before changing terms that are not covered?
- It's not feasible to adapt the _entire_ codebase to work on curvilinear grids right now. How should we handle throwing errors for cases that are not supported? Adding …
=> Adds a few areas and volumes needed for correct Coriolis terms on curvilinear grids

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_advection.jl, src/Operators/Operators.jl, src/Operators/areas_and_volumes.jl, src/Operators/divergence_operators.jl, src/Operators/vorticity_operators.jl, test/test_hydrostatic_free_surface_models.jl
This PR cleans up the horizontal divergence and vertical vorticity operators for horizontally-curvilinear grids. It also adds a test to ensure that `HydrostaticFreeSurfaceModel` continues to work with `momentum_advection=VectorInvariant()`.
=> Horizontal divergence and vertical vorticity operators

src/Grids/Grids.jl, src/Grids/regular_cartesian_grid.jl, src/Grids/vertically_stretched_cartesian_grid.jl, src/Operators/Operators.jl, src/Operators/areas_and_volumes.jl, src/Operators/derivative_operators.jl, src/Operators/difference_operators.jl, src/Operators/field_metric_products.jl, test/test_operators.jl
This PR adds horizontal grid spacing and gradient operators valid on curvilinear grids.
This means that a class of gradient operators will persist which are only valid on Rectilinear grids. To help prevent bugs associated with incorrectly applying these restricted operators to general grids, this PR also adds a new type `AbstractRectilinearGrid`.
Note: apparently we have been using the term "Cartesian" incorrectly, since ["Cartesian" only applies to coordinate systems with _unit_ areas and volumes](https://en.wikipedia.org/wiki/Regular_grid). So really we have a `RegularRectilinearGrid` and `VerticallyStretchedRectilinearGrid` (in the later case, horizontal regularity is implicit).
=> AbstractRectilinearGrid and curvilinear horizontal grid spacing and gradient operators

docs/Manifest.toml
This PR tests whether `push_previews` will work with buildkite using the latest version of Documenter.
=> Update Documenter v0.26.2

docs/src/contributing.md
This PR adds instructions for how a contributor can build the documentations locally and preview them.
I was tempted to add some info about doc previews but I think doc previews are not generated for PR that come from forks so it's not a good idea to have it in the Contributors Guide.
=> Adds instruction for building docs locally in the Contributors Guide

src/Solvers/Solvers.jl
I accidentally left a duplicate `include("index_permutations.jl")` when resolving some merge conflicts in PR #1348 which led to method redefinition errors. This PR should get rid of those errors.
=> Remove duplicate include

src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
This PR updates the HydrostaticFreeSurfaceModel RHS kernel functions to use the correctly-located pressure gradient for curvilinear grids.
=> Correct pressure gradients for curvilinear grids in HydrostaticFreeSurfaceModel

Project.toml
There have been 78 commits since the last release so I thought it would be good to put out a checkpoint release. Happy to close this PR if people think this is not necessary.
Release notes could say:
Checkpoint release including very experimental support for curvilinear grids, a vertically-stretched rectilinear grid, and a preconditioned conjugate-gradient solver.
(or nothing at all)
There should be no breaking changes.
=> Bump v0.49.0 (as a checkpoint)

docs/src/model_setup/checkpointing.md, src/OutputWriters/checkpointer.jl, src/Simulations/run.jl, test/test_output_writers.jl
This PR adds support for "cleaning up" previous checkpoints. Setting `cleanup=true` will cause the checkpointer to delete all previous checkpoints after the latest one has been written.
Pair programmed with @qwert2266.
=> Add support for only keeping the latest checkpoint

Manifest.toml, Project.toml, src/OutputWriters/netcdf_output_writer.jl, src/Simulations/run.jl, src/TimeSteppers/clock.jl, test/test_output_writers.jl, test/test_simulations.jl
This PR adds support for time step alignment and NetCDF output with `DateTime` (from `Base.Dates`) and `TimeDate` (from TimesDates.jl).
Confusing names but `DateTime` is a base Julia type, has millisecond accuracy, and is understood by NCDatasets.jl while `TimeDate` comes from TimesDates.jl, has nanosecond accuracy, and must be converted to a `DateTime` to be written to NetCDF by NCDatasets.jl.
Interestingly the way NetCDF stores dates and times is by storing a floating point value and some metadata describing it as e.g. "seconds since 2000-01-01 00:00:00". Could be minutes, hours, days, since 1900, etc.
Not sure if we'll need the nanosecond accuracy but millisecond accuracy can cause an error on the order of a day after ~100 million iterations which could matter if used to compare …
=> Time step alignment and NetCDF output for `DateTime` and `TimeDate`

.buildkite/pipeline.yml, Project.toml, benchmark/Manifest.toml, benchmark/benchmark_fourier_tridiagonal_poisson_solver.jl, benchmark/benchmark_vertically_stretched_incompressible_model.jl, src/Buoyancy/nonlinear_equation_of_state.jl, src/Grids/Grids.jl, src/Grids/grid_utils.jl, src/Grids/vertically_stretched_rectilinear_grid.jl, src/Operators/areas_and_volumes.jl, src/Solvers/fft_based_poisson_solver.jl, src/Solvers/fourier_tridiagonal_poisson_solver.jl, src/Solvers/plan_transforms.jl, test/regression_tests/ocean_large_eddy_simulation_regression_test.jl, test/regression_tests/rayleigh_benard_regression_test.jl, test/regression_tests/thermal_bubble_regression_test.jl, test/runtests.jl, test/test_grids.jl, test/test_poisson_solvers.jl, test/test_regression.jl
This PR completes the implementation of the vertically stretched grid (PR #1348) by supporting all topologies on the CPU and GPU.
Well, I think a batched tridiagonal solve in the vertical is only possible if the z dimension is `Bounded`, so "all topologies" only includes the four topologies with z being `Bounded`.
If the stretched dimension is periodic, then I think the system of linear equations is no longer tridiagonal (you get non-zero elements in the corner of the matrix). I vaguely recall @christophernhill mentioning that there may be a way around this?
I'm also going to bump v0.51.0 in this PR.
X-Ref: #586
=> Vertically stretched grids for all topologies on CPUs and GPUs

Project.toml, docs/src/model_setup/checkpointing.md, examples/convecting_plankton.jl, examples/eady_turbulence.jl, examples/geostrophic_adjustment.jl, examples/internal_wave.jl, examples/kelvin_helmholtz_instability.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/one_dimensional_diffusion.jl, examples/two_dimensional_turbulence.jl, src/Models/Models.jl, src/Oceananigans.jl, src/StokesDrift.jl, src/Units.jl, src/Utils/Utils.jl, src/Utils/pretty_time.jl, test/runtests.jl, test/test_stokes_drift.jl
This PR ensures enough things are exported by Oceananigans that all the examples can get by with just `using Oceananigans`.
The purpose of this PR is to make the package more user friendly as missing names, e.g. `ComputedField`, have become a large source of errors for new users.
As this is a large change to the user interface, I've bumped v0.52.0.
Resolves #1075
Resolves #1131
Resolves #1132
=> All-purpose `using Oceananigans`

src/Grids/Grids.jl, src/Grids/regular_latitude_longitude_grid.jl, src/Oceananigans.jl, test/test_grids.jl
This PR adds tests for `RegularLatitudeLongitudeGrid` which uncovered a couple of stupid bugs in the process.
Sorry everyone. I guess we shouldn't be approving important PRs without tests in the future.
I've somehow convinced myself that we need `Nλ + 2Hλ + 1` grid points in longitude even when it's periodic (tests don't pass otherwise), but not sure why so maybe let's hold off on merging just yet.
This PR should fix things in PR #1404.
Also, I didn't like `test_grids.jl` so I refactored it.
=> Test and fix bugs in `RegularLatitudeLongitudeGrid`

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anistropic_diffusivity.jl, validation/curvilinear_diffusion/longitudinal_tracer_diffusion.jl, validation/curvilinear_diffusion/meridional_diffusion.jl, validation/curvilinear_diffusion/meridional_tracer_diffusion.jl, validation/curvilinear_diffusion/spot_tracer_diffusion.jl, validation/solid_body_rotation/solid_body_tracer_advection.jl
This PR implements validation experiments for `HorizontallyCurvilinearAnisotropicDissipation`.
There are three experiments:
1. `validation/curvilinear_diffusion/meridional_diffusion.jl`: Diffusion of a tracer and zonal momentum along a meridian
2. `validation/curvilinear_diffusion/longitudinal_tracer_diffusion.jl`: Diffusion of a tracer along a circle of constant latitude. We would need a non-trivial `NormalFlow` boundary condition to diffuse meridional momentum, so I didn't implement momentum diffusion for this experiment.
3. `validation/curvilinear_diffusion/spot_tracer_diffusion.jl`: Diffusion of a Gaussian spot in longitude and latitude.
https://user-images.githubusercontent.com/15271942/109988157-42787180-7cd5-11eb-8dfe-b6f173c6c623.mp4 …
=> Curvilinear diffusion validation experiments

docs/src/numerical_implementation/spatial_operators.md, docs/src/numerical_implementation/time_stepping.md
Fixing two small doc typos in 
spatial_operators:  difference should be a gradient
time_stepping: errant dt
=> Small typos

src/Solvers/plan_transforms.jl
I was trying to understand the dims pattern in the branching in `plan_transforms`, and ended up re-writing it a bit to understand it. Not sure if this is a preferable form, but I thought I'd open a PR in case. I need to double-check the logic, but maybe someone can confirm.
=> Make discrete transform plans more compact

.buildkite/pipeline.yml
Updates buildkite to use Julia v1.5.4.
Closes #1461.
=> Buildkite with Julia v1.5.4

src/BoundaryConditions/fill_halo_regions.jl, src/BoundaryConditions/fill_halo_regions_normal_flow.jl, src/Fields/computed_field.jl, src/Fields/function_field.jl, src/Fields/kernel_computed_field.jl, src/Fields/reduced_field.jl, src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl, src/Models/IncompressibleModels/pressure_correction.jl, src/Models/IncompressibleModels/update_incompressible_model_state.jl, src/Models/ShallowWaterModels/update_shallow_water_state.jl, src/Solvers/preconditioned_conjugate_gradient_solver.jl, test/test_averaged_field.jl, test/test_boundary_conditions_integration.jl, test/test_halo_regions.jl, test/test_operators.jl, test/test_poisson_solvers.jl, test/test_preconditioned_conjugate_gradient_solver.jl, test/test_reduced_field.jl, test/test_turbulence_closures.jl
This PR does two things:
1. It generalizes halo filling for `NormalFlow` boundary conditions so that `fill_halo_regions` works when the optional arguments `clock, model_fields` are not provided
2. It eliminates the unnecessary `arch` argument from `fill_halo_regions!`. In many cases `fill_halo_regions!(c::AbstractField)` will now work.
=> Improved fill_halo_regions

src/BoundaryConditions/fill_halo_regions.jl, src/BoundaryConditions/fill_halo_regions_normal_flow.jl, src/Fields/computed_field.jl, src/Fields/function_field.jl, src/Fields/kernel_computed_field.jl, src/Fields/reduced_field.jl, src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl, src/Models/IncompressibleModels/pressure_correction.jl, src/Models/IncompressibleModels/update_incompressible_model_state.jl, src/Models/ShallowWaterModels/update_shallow_water_state.jl, src/Solvers/preconditioned_conjugate_gradient_solver.jl, test/test_averaged_field.jl, test/test_boundary_conditions_integration.jl, test/test_halo_regions.jl, test/test_operators.jl, test/test_poisson_solvers.jl, test/test_preconditioned_conjugate_gradient_solver.jl, test/test_reduced_field.jl, test/test_turbulence_closures.jl
Reverts CliMA/Oceananigans.jl#1444
PR #1444 is quite nice but unfortunately I think the new `fill_halo_regions!`
```julia
fill_halo_regions!(c::AbstractArray, fieldbcs, grid, args...; kwargs...)
```
broke MPI halo filling since it needs dispatch on
```julia
fill_halo_regions!(c::AbstractArray, bcs, arch::AbstractMultiArchitecture, grid, c_location, args...)
```
It might be tricky to fix since you can't tell whether you're on `CPU` or `MultiCPU` from inside `fill_halo_regions!` with just knowledge of the `field`...
I propose we revert #1444 just for now (since distributed models + tests are broken on master) and immediately open a new PR with the contents of #1444 where we can find a solution. My only idea is to add `architecture` to Field but perhaps it feels a little bloated...
This …
=> Revert "Improved fill_halo_regions"

src/Grids/vertically_stretched_rectilinear_grid.jl
This changes the behavior of `show()` for VerticallyStretchedGrids to
```julia
VerticallyStretchedRectilinearGrid{Float64, Periodic, Periodic, Bounded}
domain: x ∈ [0.0, 500.0], y ∈ [0.0, 23.4375], z ∈ [0.0, 100.0]
topology: (Periodic, Periodic, Bounded)
resolution (Nx, Ny, Nz): (128, 1, 32)
halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (3.90625, 23.4375, [min=0.97654576571653, max=5.174919985099578])
```
This is very clear but also a bit on the verbose side. Another option would be
```julia
VerticallyStretchedRectilinearGrid{Float64, Periodic, Periodic, Bounded}
domain: x ∈ [0.0, 500.0], y ∈ [0.0, 23.4375], z ∈ [0.0, 100.0]
topology: (Periodic, Periodic, Bounded)
resolution (Nx, Ny, Nz): (128, 1, 32)
halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (3.90625, …
```
=> Adds information about Δz on show function for VerticallyStretchedGrid

src/BuoyancyModels/buoyancy.jl, src/BuoyancyModels/g_dot_b.jl, test/test_dynamics.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/1496
I went ahead and created the PR that makes the change from `gravitational_unit_vector` to `vertical_unit_vector` as discussed in #1496, but I'm still open to suggestions if people agree on a better name. I also created a docstring for the user-facing `Buoyancy()` function that explains what `vertical_unit_vector` is.
=> Change nomenclature of vertical direction for Buoyancy()

validation/lid_driven_cavity/lid_driven_cavity.jl, validation/lid_driven_cavity/plot_lid_driven_cavity.py
This PR just updates and cleans up the lid-driven cavity script. At some point I'd like to add all the validation experiments into CI and into the docs as advanced examples, but this will have to wait for now.
The issue is that the script was using `Flat` back when it did nothing but now when using `Flat` you need to pass a 2-tuple for the grid size. I switched the script from `Flat` to `Bounded` until `Flat` is fully working.
cc @maeckha
Resolves #1507
=> Update lid-driven cavity validation experiment

examples/spherical_splash.jl, src/Coriolis/hydrostatic_spherical_coriolis.jl, src/Grids/regular_latitude_longitude_grid.jl, src/Operators/spacings_and_areas_and_volumes.jl, test/test_grids.jl, test/test_netcdf_output_writer.jl, validation/barotropic_gyre/barotropic_gyre.jl, validation/solid_body_rotation/solid_body_rotation.jl
This PR changes `RegularLatitudeLongitudeGrid` to use (λ, φ) (`\lambda`, `\varphi`) for spherical/geographical coordinates as agreed on in #1437.
This is a breaking change so I'm hoping to get it into v0.54.0 along with PR #1489.
Resolves #1437
=> Use (λ, φ) (`\lambda`, `\varphi`) for geographical coordinates

examples/convecting_plankton.jl, examples/geostrophic_adjustment.jl, examples/internal_wave.jl, examples/kelvin_helmholtz_instability.jl, examples/one_dimensional_diffusion.jl, examples/two_dimensional_turbulence.jl, src/Operators/spacings_and_areas_and_volumes.jl, src/Simulations/time_step_wizard.jl, src/TurbulenceClosures/turbulence_closure_diagnostics.jl, src/Utils/cell_advection_timescale.jl, test/test_hydrostatic_free_surface_models.jl, test/test_shallow_water_models.jl, validation/lid_driven_cavity/lid_driven_cavity.jl
Do we want to update the one and two dimensional examples to include `Flat`? 
If not then we can ignore this PR.  
If yes, then this is my attempt to do so.  The good news is that most of the one and two dimensional examples work very easily.  Unfortunately, a couple of them, geostrophic adjustment and convecting plankton, do not.  I don't know why at the moment and these should certainly be fixed before a merge happens.  If it happens.
The error get I get is `NaN` after (I believe) the first interval. So I suspect one of the tendencies is not being computed correctly.
=> Updating examples to include `Flat`

src/AbstractOperations/derivatives.jl, src/Operators/spacings_and_areas_and_volumes.jl
This PR generalizes `AbstractOperation.Derivative` to work on horizontally-curvilinear grids.
=> Curvilinear abstract derivatives

src/Fields/field.jl, src/Fields/reduced_field.jl, test/test_field.jl
Calling `similar(f)` returns a field at the same location and with identical boundary conditions as `f` for `f::Field` and `f::ReducedField`.
cc @christophernhill
=> Implements `similar(f::Field)` and `similar(r::ReducedField)`

test/test_grids.jl
Unit tests are ~~failing~~ hanging because a data dependency has been updated causing the checksum to not match. https://github.com/CliMA/OceananigansArtifacts.jl/pull/3
=> Update cubed sphere 32 grid file sha256 checksum

Project.toml, docs/src/numerical_implementation/poisson_solvers.md, src/Operators/Operators.jl, src/Operators/derivative_operators.jl, src/Operators/divergence_operators.jl, src/Operators/laplacian_operators.jl, src/Solvers/fourier_tridiagonal_poisson_solver.jl, src/Solvers/solve_for_pressure.jl, test/test_distributed_poisson_solvers.jl, test/test_poisson_solvers.jl, test/test_preconditioned_conjugate_gradient_solver.jl, test/test_time_stepping.jl, test/utils_for_runtests.jl
This PR fixes a bug in the `FourierTridiagonalPoissonSolver` that almost certainly meant it produced incorrect answers. There were two concurrent bugs that cancelled each other out, which allowed tests to pass:
1. The Laplacian operator (previously called `∇²`, now called `∇²ᶜᶜᶜ`) was incorrect, because "Face" and "Center" superscripts were swapped. In other words, the Laplacian operator was correct for an object located at `(Face, Face, Face)`, rather than `(Center, Center, Center)` as it was being applied.
2. `ΔzF` and `ΔzC` were also swapped in derivation of the `FourierTridiagonalPoissonSolver`. This means that both the docs and the code were incorrect.
The tests passed because these two bugs effectively cancel each other out. This PR fixes both bugs. There still may be a lingering …
=> Fixes bug in FourierTridiagonalPoissonSolver that swapped `ΔzF` and `ΔzC`

.buildkite/pipeline.yml
It's quite useful for seeing how long is being spent on building each example (and which example is currently being built).
=> Use `JULIA_DEBUG: "Documenter"` when building docs

docs/make.jl, docs/src/simulation_tips.md
Closes https://github.com/CliMA/Oceananigans.jl/issues/1478
As mentioned in https://github.com/CliMA/Oceananigans.jl/issues/1542 I couldn't build the docs locally so I probably made some markdown mistakes along the way, which is why this is a draft pull request. This first draft is also somewhat incomplete.
I figured I'd create the PR early to get some feedback along the way though. I'm especially unfamiliar with the part about converting arrays to CUDA etc., so some help/collaboration there is much appreciated.
CC @ali-ramadhan @glwagner @navidcy @francispoulin
=> Includes simulation tips section in the docs

Project.toml, src/AbstractOperations/AbstractOperations.jl, src/Architectures.jl, src/Fields/abstract_field.jl, src/Fields/set!.jl, src/Oceananigans.jl, src/Solvers/Solvers.jl, src/TimeSteppers/TimeSteppers.jl, src/TurbulenceClosures/TurbulenceClosures.jl, src/Utils/versioninfo.jl, test/runtests.jl, test/test_checkpointer.jl, test/test_field.jl
The `@hascuda` macro used to be necessary but with the addition of `CUDA.has_cuda()` I don't think it is anymore.
So this PR finally gets rid of the `@hascuda` macro.
It's been a source of errors for users, especially when using Oceananigans on clusters where some nodes have GPUs and others do not. So hopefully this PR will help reduce errors for users on clusters.
=> Stop using `@hascuda` macro

src/AbstractOperations/show_abstract_operations.jl, src/Fields/reduced_field.jl, src/Operators/interpolation_utils.jl, test/test_abstract_operations_computed_field.jl, test/test_implicit_free_surface_solver.jl
This might resolve #1241 ...
cc @ali-ramadhan @tomchor
=> Defines many identity's to avoid recursion when compiling AbstractOperations

src/CubedSpheres/conformal_cubed_sphere_grid.jl, src/Operators/vorticity_operators.jl
Hmmm, do we also want to do this when running a simulation on a single face, i.e. with just one `ConformalCubedSphereFaceGrid`?
Resolves #1584
=> Compute vertical circulation at the cubed sphere corners

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/at.jl, src/AbstractOperations/binary_operations.jl, src/AbstractOperations/derivatives.jl, src/AbstractOperations/multiary_operations.jl, src/AbstractOperations/show_abstract_operations.jl, src/AbstractOperations/unary_operations.jl, src/Fields/abstract_field.jl, src/Fields/zero_field.jl, test/test_abstract_operations_computed_field.jl
This PR changes the structure of BinaryOperations and the way that locations are inferred when constructing them.
Before this PR, BinaryOperations stored three interpolation operators: two for each argument, and a third interpolation function applied after the binary operation was computed. The motivation for this design was to ensure that products of fields were always computed at their shared location, while allowing abstract operations to be built at user-specified locations. In other words, users might want something like
```julia
grid = RegularRectilinearGrid(size=(1, 1, 1), extent=(1, 1, 1))
model = IncompressibleModel(architecture=CPU(), grid=grid)
u, v, w = model.velocities
uu = @at (Center, Center, Center) u * u
BinaryOperation at (Center, Center, Center)
├── …
```
=> Improved and simplified BinaryOperation with "stubborn" location inference

Project.toml
Release notes:
* Tests and fixes for `FFTBasedPoissonSolver` for topologies with `Flat` dimensions (#1560)
* Improved `AbstractOperations` that are much more likely to compile on the GPU, with better "location inference" for `BinaryOperation` (#1595, #1599)
=> Bump to 0.55.0

benchmark/benchmark_hydrostatic_model.jl, src/CubedSpheres/cubed_sphere_faces.jl, src/CubedSpheres/cubed_sphere_halo_filling.jl, src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl, src/Models/Models.jl, src/Oceananigans.jl
Should run these benchmarks again once everything works on the GPU.
Notes:
1. Lat-lon grid seems slower than the single cubed sphere face, which is weird. Maybe the cost of computing the grid metrics on the fly is actually adding up to a significant overhead?
2. Cubed sphere grid performs better than it should (less than 6x slower than 1 face), but allocates a lot of memory.
3. Explicit vs. implicit free surface solver performance is problem-dependent so for the purposes of this benchmarks every implicit solver is forced to take 1 iteration.
```
Hydrostatic model benchmarks
┌───────────────┬──────────────────────────────┬─────────────────────┬───────────┬───────────┬───────────┬───────────┬────────────┬─────────┬─────────┐
│ Architectures │                   grid_types │ …
```
=> Hydrostatic model explicit vs. implicit free surface benchmarks + some small fixes

Project.toml, benchmark/benchmark_fourier_tridiagonal_poisson_solver.jl, benchmark/benchmark_vertically_stretched_incompressible_model.jl, src/Grids/regular_rectilinear_grid.jl, src/Grids/vertically_stretched_rectilinear_grid.jl, test/regression_tests/ocean_large_eddy_simulation_regression_test.jl, test/regression_tests/rayleigh_benard_regression_test.jl, test/regression_tests/thermal_bubble_regression_test.jl, test/test_diagnostics.jl, test/test_grids.jl, test/test_netcdf_output_writer.jl, test/test_poisson_solvers.jl, test/test_time_stepping.jl
Also adds `architecture` property and fixes `with_halo(new_halo, old_grid::VerticallyStretchedRectilinearGrid)`.
This is a major breaking change to the API for `VerticallyStretchedRectilinearGrid`.
Resolves #1605 .
Need to bump version before merging.
=> Changes zF to z_faces for VerticallyStretchedGrid

docs/src/simulation_tips.md
Just added a bit more info about `CuArrays` in the Simulation tips section
=> Added information about CuArrays

docs/src/numerical_implementation/spatial_operators.md
=> Adds missing `\cdot` in isotropic viscosity in Docs/Numerical Implementation/Spatial Operators

docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md, src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl, test/test_time_stepping.jl
Trying to use `AnisotropicMinimumDissipation` with `buoyancy = nothing` threw an error because it tries to access `buoyancy.model`, which doesn't exist when `buoyancy = nothing`.
This PR fixes that bug and adds a few tests for time-stepping AMD with different buoyancy models, including `buoyancy=nothing`. The bug is fixed by adding a new default `Cb = nothing` (rather than `Cb = 0.0`), in which case the computation of the buoyancy modification term is elided entirely. This might speed up some models (but who knows by how much).
It is _still_ the case that users who specify a non-default `Cb` without a buoyancy model receive error that could be hard to interpret. We could `validate_closure` for this. I feel it's not worth the effort right now though because the buoyancy modification term …
=> Fixes AnisotropicMinimumDissipation bug with `buoyancy=nothing`

src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl
Found while perusing the code with @kburns as we do.
=> Fix bug in `viscous_flux_vz` for `HorizontallyCurvilinearAnisotropicDiffusivity`

src/OutputWriters/fetch_output.jl, test/test_jld2_output_writer.jl
Resolves #1629 
TODO:
cc @tomchor
=> Support FieldSlicer for function output that returns AbstractField

src/CubedSpheres/cubed_sphere_faces.jl, src/CubedSpheres/cubed_sphere_set!.jl, test/test_cubed_spheres.jl
This PR fixes `set!` for `CubedSphereReducedField` for now which is used in the Rossby-Haurwitz validation experiment (and adds tests).
=> Fix `set!` for cubed sphere reduced fields

src/Fields/Fields.jl, src/Fields/reduced_field.jl, src/Fields/reduced_getindex_setindex.jl
Previously, `getindex` for `Nothing` locations was specified to `AbstractReducedField`. This PR extends these functions to apply to `AbstractDataField`.
The effect of this is limited because `Field`s are still entirely "unwrapped" within kernels, meaning that we lose their location data.
If/when we are able to preserve location data for `Field` when adapting to the `GPU`, we may not need `ReducedField` or `AbstractReducedField` any longer -- we can instead use `Nothing` locations to indicate that a field is reduced along a particular direction.
=> Extends `getindex` for `Nothing` locations to `AbstractField`

src/Fields/reduced_getindex_setindex.jl
Let us address technical debt.
=> Deletes needless comma in `getindex` for 0D fields

src/Grids/vertically_stretched_rectilinear_grid.jl, test/test_grids.jl
This PR uses a view into the underlying array of grid spacings rather than a view into the OffsetArray of grid spacings in `Base.show` for `VerticallyStretchedRectilinearGrid`. This should allow `maximum` and `minimum` to run without errors and allow `VerticallyStretchedRectilinearGrid` to be printed on the GPU.
Would be best to add a test, cc @navidcy
Closes #1637 .
=> Fixes show for VerticallyStretchedRectilinearGrid on GPUs

benchmark/benchmark_shallow_water_model.jl
Using `Flat` should be more efficient in terms of memory.
=> Using Flat for shallow water benchmark

Project.toml
Don't think we need it anymore and it's blocking the v0.58.0 tag: https://github.com/JuliaRegistries/General/pull/37071
=> No need for explicit dependence on ArrayInterface.jl anymore

src/Utils/Utils.jl, src/Utils/kernel_launching.jl, src/Utils/versioninfo.jl
This PR fixes
```
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
WARNING: using CUDA.instantiate in module Utils conflicts with an existing identifier.
```
=> Fix name conflict in `Utils`

src/Fields/show_fields.jl
Right now `show` errors since `ZeroField.grid` is not a struct property.
=> Add `show` method for `ZeroField`

test/test_implicit_free_surface_solver.jl
It seems to fail every so often, e.g. https://buildkite.com/clima/oceananigans/builds/2664#0bb7666d-6e02-4fad-9ff7-060ef7ec3c27/31-2086
=> Increase tolerance in implicit free surface solver tests

test/test_output_readers.jl
This tests also fails intermittently due to being slightly above the tight tolerance: https://buildkite.com/clima/oceananigans/builds/2660#fdbc1bf9-350b-4051-9977-5ec4683ca080/22-534
=> Increase tolerance on `FieldTimeSeries` reduction tests

test/test_implicit_free_surface_solver.jl
It's still failing intermittently after increasing the tolerance in PR #1686: https://buildkite.com/clima/oceananigans/builds/2672#74321ab5-528f-48c2-bd0c-5ab006881fd3/22-2077
=> Further increase tolerance in implicit free surface solver tests

Project.toml, src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_biharmonic_diffusivity.jl
Resolves #1702 noticed by @mukund-gupta .
In a [previous PR](https://github.com/CliMA/Oceananigans.jl/commit/3afd5b59fce91f9ab4aa6d0d19cd64fef7aea4cf#) we changed the notation of the closure term to indicate that it's the divergence of a flux, rather than specifically the divergence of a _viscous_ or _diffusive_ flux. This notational change required us to change the term's sign. Specifically, we used the redefinition
```
∂ⱼ_2ν_Σ₁ⱼ = - ∂ⱼ_τ₁ⱼ
```
for the diffusive flux of x-momentum.
However, we did not change the sign of the flux divergence for `AnisotropicBiharmonicDiffusivity`; we only changed the _name_ of the term. This PR corrects the sign error.
There are a few closures that don't have regression tests and this highlights the danger of that.
=> Fixes sign error in flux divergence of `AnisotropicBiharmonicDiffusivity`

docs/src/contributing.md
This PR updates the instructions for building docs locally. We should avoid `Pkg.develop()` since we are offering a `docs/Manifest.toml`.
=> Update instructions for building docs

src/ImmersedBoundaries/ImmersedBoundaries.jl, src/Models/ShallowWaterModels/shallow_water_advection_operators.jl, src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl, src/Models/ShallowWaterModels/update_shallow_water_state.jl, test/test_shallow_water_models.jl
This PR updates the grid metrics used by `ShallowWaterModel` and adds a masking step to `update_state!` so that `ShallowWaterModel`s can be run on `ImmersedBoundaryGrid`.
Co-authored by @francispoulin .
Supercedes #1663
=> Try 2: ShallowWaterModel with ImmersedBoundaryGrid

docs/oceananigans.bib, docs/src/model_setup/overview.md, src/Models/Models.jl, src/Models/ShallowWaterModels/shallow_water_model.jl, src/Oceananigans.jl
This PR adds docstring to `ShallowWaterModel` and also includes all models in Model setup/Overview.
Closes #1708 and closes #1709.
=> `ShallowWaterModel` API documentation + Add all models in Model setup/Overview

src/Advection/centered_advective_fluxes.jl, src/Advection/centered_second_order.jl, src/Advection/momentum_advection_operators.jl, src/Advection/topologically_conditional_interpolation.jl, src/Advection/upwind_biased_advective_fluxes.jl, src/ImmersedBoundaries/ImmersedBoundaries.jl, src/ImmersedBoundaries/grid_fitted_immersed_boundary.jl, src/Models/ShallowWaterModels/shallow_water_advection_operators.jl
High-order advection schemes invoke wide stencils that can produce unintended non-zero fluxes across solid immersed boundaries. This PR elides advective fluxes across immersed boundaries for `GridFittedImmersedBoundary` to address that.
In addition, we should probably introduce boundary-conditional interpolation so that we limit to second-order advection close to immersed boundaries. I'll drop that into this PR too and add a test for high-order advection with immersed boundaries.
=> New features for high-order advection in the presence of immersed boundaries

docs/src/physics/hydrostatic_free_surface_model.md
The tracer advection in the `HydrostaticFreeSurfaceModel` is done by 3D velocity (u, v, w) and not by 2D (u, v, 0).
Closes #1728.
=> Fixes typo in Docs/Physics/HydrostaticFreeSurfaceModel

src/CubedSpheres/CubedSpheres.jl, src/CubedSpheres/cubed_sphere_faces.jl, src/CubedSpheres/immersed_conformal_cubed_sphere_grid.jl, src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl, validation/immersed_boundaries/animate_on_map_projection.jl, validation/immersed_boundaries/animate_three_spheres.jl, validation/immersed_boundaries/cubed_sphere_rossby_haurwitz.jl, validation/immersed_boundaries/immersed_cubed_sphere_rossby_haurwitz.jl
This PR adds a set of changes so that needed dispatch paths for CubedSphereGrid are followed when CubedSphereFaceGrid tuple is wrapped in an ImmersedBoundary type. 
With these changes the https://github.com/CliMA/Oceananigans.jl/blob/cnh-glw/immersed-cubed-sphere/validation/immersed_boundaries/immersed_cubed_sphere_rossby_haurwitz.jl code works identically for non-immersed and immersed cube sphere.
=> Make Immersed work with cubed sphere

docs/src/model_setup/buoyancy_and_equation_of_state.md, src/BuoyancyModels/linear_equation_of_state.jl
Changed units for haline contraction coefficients to match what's listed in table 1.2 of Vallis (from ppt to psu).
=> Changed units in docstring for linear eq of state

Project.toml, src/Grids/regular_rectilinear_grid.jl, src/Grids/vertically_stretched_rectilinear_grid.jl, src/TurbulenceClosures/turbulence_closure_diagnostics.jl, src/Utils/cell_advection_timescale.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/1749
Apparently there are currently two ways to get minimum spacing from a grid, and they work a bit differently from each other, which is causing some problems with `VerticallyStretchedGrids`.
Option 1. This way works with `VerticallyStretchedGrids` and `RegularGrids`, whre each type of grid defines these separately.
```julia
Δx = min_Δx(grid)
Δy = min_Δy(grid)
Δz = min_Δz(grid) 
```
Option 2: I suspect this was added recently (idk when or which commit) and it appears to be an ad-hoc way of dealing with flat dimensions.
```julia 
Δx = minimum_grid_spacing(grid.Δx, topo[1])
Δy = minimum_grid_spacing(grid.Δy, topo[2])
Δz = minimum_grid_spacing(grid.Δz, topo[3])
```
I'm including both ways in my first commit (which solves an issue for …
=> Unifying approaches for `min_Δxyz`

Project.toml, src/Grids/vertically_stretched_rectilinear_grid.jl
These lines should not be there and at the least lower the accuracy of calculations on stretched grids.
We need tests that the metrics and grid geometry are correct for stretched grids (eg all the cell spacings added up gives the total domain size; cell centers are located halfway between cell interfaces, etc). 
Not sure why these lines are there but it may have been necessary due to a serious bug with the vertically stretched Poisson solver that was fixed in https://github.com/CliMA/Oceananigans.jl/pull/1541. I'm not sure.
=> Removes manual grid manipulation in VerticallyStretchedRectilinearGrid constructor

validation/advection/plot_rates_convergence_advection.jl
The current version is broken and does not compute the correct exponents.
The corrected version fixes this problem.
=> Fixing array incides to compute the correct rates of convergence

src/Grids/vertically_stretched_rectilinear_grid.jl, test/test_simulations.jl
Using `min_Δz(grid::VerticallyStretchedRectilinearGrid)` on GPU fails. The reason is that
```julia
julia> minimum(view(grid.Δzᵃᵃᶜ, 1:grid.Nz))
ERROR: scalar getindex is disallowed
```
fails on the GPU. The line should be `minimum(view(parent(grid.Δzᵃᵃᶜ), 1:grid.Nz))`.
This error had been there all along but I guess no one caught it. This commit should fix it, but should we also include a test that would catch it?
=> Correct min_Δz for VerticallyStretchedGrids

docs/src/numerical_implementation/spatial_operators.md, docs/src/physics/notation.md
E.g., a
<p><code>```math
...
```</code></p>
environment was missing. Also some deprecated notation `G_T` was removed...
=> Fix typo in Docs/Spatial Operators

docs/src/simulation_tips.md
First attempt at this. Still wasn't able to make sure the code in the example works.
In fact, so far it has failed:
```julia
julia> using Oceananigans.Operators
julia> using Oceananigans.Grids
julia> function isotropic_viscous_dissipation_rate_ccc(i, j, k, grid, u, v, w, ν)
Σˣˣ² = ∂xᶜᵃᵃ(i, j, k, grid, u)^2
Σʸʸ² = ∂yᵃᶜᵃ(i, j, k, grid, v)^2
Σᶻᶻ² = ∂zᵃᵃᶜ(i, j, k, grid, w)^2
Σˣʸ² = ℑxyᶜᶜᵃ(i, j, k, grid, fψ_plus_gφ², ∂yᵃᶠᵃ, u, ∂xᶠᵃᵃ, v) / 4
Σˣᶻ² = ℑxzᶜᵃᶜ(i, j, k, grid, fψ_plus_gφ², ∂zᵃᵃᶠ, u, ∂xᶠᵃᵃ, w) / 4
Σʸᶻ² = ℑyzᵃᶜᶜ(i, j, k, grid, fψ_plus_gφ², ∂zᵃᵃᶠ, v, ∂yᵃᶠᵃ, w) / 4
ϵ[i, j, k] = ν[i, j, k] * 2 * (Σˣˣ² + Σʸʸ² + Σᶻᶻ² + 2 * (Σˣʸ² + Σˣᶻ² + Σʸᶻ²))
end
isotropic_viscous_dissipation_rate_ccc (generic function with 1 method)
julia> ε = KernelFunctionOperation(Center, Center, Center, …
```
=> Move simulation tips from using KernelComputedFields to KernelFunctionOperation

CONTRIBUTING.md, docs/src/contributing.md
This PR adds a few sections to `CONTRIBUTING.md` with guidelines for opening an issue, and for becoming an Oceananigans collaborator.
=> Expands contributor guidelines

docs/src/model_setup/grids.md
I think we formally support Flat topologies now, so we should at least mention them in the page that teaches users about the  grids. So I added a couple of simple sentences. I don't think we need much more for now (especially since all the 2D examples now use `Flat`).
=> Include Flat topologies when talking about the grids in the docs

benchmark/benchmark_abstract_operations.jl, benchmark/benchmark_incompressible_model.jl, benchmark/benchmark_vertically_stretched_incompressible_model.jl, benchmark/benchmarkable_incompressible_model.jl, src/Models/IncompressibleModels/incompressible_model.jl, src/Models/IncompressibleModels/non_dimensional_model.jl, test/test_boundary_conditions_integration.jl, test/test_diagnostics.jl, test/test_incompressible_models.jl, test/test_time_stepping.jl, test/test_turbulence_closures.jl
The floating point type can and should be determined from `eltype(grid)`, since `grid` is a required argument for constructing `IncompressibleModel`. An independent `float_type` argument is not only redundant but creates the possibility that models can have inconsistent float types. Eliminating this argument and using `eltype(grid)` as the source of knowledge re: floating point types solves this problem.
=> Nuke float_type arg for IncompressibleModel

Project.toml, src/Advection/weno_fifth_order.jl
"2... 32... hut, hut... !"
No idea if this resolves #1764 but perhaps.
Why? Because CUDA replaces `Int64` with `Float64` when exponentiating:
https://github.com/JuliaGPU/CUDA.jl/blob/5d6127dbbef495c94d3dd8de98162188062e11b1/src/device/intrinsics/math.jl#L218-L224
(If I'm understanding that code correctly.)
For `Int32` it calls CUDA function that's specific to integer exponents.
Hmm!
=> Exponentiate with Int32 not Int64

.buildkite/pipeline.yml, Manifest.toml, test/test_simulations.jl
Resolves #1794 .
We should also come up with a more permanent solution (perhaps another environment variable to toggle GPU-CI) that throws an error if GPU tests can't run on the GPU.
=> Don't set `JULIA_CUDA_USE_BINARYBUILDER`; up to CUDA@3.3.1

test/data_dependencies.jl
Sometimes different Buildkite jobs try to download the same file as the same time leading to freezes like in https://buildkite.com/clima/oceananigans/builds/3066#157d0809-a11d-476b-b78d-fc5b1a241286
This PR tries to avoid race conditions by just downloading the file once during the initialization stage.
Doesn't always happen though so not sure when/how to merge.
=> Avoid data dep race condition in CI

examples/ocean_wind_mixing_and_convection.jl, src/Grids/regular_rectilinear_grid.jl, src/Grids/vertically_stretched_rectilinear_grid.jl
This PR updates `examples/ocean_wind_mixing_and_convection.jl` with a new grid generating function that produces a constant grid spacing near the surface. A visualization of the grid spacing is
@tomchor proposed this idea in #1762, but we couldn't find a suitable generating function and so a grid that becomes ever more refined toward the surface was used instead. I think a grid with constant near-surface spacing and bottom-intensified stretching will be useful for boundary layer turbulence experiments, so I thought it was worthwhile to spend a bit more time to come up with something.
I thought the hyperbolic generating function was also useful, so I added it to the docstring for `VerticallyStretchedRectilinearGrid` as an example. This PR also fixes a typo in that docstring.
Some notes:
I …
=> Use constant near-surface grid spacing in ocean wind mixing and convection example + fixes some docstrings

docs/Manifest.toml, docs/Project.toml, docs/make.jl, docs/src/contributing.md
This PR removes temporary `.nc` and `.jld2` files that are created by Doctests when building the Docs.
=> Cleanup of doctest files after building docs

src/Advection/Advection.jl, src/Advection/momentum_advection_operators.jl, src/Advection/tracer_advection_operators.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_advection.jl, src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl
Use latex rendering for divergence of momentum/tracers. Now the total flow U -> 𝐯, consistent with [notation convention](https://clima.github.io/OceananigansDocumentation/dev/physics/notation/).
I was also tempted to rename the functions, e.g., `div_Uv`  to `div_𝐯u` for consistency. Shall we?
Also, does a bit of a cleanup. (Closes #1841.)
=> Better momentum/tracer advection docstrings and function names

src/Advection/centered_advective_fluxes.jl, src/Advection/momentum_advection_operators.jl, src/Advection/topologically_conditional_interpolation.jl, src/Advection/upwind_biased_advective_fluxes.jl, src/Grids/Grids.jl, src/ImmersedBoundaries/ImmersedBoundaries.jl, src/TurbulenceClosures/TurbulenceClosures.jl, src/TurbulenceClosures/abstract_isotropic_diffusivity_closure.jl, src/TurbulenceClosures/implicit_explicit_time_discretization.jl, src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/tke_based_vertical_diffusivity.jl, test/test_dynamics.jl, test/test_time_stepping.jl
Previously the functions viscous_flux_u* and diffusive_flux_* dispatched on AbstractPrimaryGrid. AbstractPrimaryGrid (now called AbstractUnderlyingGrid is an abstract type for distinguishing between ImmersedBoundaryGrid and the "primitive" / "primary" / "underlying" counterparts (I guess I'm still not sure what the best name is).
As a result, flux calculations with ImmersedBoundaryGrid were hitting fallback flux functions that returned 0.
This PR removes most instances dispatching on grid (except where necessary, where the dispatched type was changed from AbstractPrimaryGrid to AbstractGrid). It also nukes the fallbacks (which were the reason this issue escaped detection originally).
This PR also adds a minimal test that _vertical_ diffusive and viscous fluxes work. It does not test the …
=> Allow non-zero diffusive and viscous fluxes with ImmersedBoundaryGrid

Project.toml
Release notes:
* Fixes a major bug with `ImmersedBoundaryGrid` that elided all viscous fluxes
=> Bump to 0.58.9

src/Fields/background_fields.jl, test/test_incompressible_models.jl
Resolves #1831
As suggested by @glwagner , this allows us to set a background field with a `Field`.
=> Allow a background_field to be a Field

examples/kelvin_helmholtz_instability.jl
This PR changes `\real` -> `\mathrm{Re}` since `\real` is not a command recognised in MathJax3.
=> Fix LaTeX rendering bug in Kelvin Helmoltz instability example

Project.toml, src/Operators/spacings_and_areas_and_volumes.jl, src/Solvers/discrete_transforms.jl, src/Solvers/fft_based_poisson_solver.jl, src/Solvers/fourier_tridiagonal_poisson_solver.jl, src/Solvers/plan_transforms.jl, test/test_distributed_models.jl, test/test_dynamics.jl, test/test_internal_wave_dynamics.jl, test/test_poisson_solvers.jl
This PR implements seven new internal wave dynamics tests that run for both `IncompressibleModel` and `HydrostaticFreeSurfaceModel`, on vertically-stretched grids, and on `Flat` topologies for both models and both regular and stretched grids.
The tests show that `VerticallyStretchedRectilinearGrid` does not work with `Flat` dimensions.
For `IncompressibleModel`, this usage produces a warning that "`FourierTridiagonalPoissonSolver` is probably not correct." Ironically, it's this warning thats _probably_ not correct: the issue with `Flat` and vertically-stretched grids appears to lie in the lack of flat grid metrics for any grid but `RegularRectilinearGrid` --- not the Poisson solver.
We can fix this problem in this PR. In that case it will resolve #1849.
=> Flat VerticallyStretchedRectilinearGrid plus new hydrostatic and flat internal wave tests

docs/src/simulation_tips.md
[Previously referenced issue](https://github.com/CliMA/Oceananigans.jl/issues/1241) is now closed and I'm replacing it by the [newly-created one](https://github.com/CliMA/Oceananigans.jl/issues/1886), which summarizes everything.
@glwagner
=> Update issue referenced in `simulation_tips.md`

src/BoundaryConditions/boundary_condition.jl, src/BoundaryConditions/discrete_boundary_function.jl, src/CubedSpheres/CubedSpheres.jl, src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl, src/TurbulenceClosures/turbulence_closure_implementations/tke_based_vertical_diffusivity.jl
This PR reformulates TKEBasedVerticalDiffusivity simply through a redefinition of parameters.
It also makes a more important change to the code that passes `model.closure` and `model.buoyancy` to the kernels that evaluate boundary fluxes. This is necessary to make `TKEBasedVerticalDiffusivity` models robust against changes to parameters after model construction. The changes are made in a way that have no affect on the API or other models.
Resolves #1695 .
cc @adelinehillier
=> Reformulates TKEBasedVerticalDiffusivity

src/Oceananigans.jl, src/Simulations/Simulations.jl, src/Simulations/callback.jl, src/Simulations/run.jl, src/Simulations/simulation.jl
This PR implements `Callback`, designed to be used with `Simulation`.
Illustration:
```julia
model = NonhydrostaticModel(grid = RegularRectilinearGrid(size=(128, 128), extent=(2π, 2π), topology=(Periodic, Periodic, Flat)),
timestepper = :RungeKutta3,
advection = UpwindBiasedFifthOrder(),
buoyancy = nothing,
tracers = nothing)
set!(model, u = (x, y, z) -> randn(), v = (x, y, z) -> randn())
simulation = Simulation(model, Δt=0.01, stop_iteration=100)
print_progress(sim) = @info "Iteration: $(sim.model.clock.iteration), time: $(sim.model.clock.time)"
simulation.callbacks[:progress] = Callback(print_progress, schedule=IterationInterval(10))
run!(simulation)
```
we get
```julia
julia> run!(simulation)
[ Info: Iteration: 0, time: 0.0
[ Info: Iteration: 10, time: …
```
=> Introducing Callback for Simulations

docs/make.jl, docs/src/numerical_implementation/poisson_solvers.md, docs/src/numerical_implementation/spatial_operators.md
This PR change the order of pages in the Docs/Numerical Implementation section. It starts with "Finite volume method" and "Spatial operators" and then goes on with everything else.
Also fixes some loose ends in formatting. ;)
=> Change order in Docs/Numerical Implementations

docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md, docs/src/physics/turbulence_closures.md, examples/ocean_wind_mixing_and_convection.jl, src/Oceananigans.jl, src/TurbulenceClosures/TurbulenceClosures.jl, src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl, test/test_regression.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/1907
=> Update Smagorinsky-Lilly model

src/TimeSteppers/quasi_adams_bashforth_2.jl
It was just a little sketchy: we shouldn't derive the "floating point type" from a potentially user-supplied parameter (which might accidentally be an integer, like `0`). It also had weird formatting so I fixed that too.
=> Make ab2_step_field! a bit less sketchy

.gitignore, src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl, src/Models/HydrostaticFreeSurfaceModels/rigid_lid.jl, src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl, src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl, src/TimeSteppers/quasi_adams_bashforth_2.jl, src/TimeSteppers/runge_kutta_3.jl, src/TurbulenceClosures/closure_tuples.jl, src/TurbulenceClosures/turbulence_closure_implementations/tke_based_vertical_diffusivity.jl, src/Utils/kernel_launching.jl, validation/vertical_mixing_closures/Manifest.toml, validation/vertical_mixing_closures/Project.toml, validation/vertical_mixing_closures/gpu_tkevd_ensemble.jl, validation/vertical_mixing_closures/many_tke_based_free_convection.jl, validation/vertical_mixing_closures/profile_tke_based_vertical_diffusivity.jl, validation/vertical_mixing_closures/profile_tkevd_ensemble.jl, validation/vertical_mixing_closures/tke_based_free_convection.jl
This PR makes some changes to the `HydrostaticFreeSurfaceModel` to permit the simulation of an "ensemble of columns". This abstraction uses a `Flat, Flat, Bounded` topology but non-zero resolution in `x, y`, leading to a model of `Nx, Ny` independent, non-communicating columns. In addition, we support using a 2D array of turbulence closures with this "column ensemble" abstraction (but only with this abstraction, not generally, to hopefully minimize unexpected behavior) so that each column can simulate a different surface boundary condition and parameterization independently. An example of usage is implemented in `validation/vertical_mixing_closures/many_tke_based_free_convection.jl` and `validation/vertical_mixing_closures/gpu_tkevd_ensemble.jl`.
The result is a model that can simulate …
=> SingleColumn enhancements and "ensemble of columns" abstraction

src/BoundaryConditions/continuous_boundary_function.jl, src/Forcings/continuous_forcing.jl, test/runtests.jl, test/test_hydrostatic_free_surface_immersed_boundaries_apply_surf_bc.jl
This test is to stop the error below from reappearing (once the test is fixed!). 
```
nested task error: MethodError: no method matching (::Oceananigans.BoundaryConditions.ContinuousBoundaryFunction{Face, Center, Nothing, 1, var"#surface_wind_stress#28", NamedTuple{(:τ₀, :Lφ, :φ₀), Tuple{Float64, Float64, Int64}}, Tuple{}, Tuple{}, Tuple{}})(::Int64, ::Int64, ::ImmersedBoundaryGrid{Float64, Bounded, Bounded, Bounded, RegularLatitudeLongitudeGrid{Float64, Bounded, Bounded, Bounded, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}}, GridFittedBoundary{RasterDepthMask, var"#raster_depth#27"}}, ::Clock{Float64}, ::NamedTuple{(:u, :v, :η), Tuple{Field{Face, Center, Center, CPU, OffsetArray{Float64, 3, Array{Float64, 3}}, …
```
=> Add a test to check surface bc continuous functions work with ImmersedBoundary

examples/convecting_plankton.jl
The named tuple that contains parameters in named `p` in a couple of functions in the [convecting plankton example](https://github.com/CliMA/Oceananigans.jl/blob/b15d2d0e7204e66a74e51e9ed2a0f2214315b62a/examples/convecting_plankton.jl#L102). I think this is unnecessarily confusing since the plankton concentration `P` appears in the same lines. This fixes that.
=> Changes parameters name from p to params

Project.toml, src/Models/HydrostaticFreeSurfaceModels/compute_w_from_continuity.jl
Simple fix to use the cell-centered vertical spacing (face-to-face distance) in the continuity equation for determining w in the hydrostatic model.  The code currently uses the face-centered spacing (center-to-center distance), which is the same for the uniform grid but not for the vertically stretched grid.  With help from @sandreza and @jm-c.
=> Fix bug in hydrostatic vertical velocity with stretched grid

src/Operators/derivative_operators.jl
This PR "unrestricts" (removes type annotations) from second and fourth derivative operators.
These annotations are unnecessary, since the second and fourth derivative operators call first-derivative operators that perform appropriate dispatch. Also, the second vertical derivative operators are general (within the scope of current Oceananigans code) and should not be restricted.
@jm-c does this fix your problem?
=> Unrestrict second and fourth derivative operators for use with `ImmersedBoundaryGrid`

Project.toml, src/TurbulenceClosures/diffusion_operators.jl, validation/immersed_boundaries/immersed_tracer_1D.jl
This PR fixes the diffusive flux argument in the divergence of diffusive flux, `∇_dot_qᶜ`,
https://github.com/CliMA/Oceananigans.jl/blob/e929631eb3a233ae3f3358d2146e5d6004f9a06c/src/TurbulenceClosures/diffusion_operators.jl#L47  to allow for the immersed boundary version using `_diffusive_flux_x`. This will make the tracer equations feel the immersed boundaries correctly. This also adds a very small 1D validation to test this. With a uniform buoyancy, validation checks if the buoyancy changes in time (it shouldn't). Below are the results before and after the fix. We can, of course, not include the validation and instead add a test for this.
=> Fix diffusive flux bug for immersed boundaries

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/kernel_function_operation.jl, src/Oceananigans.jl
`KernelFunctionOperation` wasn't being exported, so this PR fixes it.
I also moved the docstring to the struct because it was being recognized before. Let me know if this isn't the best solution to this. Before
```julia
help?> Oceananigans.AbstractOperations.KernelFunctionOperation
No documentation found.
Oceananigans.AbstractOperations.KernelFunctionOperation is of type UnionAll.
Summary
≡≡≡≡≡≡≡≡≡
struct UnionAll <: Type{T}
Fields
≡≡≡≡≡≡≡≡
var  :: TypeVar
body :: Any
Supertype Hierarchy
≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
UnionAll <: Type{T} <: Any
```
Now:
```julia
help?> KernelFunctionOperation
search: KernelFunctionOperation
KernelFunctionOperation{LX, LY, LZ}(kernel_function, grid; architecture=nothing,
computed_dependencies=(), parameters=nothing)
Constructs a KernelFunctionOperation at location …
```
=> Exports KernelFunctionOperation

docs/src/appendix/library.md
I noticed some pages listed in library.mb didn't quite match the pages that are currently in `src`, mist notably (for me) `kernel_function_operation.jl`, so  updated it. There probably are more discrepancies, but I also think we don't wanna list some of the more experimental features, so I left the rest as it was.
=> Update library.md with KernelFunctionOperation

src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_lateral_areas.jl
This changes the threading structure in a kernel launch to only launch over the i,j indices to avoid race conditions
=> Adds a small bugfix to calculation in HydrostaticModel

src/TimeSteppers/clock.jl
Think this should be 
```
`time::T` can be either a number or a `DateTime` object" 
```
?
=> time::T number OR DateTime object

src/Fields/broadcasting_abstract_fields.jl, test/test_abstract_operations.jl, test/test_broadcasting.jl, test/test_computed_field.jl
This adds a test that should fail; but we should be able to fix it by defining 
```julia
@inline Base.Broadcast.materialize!(dest::AbstractField, bc::Broadcasted{<:DefaultArrayStyle}) =
Base.Broadcast.materialize!(interior(dest), bc)
```
=> Adds a test for broadcasting fields with arrays with singleton dimensions

Project.toml
Forgot to bump after #1926, which is breaking because it changes `TKEBasedVerticalDiffusivity` to `CATKEVerticalDiffusivity`.
=> Bump to 0.62.0

src/ImmersedBoundaries/mask_immersed_field.jl
This optional positional argument can be used to mask a field with a value other than 0.
The syntax is supposed to be
```julia
mask_immersed_field!(c, NaN)
```
to mask a field to `NaN`, for example.
cc @francispoulin @fadaie91
=> Adds optional second argument `value` to `mask_immersed_field!`

Project.toml, src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
This PR changes the criterion for a "stable" layer from `dbdz > 0` to `dbdz >= 0`.
Resolves #1980 .
=> Neutral boundary layers are not unstable

Manifest.toml, Project.toml
Closes #1995 and closes #1996
(I'm not sure when the bug was introduced, so I capped the version up to 3.3.6. Feel free to change if there's a newer version that's also safe.)
Also we need to remember to remove this after the bug gets put into a tagged release. (Can we exclude only version 3.4.2 using compat?)
=> Introduces range of acceptable CUDA packages to avoid bug in 3.4.2

Project.toml, src/Grids/Grids.jl, test/test_grids.jl
For some reason when I tested the code after merging https://github.com/CliMA/Oceananigans.jl/pull/2028 it didn't really work on my main code for GPUs. 
It worked for a MWE when I tested it [here](https://github.com/CliMA/Oceananigans.jl/pull/2028#issuecomment-952089949) but I guess I must have done something wrong? In any case, I apologize!
I also expanded the test to test grids on GPUs (which would have caught this error) so I think this'll help.
Given that we _just_ released a new version, I didn't bump this to 0.63.4 here. But let me know if I should do that.
CC: @navidcy
=> Fixes grid equality for GPUs

docs/src/simulation_tips.md
Updating this with some info I just found out: trigonometric functions are super slow on GPUs.
I should say, I couldn't find anything mentioning this issue online. So if you anyone thinks this is a bug of some sort, let me know and I'll open an issue.
=> Updates simulation tips

docs/Manifest.toml, docs/Project.toml
At the moment it was there but never used. So only wasting time by installing and precompiling when building the docs.
=> Remove GLMakie from `docs/Project.toml`

src/CubedSpheres/CubedSpheres.jl
`Oceananigans.Diagnostics.error_if_nan_in_field` was moved to `Oceananigans.Simulations` (after #2048).
Closes #2068.
=> Update `Oceananigans.CubedSpheres` to correctly import `error_if_nan_in_field`

docs/src/model_setup/grids.md, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl
This PR fixes the alignment issue in `show(io, ::AbstractGrid)`.
Partially addresses #2064.
=> Better `show(io, ::AbstractGrid)`

docs/src/appendix/library.md, src/Advection/centered_fourth_order.jl, src/Advection/centered_second_order.jl, src/Advection/upwind_biased_fifth_order.jl, src/Advection/upwind_biased_first_order.jl, src/Advection/upwind_biased_third_order.jl, src/Advection/weno_fifth_order.jl, src/BoundaryConditions/boundary_condition_classifications.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/Fields/computed_field.jl, src/Forcings/continuous_forcing.jl, src/ImmersedBoundaries/ImmersedBoundaries.jl, src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_volume_flux.jl, src/Models/HydrostaticFreeSurfaceModels/compute_w_from_continuity.jl, src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl, src/Models/NonhydrostaticModels/NonhydrostaticModels.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl, src/Models/ShallowWaterModels/ShallowWaterModels.jl, src/Models/ShallowWaterModels/shallow_water_model.jl, src/Oceananigans.jl, src/Operators/spacings_and_areas_and_volumes.jl, src/OutputWriters/jld2_output_writer.jl, src/Simulations/run.jl, src/StokesDrift.jl, src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl, src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl
This PR simplifies the Docs/Appandix/Library and also adds missing modules in it. 
Furthermore, it enhances formatting in several docstrings and converts some examples to doctests.
Closes  #2080.
For example, regarding 2 vs 4 spaces in markdown formatting,
**before this PR**
while **after this PR**
=> Enhance docstrings + add models & modules in Docs/Appendix/Library

src/Distributed/distributed_fft_based_poisson_solver.jl, test/test_distributed_poisson_solvers.jl
eigenvaluies correctly distributes
partially resolves #2074 (`Nx` can be different than `Ny`)
=> small bug fix in Distributed Poisson Solver

src/Advection/weno_fifth_order.jl
Seems that "\n" cannot be part of regular expressions for doctest filters. Otherwise, something goes wrong with the parsing and
```
DocTestFilters = [Regex(".*┌ Warning.*
"), Regex(".*└ @ Oceananigans.*
")]
```
appears in the docstring.
Compare 
https://clima.github.io/OceananigansDocumentation/dev/appendix/library/#Oceananigans.Advection.WENO5
to
https://clima.github.io/OceananigansDocumentation/previews/PR2083/appendix/library/#Oceananigans.Advection.WENO5
=> Fix WENO5 doctest

src/AbstractOperations/AbstractOperations.jl, src/AbstractOperations/binary_operations.jl, src/AbstractOperations/derivatives.jl, src/AbstractOperations/multiary_operations.jl, src/AbstractOperations/unary_operations.jl, src/BuoyancyModels/buoyancy_field.jl, src/Fields/function_field.jl, src/Fields/reduced_field.jl, src/TimeSteppers/clock.jl, src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl
Inner constructor docstrings need to be preceded by `@doc`.
=> More docstrings

Project.toml, src/Simulations/run.jl, src/Simulations/simulation.jl
I believe we have a mismatch with `wall_time_limit` since `sim.run_wall_time` measures it in nanoseconds and `sim.wall_time_limit` measures it in seconds:
```julia
julia> grid = RectilinearGrid(size=(1, 1, 1), extent=(1, 1, 1));
julia> model = NonhydrostaticModel(grid=grid)
NonhydrostaticModel{CPU, Float64}(time = 0 seconds, iteration = 0) 
├── grid: RectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
├── tracers: (:T, :S)
├── closure: Nothing
├── buoyancy: SeawaterBuoyancy{Float64, LinearEquationOfState{Float64}, Nothing, Nothing}
└── coriolis: Nothing
julia> simulation = Simulation(model, Δt=1, wall_time_limit=10minute)
Simulation{typename(NonhydrostaticModel){typename(CPU), Float64}}
├── Model clock: time = 0 seconds, iteration = 0
├── Next time step: 1 second
├── …
```
=> Stores `run_wall_time` in seconds and fixes bug

src/BoundaryConditions/field_boundary_conditions.jl
This is a (somewhat minor) convenience for parameter studies, because it means that if `u` was constructed with
```julia
u_boundary_conditions = FieldBoundaryConditions(top = FluxBoundaryCondition(1.0))
```
we can later write things like
```julia
u.boundary_conditions.top = FluxBoundaryCondition(2.0)
```
to change the value of the boundary condition. Note that the _type_ of the boundary condition can't change. 
Just opening this PR to see if tests pass with this change. If so it seem positive to me (I don't think `FieldBoundaryConditions` needs to be immutable for performance reasons, but please speak up if anyone thinks/knows otherwise).
=> Makes FieldBoundaryConditions mutable

src/Grids/conformal_cubed_sphere_face_grid.jl, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl
This PR adds a new constructor for `RectilinearGrid` that looks something like
```julia
grid = RectilinearGrid(Float64, size = (1, 1, 1), ...)
```
that defaults to `architecture = CPU()`.
This avoids the error observed on #2103. Since users _rarely_ change the floating point type, this alternative constructor probably won't be used all that much. So it's not crucial, but might help a few people.
If others (@navidcy, @simone-silvestri ?) think this is a good idea, I'll add the same for other grid constructors.
If we don't merge this PR, we should probably still validate the positional inputs to grid constructors to make sure they are valid (eg `architecture` needs to be `AbstractArchitecture`, etc).
=> Quality-of-life improvement for grid constructors

src/Simulations/time_step_wizard.jl
The minimum CFL for `QuasiAdamsBashforthTimeStepper` is 0.2, not 0.1. Also, `max_change=2.0` often causes the time-step to change too quickly and leads to NaNs. `max_change=1.1` is a better default.
=> More useful defaults for `TimeStepWizard`

Project.toml
Notably we don't have a version that captures #2078.
=> Bump to 0.67.0

src/Grids/Grids.jl, src/Grids/grid_utils.jl
=> Remove `length(::AbstractGrid)` and tidies up grid-related utility functions

test/dependencies_for_runtests.jl, test/runtests.jl
This lets me do 
export TEST_GROUP="none"
export TEST_FILE="test_matrix_poisson_solver.jl"
so I don't have to edit runtest to try a single file test.
Not sure if its good idea???
=> Add possible option to test with one file

src/Grids/grid_generation.jl, test/test_grids.jl
At the moment 
`ΔF[i-1] = C[i] - C[i-1]` where `C` and `F` are the center and face coordinate, respectively. On the other hand, the derivative on the face `[i]` is calculated with `(c[i] - c[i-1]) / ΔF[i]` (where `c` is the value of the derived variable at the centers)
therefore, it has to be that `ΔF[i] = C[i] - C[i-1]`
Because of how we test, this bug was miraculously eluding all testing
=> Bug fix in stretched grid!

.buildkite/pipeline.yml, test/runtests.jl, test/test_hydrostatic_regression.jl, test/test_nonhydrostatic_regression.jl
This is a second take on #2140. Closes #2139.
=> Split tests into smaller bits and pieces (take #2)

examples/shallow_water_Bickley_jet.jl
I believe there were two superfluous lines in the Shallow water example there were leftover from an earlier version. I removed these lines.
=> Cleans `examples/shallow_water_Bickley_jet.jl`

Project.toml, src/Grids/conformal_cubed_sphere_face_grid.jl, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl, src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl, src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
PR #2121 changed some function signatures, which broke functionality provided by `single_column_model_mode.jl` that sets `model.free_surface = nothing`. This PR restores that functionality.
I think we could add a test, but the experimental nature of `single_column_model_mode.jl` could also mean it'd be better to wait.
=> Small fix for single column model mode

.buildkite/pipeline.yml
Because `/` is small and often full, causing initialization to fail when `TMPDIR=/tmp` by default.
=> Change TMPDIR for CPU initialization on tartarus

src/Simulations/callback.jl, test/test_simulations.jl
This allows users to build `Callback`s with optional parameters. This feature addition resolves #2127 .
=> Add parameters to Callback

src/Fields/broadcasting_abstract_fields.jl, test/test_broadcasting.jl
This PR generalizes the broadcasting implementation to work with fields reduced in any direction. The changes mean that, for example, if broadcasting to a field that's reduced in _two_ directions (eg a 1D field on a 3D grid), the kernel that's launched to do the computation will be 1D and therefore will not "waste" computation. It also turns out that the "generalization" requires less code than the original implementation (doh). This PR also adds more tests for broadcasting to reduced fields.
=> More support for broadcasting to reduced fields

.buildkite/pipeline.yml, src/BoundaryConditions/BoundaryConditions.jl, src/BoundaryConditions/boundary_condition.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/BoundaryConditions/fill_halo_regions_nothing.jl, src/CubedSpheres/CubedSpheres.jl, src/Fields/field.jl, test/test_field.jl
This PR adds a step in the outer `Field` constructor that validates boundary conditions. We check three things:
1. That boundary conditions are compatible with the topology. Namely, we are restricted to default choices in `Periodic` or `Flat` directions; anything but default throws an error.
2. If a topology is `Bounded`, we check that boundary conditions are compatible with field location. Mostly we cannot support flux, value, or gradient boundary conditions for fields at faces, and we only support `nothing` for fields in `Flat` directions.
3. That boundary condition arrays are on the right architecture.
TODO:
Resolves #419
Resolves #890
Supercedes #1732
=> Validate boundary conditions on Fields

.buildkite/pipeline.yml, src/Fields/Fields.jl, src/Fields/constant_field.jl, src/Fields/zero_field.jl
This PR adds `OneField` and `ConstantField` and generalizes `ZeroField` to be capable of producing zeros of any type. In particular it may be useful to use a `ZeroField(Bool)` since `false` is a "strong" zero.
@simone-silvestri you may find `OneField` useful for estimating lengths efficiently, along with `ConditionalOperation`.
=> `OneField`, `ConstantField`, and generalized `ZeroField`

Project.toml, src/AbstractOperations/grid_metrics.jl, src/AbstractOperations/metric_field_reductions.jl, test/test_computed_field.jl, test/test_field_reductions.jl
This PR fixes `Average` to correctly to use `mean!` when reducing over regular dimensions. It also adds a few tests.
=> Fixes bug inferring regular dimensions for Average

Project.toml, src/Fields/field.jl, src/Fields/regridding_fields.jl, src/Fields/set!.jl, src/Grids/grid_utils.jl
This PR checks whether two grids are only different in the vertical dimension using runtime information, rather then relying on both fields being `SingleColumnGrid`.
It also extends `total_length` for directions that are `Flat`, but have non-zero grid points (for simulations representing ensembles of simulations).
Closes #2067
=> Let regridding work on non-`SingleColumnGrid` +  better `total_length` on `Flat` grids

Project.toml, src/Fields/regridding_fields.jl, test/test_field.jl
~Also bumps to 0.68.8.~
The application for this kind of regridding is from a field that, while living on a 3D grid, is reduced in x and y. Because the field is reduced in x and y it's a valid source field for a target field that's on a 1D grid.
We should probably add a test to this PR (regridding from a reduced field on a 3D grid to a non-reduced field on a 1D grid).
cc @adelinehillier @navidcy
=> Change regridding criterion to check field size rather than grid size

docs/src/model_setup/buoyancy_and_equation_of_state.md, src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
After this PR
```Julia
julia> grid = RectilinearGrid(topology=(Periodic, Bounded, Bounded), size=(1, 1, 1), extent=(1, 2, 3))
1×1×1 RectilinearGrid{Float64, Periodic, Bounded, Bounded} on CPU with 1×1×1 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=1.0
├── Bounded  y ∈ [0.0, 2.0]  regularly spaced with Δy=2.0
└── Bounded  z ∈ [-3.0, 0.0] regularly spaced with Δz=3.0
julia> model = HydrostaticFreeSurfaceModel(grid=grid)
HydrostaticFreeSurfaceModel{CPU, Float64}(time = 0 seconds, iteration = 0)
├── grid: 1×1×1 RectilinearGrid{Float64, Periodic, Bounded, Bounded} on CPU with 1×1×1 halo
├── tracers: (:T, :S)
├── closure: Nothing
├── buoyancy: Buoyancy{SeawaterBuoyancy{Float64, LinearEquationOfState{Float64}, Nothing, Nothing}, …
```
=> Show free surface method/solver for `HydrostaticFreeSurfaceModel`s

src/Fields/interpolate.jl
Looks like this only worked for `Field`. Not it should work for `AbstractOperations` too. Supercedes #1260 .
=> Generalize `interpolate(field, x, y, z)`

src/Simulations/time_step_wizard.jl
This PR includes the `diffusive_cfl` keyword argument in the docstring (specifically the constructor's signature) of `TimeStepWizard`. The only arguments that aren't listed now are the advective and diffusive time scales. I chose to keep them this way in the PR because it seems like those options aren't user-facing.
=> Include `diffusive_cfl` in `TimeStepWizard`'s docstring

src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl, src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl, src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/surface_TKE_flux.jl
```Julia
julia> using Oceananigans.TurbulenceClosures.CATKEVerticalDiffusivities: CATKEVerticalDiffusivity
julia> catke = CATKEVerticalDiffusivity()
┌ Warning: CATKEVerticalDiffusivity is an experimental turbulence closure that
│ is unvalidated and whose default parameters are not calibrated for
│ realistic ocean conditions or for use in a three-dimensional
│ simulation. Use with caution and report bugs and problems with physics
│ to https://github.com/CliMA/Oceananigans.jl/issues.
└ @ Oceananigans.TurbulenceClosures.CATKEVerticalDiffusivities /g/data/v45/nc3020/.julia/packages/Oceananigans/Bks9B/src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl:95 …
```
=> Add show method for CATKE closure

Project.toml, src/Simulations/time_step_wizard.jl, test/test_simulations.jl
The clause that controls the definition of `cell_diffusion_timescale` in `TimeStepWizard` had a bug. I re-wrote in a way that's clearer to understand and that fixes the bug.
Consider the MWE below:
```julia
grid = RectilinearGrid(size=(8, 8, 8), extent = (1,1,1),
topology=(Periodic, Periodic, Bounded))
closure = IsotropicDiffusivity(ν=1)
model = NonhydrostaticModel(grid = grid,
closure = closure)
@info "" model
wizard = TimeStepWizard(diffusive_cfl=0.1,)
```
Before this PR:
```julia
julia> wizard.cell_diffusion_timescale(model)
Inf
julia> @which wizard.cell_diffusion_timescale(model)
infinite_diffusion_timescale(args...) in Oceananigans.Simulations at /home/tomas/.julia/packages/Oceananigans/IHPoE/src/Simulations/time_step_wizard.jl:12
```
After this PR:
```julia
julia> …
```
=> Fixes bug in `TimeStepWizard`'s diffusive timescale calculation

Project.toml, src/TurbulenceClosures/closure_tuples.jl
This is a wilderness of the code with not many tests. This is part of ongoing work to build infrastructure for calibrating mesoscale parameterizations in conjunction with `OceanTurbulenceParameterEstimation.jl`.
cc @sandreza
=> Support for tuples with arrays of closures

Project.toml, src/Models/HydrostaticFreeSurfaceModels/slice_ensemble_model_mode.jl
The signature used to extend `FFTImplicitFreeSurfaceSolver` was not used by `build_implicit_free_surface_solver`; thus, slice ensemble models had incorrect free surface solvers. This PR fixes it.
=> Fixes FFT solver constructor for an ensemble of slice models

src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl, src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl, src/Solvers/preconditioned_conjugate_gradient_solver.jl
This is a workaround to avoid printing `solver: Default` and instead print `solver: FFTImplicitFreeSurfaceSolver`.
=> Saves actual `solver_method` name in `ImplicitFreeSurface` (not just `:Default`)

examples/ocean_wind_mixing_and_convection.jl
This is a very minor update just to make the plotting command in the Ocean mixing and convection example a bit more general and self-contained. This makes it easier for people to copy-paste that snippet and have it work out of box (I do that frequently for example).
=> Minor change to Ocean mixing and convection example

docs/make.jl
The docs repo is running out of space. In an attempt to remedy that I'm trying here `forcepush = true` for deploying docs.
https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.deploydocs
=> Deploy docs with `forcepush = true`

docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md
I think the docs weren't 100% clear before on how to actually use different horizontal and vertical components in a single closure. I also couldn't figure out how to set `νx` different from `νy`, but I'm assuming that possible. So if anyone knows, I think we could also add that there.
=> Adds a sentence to the Anisotropic diffusivity section of the docs

Project.toml, src/Simulations/run.jl
This PR tweaks `initialize_simulation!` so that the schedules get called when `iteration == 0` --- in addition to running diagnostics, executing callbacks, and writing output.
This is a tiny step in the direction of having a robust initialization procedure. I think we still need to work on the abstractions a bit though, since it'd be nice to initialize schedules / callbacks more explicitly rather than implicitly relying on `iteration == 0`. This change will affect `SpecifiedTimes` and `WallTimeInterval` the most, I think.
TODO:
=> Initialize schedules at iteration 0

docs/src/physics/turbulence_closures.md
I believe the [Physics/Turbulence Closures](https://clima.github.io/OceananigansDocumentation/stable/physics/turbulence_closures/) section of docs had a minor inconsistency caused by a minus sign.
Also (I haven't changed this yet because I haven't had the time to check in the code) I believe there might be a factor of 2 missing from the τ_ij equation (not numbered), which is the first Eq in [this subsection](https://clima.github.io/OceananigansDocumentation/stable/physics/turbulence_closures/#Smagorinsky-Lilly-turbulence-closure)). 
Other pairs of eyes here would be appreciated, but if not I'll double check everything at a later date.
=> Small adjustment to Turbulence Closures section of docs

docs/src/model_setup/boundary_conditions.md, docs/src/model_setup/buoyancy_and_equation_of_state.md, examples/ocean_wind_mixing_and_convection.jl, src/BuoyancyModels/linear_equation_of_state.jl, test/regression_tests/ocean_large_eddy_simulation_regression_test.jl, test/test_abstract_operations.jl, test/test_buoyancy.jl, test/test_computed_field.jl, test/test_dynamics.jl, validation/mesoscale_turbulence/eddying_channel_nonhydrostatic.jl, validation/near_global_lat_lon/annual_cycle_earth_bathymetry.jl, validation/near_global_lat_lon/annual_cycle_earth_bathymetry_fine.jl, validation/near_global_lat_lon/constant_forcing_earth_bathymetry.jl, validation/stratified_couette_flow/stratified_couette_flow.jl
This PR changes `α` and `β` in `LinearEquationOfState` to `thermal_expansion` and `haline_contraction`.
Closes #453
=> Use verbose names in `LinearEquationOfState`

src/Fields/show_fields.jl
So that
```julia
julia> grid = RectilinearGrid(size=(4, 4, 4), extent=(4, 4, 4));
julia> a = CenterField(grid); b = XFaceField(grid);
julia> (; a, b)
(a = 4×4×4 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 4×4×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── boundary conditions: west=Periodic, east=Periodic, south=Periodic, north=Periodic, bottom=ZeroFlux, top=ZeroFlux, immersed=ZeroFlux
└── data: 6×6×6 OffsetArray(::Array{Float64, 3}, 0:5, 0:5, 0:5) with eltype Float64 with indices 0:5×0:5×0:5
└── max=0.0, min=0.0, mean=0.0, b = 4×4×4 Field{Face, Center, Center} on RectilinearGrid on CPU
├── grid: 4×4×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── boundary conditions: …
```
=> Add show method for FieldTuple

src/Grids/grid_utils.jl, src/Grids/latitude_longitude_grid.jl
This PR updates the `show()` method for `LatitudeLongitudeGrid` to denote which of the directions is latitude and which is longitude. It also updates the docstring to match the latest syntax.
```julia
julia> LatitudeLongitudeGrid(size = (10, 4, 5),
latitude = (-40, 40),
longitude = (-20, 20),
z = (-2000, 0),
topology = (Periodic, Bounded, Bounded),
halo = (2, 2, 2))
10×4×5 LatitudeLongitudeGrid{Float64, Periodic, Bounded, Bounded} on CPU with 2×2×2 halo and with precomputed metrics
├── Periodic λ ∈ [-20.0, 20.0)  regularly spaced with Δλ=4.0
├── Bounded  φ ∈ [-40.0, 40.0]  regularly spaced with Δφ=20.0
└── Bounded  z ∈ [-2000.0, 0.0] regularly spaced with Δz=400.0
```
```Julia
julia> LatitudeLongitudeGrid(size = (10, 4, 5),
latitude = …
```
=> Denote which coordinate is lat and which is lon in `show(io, ::LatitudeLongitudeGrid)`

Project.toml, src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl, src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/surface_TKE_flux.jl
This PR updates the dissipation and surface TKE flux parameter for CATKE. These were _not_ updated in #2273, but they should have been.
cc @adelinehillier
=> Update dissipation and surface TKE flux parameters for CATKE

src/Fields/field.jl, src/Fields/field_reductions.jl
Just a little sugary convenience so we can write one-liners like
```Julia
U = compute!(Field(Average(u, dims=1)))
```
(Note that other `compute!` already do this, we just have a few lingering inconsistencies.)
=> Return `field` from `compute!(field::ReducedComputedField)`

docs/src/numerical_implementation/time_stepping.md
Better number all equations. Following *Rule I; Fisher's rule* from Mermin's funny and on-the-point essay "What's wrong with those equations?", http://www.geo.umass.edu/faculty/wclement/Writing/equations.pdf
cc @elise-palethorpe
=> Number all equations in Docs/Timestepping section

benchmark/Manifest.toml, benchmark/Project.toml
`benchmarks/Manifest.toml` had CUDA updated to 3.7 which caused problems when benchmarking Oceananigans restricted to 3.3.6. This PR adds a `compat` to `benchmarks/Project.toml` and downgrades `CUDA`.
I think maybe a better solution would be to add Oceananigans explicitly to `benchmarks/Project.toml`. But then to run the benchmarks on the current repo we'd have to update the environment every time.
=> Updates Benchmarks environment

Project.toml, src/OutputReaders/field_time_series.jl, src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
This PR updates `FieldTimeSeries` to be slightly "backward compatible" and capable of loading data from Oceananigans versions that did not have `Field.indices`, or which serialized stretched GPU grids with `CuArray`s.
We might have to constantly maintain this... but hopefully eventually structures will be more stable, and eventually we can just delete the stuff added here.
=> Some backward compatibility for `FieldTimeSeries`

src/OutputWriters/jld2_output_writer.jl
Just clarify a detail about `indices`
=> JLD2OutputWriter: right now the indices have to be contiguous

benchmark/Manifest.toml, benchmark/distributed_nonhydrostatic_model_mpi.jl
This PR tries to make the script a bit easier to run based on my experiences with it. For example `Benchmark` and `@gpu_sync` aren't needed in this case and we can delete it.
So far I've only been able to run this with one core (see https://github.com/CliMA/Oceananigans.jl/issues/2433).
Closes https://github.com/CliMA/Oceananigans.jl/issues/2433
=> Updates `distributed_nonhydrostatic_model_mpi.jl`

src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
If there is no tracer then only show `ν`.
Resolves #2443.
```Julia
[ Info: Oceananigans will use 10 threads
julia> grid = RectilinearGrid(size=(1, 1, 1), extent=(1, 2, 3), halo=(2, 2, 2));
julia> model = NonhydrostaticModel(closure=ScalarBiharmonicDiffusivity(); grid)
NonhydrostaticModel{CPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── grid: 1×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 2×2×2 halo
├── timestepper: QuasiAdamsBashforth2TimeStepper
├── tracers: ()
├── closure: ScalarBiharmonicDiffusivity{ThreeDimensionalFormulation}(ν=0.0)
├── buoyancy: Nothing
└── coriolis: Nothing
```
=> Better diffusivity closure `show()`

src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl, src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
This allows us to implement "divergence damping" for large scale ocean models via `ScalarDiffusivity`:
```julia
using Oceananigans.TurbulenceClosures: HorizontalDivergenceFormulation
divergence_damping = ScalarDiffusivity(HorizontalDivergenceFormulation(), ν=1)
```
We probably also want vorticity damping. There also might be other names, for vorticity damping the coefficient is often referred to as the "rotational viscosity".
A few other things:
* Possibly one should throw an error if users specify kappa, since this closure has no tracer diffusion.
* I added an abstract type for the formulations
* Should we use flux=0 fallbacks? We have a substantial amount of code devoted to emitting zero fluxes for many cases (eg zero tracer flux in this case).
=> Adds HorizontalDivergenceFormulation for scalar diffusions

Project.toml, src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
This emits a warning when Oceananigans is compiled:
```
WARNING: Method definition diffusive_flux_z(Any, Any, Any, Any, Oceananigans.TurbulenceClosures.AbstractScalarDiffusivity{var"#s139", var"#s138"} where var"#s138"<:Oceananigans.TurbulenceClosures.HorizontalDivergenceFormulation where var"#s139", Any, Base.Val{x} where x, Any...) in module TurbulenceClosures at /Users/gregorywagner/Projects/Oceananigans.jl/src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl:192 overwritten at /Users/gregorywagner/Projects/Oceananigans.jl/src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl:204.
** incremental compilation may be fatally broken for this module **
```
=> Remove redundant definition of `diffusive_flux_z` for divergence damping

src/TurbulenceClosures/isopycnal_rotation_tensor_components.jl, src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl, validation/mesoscale_turbulence/coarse_lat_lon_baroclinic_adjustment.jl
This PR refactors the calculation of `isopycnal_rotation_components` to _actually_ use the "Cox stencil" described by [Griffies et al 1998](https://journals.ametsoc.org/view/journals/phoc/28/5/1520-0485_1998_028_0805_idiazc_2.0.co_2.xml).
~~It looks to me like MITgcm uses this so-called anti-Cox stencil.~~ It looks like MITgcm uses the Cox stencil. For example, when calculating the "Gradient of Sigma at rVel points" --- which appears in `isopycnal_rotation_tensor_xz_ccf` --- MITgcm uses
https://github.com/MITgcm/MITgcm/blob/9bcb4977016b9cc234328aa357b105d227417e43/pkg/gmredi/gmredi_calc_tensor.F#L712
which reconstructs the x-component of the density gradient by _averaging the gradient_ (with a four point average). On the other hand, we use …
=> Implement the actually-Cox (aka the anti-anti-Cox) stencil for GM

src/TurbulenceClosures/abstract_scalar_biharmonic_diffusivity_closure.jl, src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
This PR introduces a "Biharmonic" divergence damping.
In line with #2440, `ScalarBiharmonicDiffusivity(HorizontalDivergenceFormulation(), ν = 1)`, is a biharmonic diffusion that acts only on the divergent component of the horizontal velocity field.
This allows us to diffuse the remaining horizontally rotational component through the use of a WENO scheme (which does not act on vertical motions, hence does not dissipate noise generated through divergent motions)
=> Biharmonic divergence damping

src/Advection/vector_invariant_advection.jl
I found out that treating with WENO the vertical advection in a vector invariant formulation (`w⋅∂z(u)` and `w⋅∂z(u)`) might be detrimental because
- The noise is not propagated by the `u` and `v` fields which are weno-interpolated but by the `w` field which is just centrally-interpolated
- The wall-time increases substantially without a benefit
- In global simulations (both 1 degree and 1/4 degree) the solution seems to be less stable
This PR comments out the vertical WENO advection for the moment returning to a 2nd order version so we can still use a beneficial version of the WENO vector invariant. The vertical advection term requires further study....
=> Remove vertical advection from vector invariant WENO

src/MultiRegion/multi_region_output_writers.jl
this PR fixes a bug in the `OutputWriters` for which the output fields are not updated when writing
=> OutputWriters for MultiRegion

test/test_computed_field.jl
This PR adds tests for "sliced" `compute!(field)`, when `field.indices != (:, :, :)`.
=> Add tests for computations on slices

src/Distributed/distributed_fft_based_poisson_solver.jl, src/Models/NonhydrostaticModels/NonhydrostaticModels.jl, src/Models/NonhydrostaticModels/solve_for_pressure.jl, test/test_distributed_models.jl, test/test_distributed_poisson_solvers.jl
This PR permutes the dimensions of the _temporary array_ that's used by the `DistributedFFTBasedPoissonSolver` (and `PencilFFTs`) compared to Oceananigans data layout to look like (z, x, y). This permits "pencil" decompositions in x, y via PencilFFTs, which cannot partition along the first dimension.
This PR should probably expand the tests to cover these cases, which weren't tested previously because it wasn't supported.
Co-developed with @johnryantaylor.
=> Permute PencilFFT temporary array dimensions

src/OutputWriters/jld2_output_writer.jl
This PR "enhances" `JLD2OutputWriter` so it first _checks_ whether an iteration number exists in the file it's about to save to. If the iteration number does exist, it emits warning, but does not fail. Previously, it would fail. This helps when restoring a simulation from a checkpoint when output is saved at higher frequency than the simulation is checkpointed.
TODO: probably test makes sense.
=> Make JLD2 look before leaping

src/Advection/weno_fifth_order.jl, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl, src/ImmersedBoundaries/ImmersedBoundaries.jl, src/ImmersedBoundaries/immersed_grid_metrics.jl
This PR fixes the following problem:
```julia
julia> grid_base = RectilinearGrid(size=(4, 4, 4),
x = (0, 1), y=(0, 1),
z = (0, 1),
halo=(3,3,3),
)
4×4×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [0.0, 1.0) regularly spaced with Δx=0.25
├── Periodic y ∈ [0.0, 1.0) regularly spaced with Δy=0.25
└── Bounded  z ∈ [0.0, 1.0] regularly spaced with Δz=0.25
julia> grid = ImmersedBoundaryGrid(grid_base, GridFittedBottom(bathymetry))
4×4×4 ImmersedBoundaryGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo:
├── immersed_boundary: GridFittedBottom{OffsetArrays.OffsetMatrix{Float64, Matrix{Float64}}}
├── underlying_grid: 4×4×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── …
```
=> Fixes `WENO5(grid=grid)` for immersed boundary grids

src/Distributed/distributed_grids.jl, src/Grids/input_validation.jl, src/Grids/rectilinear_grid.jl, test/test_grids.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/2548
Before this PR:
```julia
julia> grid = RectilinearGrid(size=(4, 4, 4),
x = (0,1), y=(0,1),
z = LinRange(0,1,20), 
halo=(3,3,3),
)
4×4×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [0.0, 1.0)      regularly spaced with Δx=0.25
├── Periodic y ∈ [0.0, 1.0)      regularly spaced with Δy=0.25
└── Bounded  z ∈ [0.0, 0.210526] variably spaced with min(Δz)=0.0526316, max(Δz)=0.0526316
julia> grid.zᵃᵃᶜ
10-element OffsetArray(::Vector{Float64}, -2:7) with eltype Float64 with indices -2:7:
-0.13157894736842105
-0.07894736842105263
-0.02631578947368421
0.02631578947368421
0.07894736842105263
0.13157894736842105
0.18421052631578946
0.23684210526315788 …
```
=> Throws error when size of dimension is mismatched when constructing RectilinearGrid

src/OutputWriters/netcdf_output_writer.jl
=> Adds `with_halos` to `NetCDFOutputWriter`'s signature call in docstring

.gitignore, docs/src/model_setup/grids.md, examples/baroclinic_adjustment.jl, examples/convecting_plankton.jl, examples/horizontal_convection.jl, examples/internal_wave.jl, examples/kelvin_helmholtz_instability.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/one_dimensional_diffusion.jl, examples/shallow_water_Bickley_jet.jl, examples/tilted_bottom_boundary_layer.jl, examples/two_dimensional_turbulence.jl, src/OutputReaders/field_time_series.jl
This PR builds on @navidcy's excellent work to convert all the examples to Makie. I tried to unify the coding style in the examples as best I could. Also, there was a bit too much logging / plotting messages in the examples, which polluted the docs.
TODO:
=> Beautify examples a bit more

docs/src/model_setup/grids.md
This PR adds back a figure that somehow is not shown in the Docs/Model/Grids section and also adds an example of grid construction that has a `Flat` topology in the same docs.
=> Adds back a fig in Docs/Model/Grids + example with `Flat` topology

src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl, src/Solvers/fft_based_poisson_solver.jl, src/Solvers/heptadiagonal_iterative_solver.jl
Enhances docstring for the `ImplicitFreeSurface` constructor to include the available solver methods.
Closes #2620
=> Update `ImplicitFreeSurface` & `HeptadiagonalIterativeSolver` docstrings

test/test_matrix_poisson_solver.jl, test/test_multi_region_poisson_solver.jl
=> Use predefined `compute_∇²!` instead of defining new `calc_∇²!` in `test_matrix_poisson_solver.jl`

examples/one_dimensional_diffusion.jl
Some of the figures aren't rendering and this is an attempt to fix that:
It should render here: https://clima.github.io/OceananigansDocumentation/previews/PR2648/generated/one_dimensional_diffusion/
=> Small change to 1D diffusion example

examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl
This PR:
- The Langmuir example currently claims that the buoyancy flux in the 2021 paper is `2.307e-9 # m² s⁻³, surface buoyancy flux` and sets up the buoyancy flux accordingly. But the paper actually sets up a flux of `2.307e-8` so I changed that (I think it was a typo). @glwagner can you please confirm that I'm not missing anything?
- Updates the CPU -> GPU functionality done via grid constructor instead via model in the Ocean wind mixing example.
Docs should render here: It should render here: https://clima.github.io/OceananigansDocumentation/previews/PR2646
=> Minor changes in Langmuir and Ocean wind mixing examples

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl, src/TurbulenceClosures/turbulence_closure_utils.jl, test/test_turbulence_closures.jl
small bugfix for which `discrete_form=form` and `Fields` were not working for tracers.
Also passing all the fields to the forcing function instead of only the prognostic ones
=> Bugfix for `DiscreteDiffusionFunction` + passes prognostic + auxiliary fields to forcing functions

src/Utils/multi_region_transformation.jl
never really used in the code but solves a bug which appeared if  `@apply_regionally` was used with a `begin ... end` 
as
```
@apply_regionally begin
fill!(u, 0.0)
r = data(u)
end
```
=> small bugfix in multi-region

docs/make.jl, docs/src/appendix/fractional_step.md, docs/src/appendix/library.md, docs/src/numerical_implementation/elliptic_solvers.md
=> Fixes doc references in Numerical Implementation/Elliptic Solvers section + `checkdocs = :exports`

examples/tilted_bottom_boundary_layer.jl
The video at the end of this example doesn't look optimal so I'm gonna try to improve it.
Preview should render here: https://clima.github.io/OceananigansDocumentation/previews/PR2704/generated/tilted_bottom_boundary_layer/
=> Improves plotting in tilted bottom boundary layer example

src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl, src/Solvers/multigrid_solver.jl
The multilevel structure should only be created when the matrix is initialized or altered.
cc @navidcy
=> Reduces allocations for Multigrid solver on CPU: Multilevel structure only created when required

docs/make.jl, examples/horizontal_convection.jl, src/OutputWriters/jld2_output_writer.jl, src/OutputWriters/netcdf_output_writer.jl
In the horizontal convection example `χ_diff` is defined as a volume average of the buoyancy dissipation but when computing it were not dividing by the total volume. Now fixed. To compute the buoyancy dissipation the halos were crucial so as to take into account correct boundary conditions for `b` -- the example now remarks on this and saves output using `with_halos = true`.
Closes #2735.
=> Correct computation for buoyancy dissipation rate, `χ_diff` + demonstrate `Integral`

src/AbstractOperations/at.jl, src/AbstractOperations/derivatives.jl, src/AbstractOperations/multiary_operations.jl, src/OutputReaders/field_dataset.jl
Following the warnings issued by julia `v1.8.2`
```
WARNING: method definition for _multiary_operation at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/multiary_operations.jl:23 declares type variable LZ but does not use it.
WARNING: method definition for _multiary_operation at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/multiary_operations.jl:23 declares type variable LY but does not use it.
WARNING: method definition for _multiary_operation at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/multiary_operations.jl:23 declares type variable LX but does not use it.
WARNING: method definition for _derivative at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/derivatives.jl:31 declares type variable LZ but does not use it.
WARNING: method definition for …
```
=> Cleanup unused type variables

src/Models/ShallowWaterModels/shallow_water_cell_advection_timescale.jl
Also specifies that the methods only work for `RectilinearGrid`, and cleans up the formatting.
Some background on #2720 with @pjrusello
=> Ignore halos and immersed cells in calculating shallow water advection time-scale

src/Models/HydrostaticFreeSurfaceModels/barotropic_pressure_correction.jl, src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
A leftover bug from the sliced fields PR that was neglecting the free surface contribution on immersed grids (and crashing our global simulations)
=> Bugfix in implicit free surface

src/Fields/field.jl, src/OutputWriters/output_construction.jl
https://github.com/CliMA/Oceananigans.jl/pull/2740 Introduced extra memory allocation in output construction of ComputedFields to satisfy sliced boundary conditions constraints.
This PR changes the definition of `view(f::Field, indices...)` in order to automatically satisfy sliced boundary condition constraints and avoid unnecessary memory allocation.
closes #2794 ?
=> Remove extra memory allocations of `output_construction`

src/Grids/conformal_cubed_sphere_face_grid.jl
~see [https://docs.julialang.org/en/v1/devdocs/boundscheck/\#Caution](https://docs.julialang.org/en/v1/devdocs/boundscheck/#Caution)~
Closes #2815
=> Fix wrong looping over indices of OffsetArray

examples/baroclinic_adjustment.jl
=> Simplify the baroclinic adjustment example

Project.toml, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl, src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl, src/MultiRegion/multi_region_utils.jl
Affects calibration with single column models (but mostly on the GPU?) and tracer simulations with `PrescribedVelocityFields`.
cc @adelinehillier 
closes #2809
=> Fix race condition affecting `HydrostaticFreeSurfaceModel` with `isnothing(free_surface)`

src/Grids/input_validation.jl
At the moment the error throwing in the function `validate_index()` isn't working due to an undefined variable. For indices that aren't valid, the error ends up being not useful:
```julia
caused by: UndefVarError: I not defined
Stacktrace:
[1] validate_index(idx::UnitRange{Int64}, loc::Type, topo::Type, N::Int64, H::Int64)
@ Oceananigans.Fields /glade/work/tomasc/.julia/packages/Oceananigans/7G5bN/src/Fields/field.jl:90
[2] validate_index
@ /glade/work/tomasc/.julia/packages/Oceananigans/7G5bN/src/Fields/field.jl:94 [inlined]
```
This PR fixes that with a simpler error message.
=> Fixes bug in error for `validate_index`

Project.toml, src/Grids/input_validation.jl
Currently an error during grid validation is actually not printed, instead you get
```
ERROR: UndefVarError: N! not defined
```
as string interpolation is expecting a variable called `N!` when the variable is `N`.
This PR fixes this.
=> Fix bug when throwing exception during grid validation

src/Fields/interpolate.jl
Hi all,
I noticed that some of the array indexing in `interpolate` weren't `@inbounds`'ed so added them, and then also noticed that `issorted` tooke a good fraction of the time when interpolating fields on irregular grids so I removed that since the funciton is only used internally and is always going to be given sorted vectors.
This results in a ~5x speedup so seems worth it.
=> Increased `interpolate` speed

docs/make.jl
Unfortunately the previews clog up the [OceananigansDocumentation](https://github.com/CliMA/OceananigansDocumentation) repository and we need to perform manual cleanup often...
I suggest we drop the doc previews for the moment. We could build the docs manually _or_ temporarily enable them for a particular PR that includes Doc changes and then disable them again.
=> Don't push docs preview

src/CubedSpheres/cubed_sphere_faces.jl
I've been facing some trouble in https://github.com/CliMA/Oceananigans.jl/pull/2842/ for cubed sphere grids and I think that's why. Locally this change makes the tests there pass.
Admittedly I know very little about cubed spheres, so input is appreciated.
=> Adds `get_face()` method for `FunctionField`

docs/make.jl, examples/baroclinic_adjustment.jl, examples/internal_wave.jl, examples/ocean_wind_mixing_and_convection.jl
=> Correct filename for internal wave movie

src/BoundaryConditions/show_boundary_conditions.jl
```Julia
model = HydrostaticFreeSurfaceModel(grid=RectilinearGrid(topology=(Bounded, Bounded, Bounded), size=(8, 6, 8), extent=(10, 20, 3)));
model.velocities.u
```
before this PR would give:
```julia
9×6×8 Field{Face, Center, Center} on RectilinearGrid on CPU
├── grid: 8×6×8 RectilinearGrid{Float64, Bounded, Bounded, Bounded} on CPU with 3×3×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Open, east: Open, south: ZeroFlux, north: ZeroFlux, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 15×12×14 OffsetArray(::Array{Float64, 3}, -2:12, -2:9, -2:11) with eltype Float64 with indices -2:12×-2:9×-2:11
└── max=0.0, min=0.0, mean=0.0
```
after this PR:
```julia
9×6×8 Field{Face, Center, Center} on RectilinearGrid on CPU
├── grid: 8×6×8 …
```
=> Better show for impenetrable boundary condition

src/AbstractOperations/binary_operations.jl, test/test_abstract_operations.jl
This PR defines some binary operations involving `ZeroField`s that might be useful, and adds tests for those operations. The issue came up at https://github.com/tomchor/Oceanostics.jl/pull/104
=> Defines some binary operations with `ZeroField`

src/Grids/latitude_longitude_grid.jl
I guess it doesn't make any difference since both Δφ spacings between faces or centers are the same. But for the sake of sanity it should be changed. Thus, I removed the "bug" label.
=> Fix in lat-lon grid `Δy` metric

benchmark/benchmark_abstract_operations.jl, benchmark/benchmark_advection_schemes.jl, benchmark/benchmark_equations_of_state.jl, benchmark/benchmark_fourier_tridiagonal_poisson_solver.jl, benchmark/benchmark_lagrangian_particle_tracking.jl, benchmark/benchmark_multithreading_single.jl, benchmark/benchmark_shallow_water_model.jl, benchmark/benchmark_time_steppers.jl, benchmark/benchmark_topologies.jl, benchmark/benchmark_tracers.jl, benchmark/benchmark_turbulence_closures.jl, benchmark/benchmark_vertically_stretched_nonhydrostatic_model.jl, benchmark/distributed_nonhydrostatic_model_threaded.jl, benchmark/distributed_shallow_water_model_threaded.jl, docs/src/model_setup/boundary_conditions.md, src/AbstractOperations/grid_metrics.jl, src/Advection/vector_invariant_advection.jl, src/Advection/weno_reconstruction.jl, src/Distributed/distributed_fft_based_poisson_solver.jl, src/Models/ShallowWaterModels/shallow_water_advection_operators.jl, src/Operators/divergence_operators.jl, src/Operators/vorticity_operators.jl, src/OutputReaders/field_dataset.jl, src/OutputWriters/checkpointer.jl, src/OutputWriters/jld2_output_writer.jl, src/OutputWriters/netcdf_output_writer.jl
supersedes #2872 
basically similar except without changing, e.g., `grid=grid, ...` -> `; grid,...`.
=> Some docstring fixes/enhancements + Code cleanup

Project.toml, docs/src/model_setup/output_writers.md, src/OutputWriters/jld2_output_writer.jl, src/OutputWriters/netcdf_output_writer.jl, src/OutputWriters/windowed_time_average.jl, test/test_netcdf_output_writer.jl
While `Array{Float32}` is neat because user output is smaller, it's a bad default because it often leads to confusing results, like the fact that outputing `Field(Integral(c))` is different (possibly by `eps(Float32)`) than computing `Integral(c_output)` in post processing when `Field(Integral(c))` is close to 0.
Thus @xkykai and I propose to make the default `Array{Float64}`. We could regard outputting with `Array{Float32}` as an "optimization" which is premature as a default.
=> Change default output array type for `JLD2OutputWriter` to `Array{Float64}`

src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl
This PR removes the calculation of the diffusivities in `DiffusivityFields()` for the SmagorinskyLilly so that binary operations are avoided.
Closes https://github.com/CliMA/Oceananigans.jl/issues/2869
=> Removes diffusivity calculation from `DiffusivityFields()` for Smagorinsky closure

src/Grids/grid_utils.jl, src/Grids/inactive_node.jl, src/ImmersedBoundaries/ImmersedBoundaries.jl, src/ImmersedBoundaries/active_cells_map.jl, src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl, src/Models/NonhydrostaticModels/calculate_nonhydrostatic_tendencies.jl, src/MultiRegion/multi_region_boundary_conditions.jl, src/MultiRegion/multi_region_field.jl, src/MultiRegion/multi_region_grid.jl, src/MultiRegion/multi_region_models.jl, src/MultiRegion/multi_region_reductions.jl, src/MultiRegion/multi_region_utils.jl, src/MultiRegion/x_partitions.jl, src/MultiRegion/y_partitions.jl, src/Utils/kernel_launching.jl, src/Utils/multi_region_transformation.jl
This is important for writing robust and readable code in our time-stepping algorithm.
=> Make `construct_regionally` handle multiple return values

src/TurbulenceClosures/TurbulenceClosures.jl, src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl, test/test_turbulence_closures.jl
A recent PR broke the user-facing `diffusivity()` function for `SmagorinskyLilly` and this fixes it. It also adds a test to catch this in the future and exports `diffusivity()` at the `TurbulenceClosure` level, since it's a user-facing function.
=> Fixes `diffusivity()` for Smagorinsky-Lilly closure

test/test_grids.jl, test/test_netcdf_output_writer.jl
I noticed that in a couple of tests in `test_grids.jl` the code was written in way that leads to some not-so-clear statements such as:
https://github.com/CliMA/Oceananigans.jl/blob/182e75c80645af0d6a7105ed2d8d4fcbceb7bccc/test/test_grids.jl#L381
The above seems wrong at first but it's actually correct since `Δzᵃᵃᶜ()` is defined the same way as `grid.Δzᵃᵃᶠ`.
This PR changes that to make the notation clearer (i.e. `grid.Δzᵃᵃᶠ[2:Nz] == Δzᵃᵃᶠ.(2:Nz)`) and condenses 3 separate test functions for stretched grids (needing three separate grid instantiations) into one function (with the same tests).
EDIT:
This also implements a suggestion by @glwagner in https://github.com/CliMA/Oceananigans.jl/pull/2865 that couldn't be implemented then. I'll open another PR in the near future to further condense …
=> Refactor of some stretched rectilinear grid tests

.buildkite/pipeline.yml, Project.toml, src/Coriolis/Coriolis.jl, src/Coriolis/hydrostatic_spherical_coriolis.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
=> Changes wet/dry to active/inactive

src/OutputWriters/checkpointer.jl
This feature adds support for using a checkpoint file to initialize a model that contains additional passive tracers that weren't present in the original simulation. The use case in mind is whenever a user wants to start passive tracers only after simulation spin-up, for example.
At the moment, on main, this isn't possible since if we try to pickup a simulation but a given variable can't be found in the checkpointer file, the code throws a warning when trying to set the data for that variable, and an error when trying to set its tendencies.
This PR changes the code so that it throws an error for both cases. After this PR a user can then do:
```julia
grid = RectilinearGrid(size = (4, 4, 4), extent = (1,1,1))
model_spinup = NonhydrostaticModel(; grid, tracers = :b) …
```
=> Make it easier to restart a simulation from a checkpoint with additional passive tracers

examples/tilted_bottom_boundary_layer.jl
This PR changes ~two things~ about the BBL example:
- The variable `κ` was used for both the von Karman constant and for the eddy diffusivity. Now it's just used for the von Karman constant
- ~When calling `NonhydrostaticModel` we were using ordered arguments, which could make a new user interpret that they should know the order of the arguments when calling `NonhydrostaticModel`. Now this call is made in a more usual way with keyword arguments, where the order doesn't matter.~
=> Small changes to tilted bottom boundary layer example

Project.toml, src/AbstractOperations/computed_field.jl, src/Fields/field.jl, src/Fields/field_reductions.jl, src/OutputWriters/netcdf_output_writer.jl
Closes #2931 
We could add a test...
=> Don't conflate the status of a sliced field with its parent field

src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl, test/test_shallow_water_models.jl
I made an attempt. But it can be definitely improved...
So this diffusivity is applied to the dynamics regardless the formulation?
@francispoulin can you edit the docstring? Or @simone-silvestri?
Closes #2939
=> Docstring for `ShallowWaterScalarDiffusivity`

src/TurbulenceClosures/turbulence_closure_diagnostics.jl, test/test_turbulence_closures.jl
When trying to run a LES with a Tuple closure (such as `closure = (ScalarDiffusivity(), SmagorinskyLilly())`), the calculation of a diffusive timescale fails on main:
```
julia> cell_diffusion_timescale(model.closure, model.diffusivity_fields, model.grid)
ERROR: type Tuple has no field νₑ
Stacktrace:
[1] getproperty
@ ./Base.jl:38 [inlined]
[2] cell_diffusion_timescale(closure::SmagorinskyLilly{Oceananigans.TurbulenceClosures.ExplicitTimeDiscretization, Float64, NamedTuple{(:b,), Tuple{Float64}}}, diffusivities::Tuple{Nothing, NamedTuple{(:νₑ,), Tuple{Field{Center, Center, Center, Nothing, RectilinearGrid{Float64, Periodic, Periodic, Bounded, Float64, Float64, OffsetArrays.OffsetVector{Float64, Vector{Float64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, …
```
=> Fixes calculation of diffusive CFL for LES with Tuple closures

src/Models/NonhydrostaticModels/NonhydrostaticModels.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
This PR adds an informative error when a grid with non-regularly spaced $x$ or $y$ dimensions is provided in the `NonhydrostaticModel`.
Closes #2940
=> Informative error message for non-regularly spaced grids in `NonhydrostaticModel`

src/Utils/kernel_launching.jl
Could be (left, right) or (right, left)... hm!
=> Bugfix in heuristic workgroup

src/Oceananigans.jl, src/TurbulenceClosures/turbulence_closure_implementations/nothing_closure.jl, test/test_turbulence_closures.jl
This is useful for writing general code from the user perspective. Ideally we'd want to return `zero(FT)`, but there's nowhere obvious to get the float type, so I think this is okay for now.
=> Return zero for `closure == nothing`

docs/src/numerical_implementation/turbulence_closures.md
There is an incorrect LaTeX string which produces an Undefined control sequence in `numerical_implementation/turbulence_closures.md` in the documentation. I used the symbol for the mean scalar gradient ``\boldsymbol{\nabla} \overline{c}`` found in the display math a few lines below this which I think is what it should be?
=> Fix rendering in `numerical_implementation/turbulence_colsures.md`

src/Fields/regridding_fields.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Closes #2983
The PR also took the opportunity to remove the warning from the `regrid!` docstring since the warning does not hold after merging #2881
=> More informative message when user provides smaller halo size than ImmersedBoundraryGrid requires

src/OutputReaders/OutputReaders.jl, src/OutputReaders/field_time_series.jl
This PR cleans up / shortens code for `FieldTimeSeries` and makes the `OnDisk` backend usable.
In a future PR I think we'll need a "partially in memory" abstraction, ie chunked data retrieval.
=> Make OnDisk backend minimally usable

examples/langmuir_turbulence.jl, src/StokesDrift.jl, test/test_stokes_drift.jl
This PR adds a `parameters` keyword to `UniformStokesDrift`.
At the moment this only gets activated if `parameters isa NamedTuple`. Do we want to be more general than that?
Closes https://github.com/CliMA/Oceananigans.jl/issues/2960
=> Adds `parameters` keyword to `UniformStokesDrift`

docs/make.jl, examples/tilted_bottom_boundary_layer.jl
This PR does two things:
- Changes `docs/make.jl` to only define the example names once. They were being defined twice before, with some redundancy. Now it'll be easier to comment a given example out when building the docs locally, for example.
- Speeds up the tilted BBL example. I'm doing that by starting it with some noise, which makes turbulence appear much sooner, which allows us to run it for only one day (half the previous time).
=> Small improvements to the docs

src/Grids/Grids.jl, src/Grids/grid_utils.jl, src/ImmersedBoundaries/ImmersedBoundaries.jl, src/Solvers/batched_tridiagonal_solver.jl, src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl, test/test_batched_tridiagonal_solver.jl, test/test_time_stepping.jl
This PR extends `BatchedTridiagonalSolver` to also work when the tridiagonal direction is `x` and `y`, in addition to `z`.
This is one necessary step to getting the `NonhydrostaticModel` to work with grids that are irregularly-spacing in the `x` and `y` directions.
Related to https://github.com/CliMA/Oceananigans.jl/issues/3116
=> Extend `BatchedTridiagonalSolver` to all directions

src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl, test/test_split_explicit_free_surface_solver.jl, test/test_split_explicit_vertical_integrals.jl
This PR allows initializing the `SplitExplicitFreeSurface` with the following keyword arguments:
```julia
free_surface = SplitExplicitFreeSurface(; CFL = 0.7, Δt_max = 10minutes, grid)
```
=> Initialize `SplitExplicitFreeSurface` with a CFL condition

src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
bugs:
- `Δy = minimum_xspacing(grid)`
- some leftover `Δt_max` was changed to `max_Δt`
- when computing `substeps` via cfl then we need to ensure it's an integer
=> Fix few bugs + improve docstring of `SplitExplicitFreeSurface` 

Project.toml, src/OutputWriters/netcdf_output_writer.jl
To use compression in `NCDatasets` , the keyword for `defVar` should be `deflatelevel` instead of `compression`. `defVar` does not show any warning message for unrecognized keywords.
=> (0.84.0) Fix `NetCDFOutputWriter` compression kwarg

Manifest.toml
The current Manifest conflicts with FFMPEG v0.4 and thus enforces it to fallback to FFMPEG v0.2.
This, in principle, is not a problem since we don't depend on FFMPEG. But as soon as we try to use Makie/GLMakie which has FFMPEG as a dependency then it is forced to use FFMPEG v0.2.
FFMPEG v0.2 cannot compile on Apple’s M1/M2 chips and this creates errors and inconvenience. 
I tried to enforce installing `FFMPEG@v0.4` on the current environment and this resulted in downgrade of some `jll`s.
```
⌅ [0234f1f7] ↓ HDF5_jll v1.14.0+0 ⇒ v1.12.2+2
⌃ [7243133f] ↓ NetCDF_jll v400.902.208+0 ⇒ v400.902.5+1
⌅ [458c3c95] ↓ OpenSSL_jll v3.0.9+0 ⇒ v1.1.21+0
```
Informed by that, this PR ensures that those `jll`s satisfy `FFMPEG`s dep requirements so that people with Apple M1/2 chips (like myself) can still …
=> Fix issue with GL/CairoMakie not being able to compile on Apple's M1/2 chips

docs/make.jl
The shallow water example needs ~25 min to run while all other examples need ~1min (2D) or up to ~7min (Baroclinic instability).
This PR forces the workers that run the examples for the docs to start from the shallow water example. This way we minimize the time that the one worker ends up running the swe example while the other one sits and waits.
This PR is related to #3169 but it does _not_ resolve the issue.
=> More docs built optimization

test/runtests.jl
This PR restores some test on netCDF output.
(The tests were removed, if I recall correctly, because at some point netCDF was creating issues on unix machines. Things seems fine now!)
Closes #2956
=> Restore netCDF output writer tests

src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
Add `update_biogeochemical_state!` to `update_state!` for hydrostatic free surface single column mode because it's missing and therefore bgc doesn't work.
=> Add `update_biogeochemical_state!` to `update_state!` for hydrostatic free surface single column mode

Project.toml, README.md, docs/src/index.md, src/Fields/field.jl, src/Oceananigans.jl
Removes all support for <1.9 Julia versions and update `Project.toml`.
Closes #3184
=> (0.86.0) Removes all support for <1.9 Julia versions

src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
I don't know how relevant these changes are, but I found some more type instabilities in the split explicit free surface model's adams bashforth time integrator. Removing them similar to #3212 
Alternatively we could also hardcode the constants
https://github.com/CliMA/Oceananigans.jl/blob/9140a74536784396d368cf8205432433a9deea3d/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl#L11-L19
as Float32
```julia
const β = 0.281105f0
const α = 1.5f0 + β
```
etc. as this will directly upcast to Float64 if that's used, but not cause a type instability with Float32. But this will again cause problems if we ever want to use something else than Float32/64... Now just the `U★, η★` get a bit lengthier!
=> Remove type instability in AB2/3

src/MultiRegion/multi_region_abstract_operations.jl
getregion was not working on `KernelFunctionOperation`s after the update from `computed_dependecies` to `arguments` because of the splatting in the constructor.
This PR fixes it
@siddharthabishnu
=> `getregion` for `KernelFunctionOperation`

Project.toml, src/Fields/set!.jl, test/test_field.jl
It was not copying halo regions, which are needed for correct offline diagnostics since `FieldTimeSeries` uses `set!`.
Closes #3224 
Thanks very much to @hdrake and @ikeshwani for finding this offline-diagnostics-ruining bug!
I think the implementation of `set!` between `Field`s has waffled over time. We should add a test if we want to ensure this behavior.
=> (0.87.1) Make `set!` a little more ambitious

src/Grids/latitude_longitude_grid.jl, test/test_grids.jl
=> Better validation for `LatitudeLongitudeGrid` + add test for `sum(Azᶜᶜᵃ) ≈ 4πr²`

examples/ocean_wind_mixing_and_convection.jl
`minutes` shouldn't be italic as is atm:
https://clima.github.io/OceananigansDocumentation/dev/generated/ocean_wind_mixing_and_convection/#Turbulence-visualization
=> Fix latex rendering in Ocean wind and mixing example

examples/horizontal_convection.jl, src/Simulations/time_step_wizard.jl
=> Provide a better explanation of the `max_change` and `min_change` of `TimeStepWizard`

src/Fields/Fields.jl
This PR adds a method to the function `field` for converting various objects (functions, arrays, `Field`) into `Field` that leverages `ConstantField` when `object isa Number`.
=> Add method for constants to `field`

src/AbstractOperations/broadcasting_abstract_operations.jl, src/Fields/broadcasting_abstract_fields.jl, src/Fields/constant_field.jl, src/Fields/field_boundary_buffers.jl, src/Fields/field_tuples.jl, src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl, src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl, src/Models/NonhydrostaticModels/set_nonhydrostatic_model.jl, src/MultiRegion/cubed_sphere_partitions.jl, src/MultiRegion/multi_region_cubed_sphere_grid.jl, src/MultiRegion/multi_region_field.jl, src/MultiRegion/multi_region_grid.jl, src/MultiRegion/multi_region_models.jl, src/Oceananigans.jl, test/test_hydrostatic_free_surface_models.jl, test/test_multi_region_cubed_sphere.jl, validation/multi_region/cubed_sphere_tracer_advection.jl, validation/multi_region/multi_region_cubed_sphere.jl
Some TODOs:
With the above and fixing the tests then I think we are ready to merge.
Supersedes #3221; closes #3204
=> Cubed sphere tracer advection script

src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl, src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl, src/Models/Models.jl, src/Models/ShallowWaterModels/shallow_water_model.jl
This PR fixes a few type instabilities.
=> Remove some type instabilities

docs/src/model_setup/buoyancy_and_equation_of_state.md, src/BuoyancyModels/buoyancy.jl
Since version 0.80 (March 2023) we've had a warning pointing out the change in behavior of `gravity_unit_vector`, which "flipped" directions at that point. I think it's been enough time that we can remove that warning. What do others think?
=> Removes warning in `Buoyancy` for rotated gravity

src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
This PR propagates the eltype of the "3D grid" into the horizontal grid that's used by the FFT-based implicit free surface solver.
Should help down the line with one of the issues that cropped up on #3288.
@jagoosw
=> Propagate eltype through FFT-based implicit free surface solver

src/Grids/orthogonal_spherical_shell_grid.jl, src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl, src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl, src/MultiRegion/multi_region_cubed_sphere_grid.jl, test/test_multi_region_cubed_sphere.jl
Closes  #3295
Before this PR:
```Julia
julia> grid = ConformalCubedSphereGrid(; panel_size = (3, 3, 3), z = (-1, 0));
julia> model = HydrostaticFreeSurfaceModel(; grid, momentum_advection = VectorInvariant())
ERROR: UndefVarError: `rotation_from_panel_index` not defined
Stacktrace:
[1] with_halo(new_halo::Tuple{Int64, Int64, Int64}, csg::ConformalCubedSphereGrid{Float64, FullyConnected, ....
@ Oceananigans.MultiRegion ~/Research/OC8.jl/src/MultiRegion/multi_region_cubed_sphere_grid.jl:431
[2] Oceananigans.Models.HydrostaticFreeSurfaceModels.PCGImplicitFreeSurfaceSolver(grid::ConformalCubedSphereGrid{Float64, ...
@ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Research/OC8.jl/src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl:47
[3] …
```
=> Fixes bug in free surface build for `HydrostaticFreeSurfaceModel`s on a `ConformalCubedSphereGrid`

src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
This PR deals with the wrong docstring mentioned in #3289.
If in the discussion in #3289 we decide to change the default free-surface solver to Split-Explicit then we can make the change in this PR. ;)
=> Fixes docstring for free surface in `HydrostaticFreeSurfaceModel`

src/Grids/input_validation.jl
Before this PR, the following would *NOT* error:
```Julia
julia> grid = RectilinearGrid(size=2, z=[0, -0.5, -1], topology=(Flat, Flat, Bounded))
1×1×2 RectilinearGrid{Float64, Flat, Flat, Bounded} on CPU with 0×0×3 halo
├── Flat x
├── Flat y
└── Bounded  z ∈ [0.0, -1.0]      variably spaced with min(Δz)=-0.5, max(Δz)=-0.5
```
After this PR:
```Julia
julia> grid = RectilinearGrid(size=2, z=[0, -0.5, -1], topology=(Flat, Flat, Bounded))
ERROR: ArgumentError: z=[0.0, -0.5, -1.0] should be a vector with increasing values.
Stacktrace:
[1] validate_dimension_specification(T::Type, ξ::Vector{Float64}, dir::Symbol, N::Int64, FT::Type)
@ Oceananigans.Grids ~/Research/OC6.jl/src/Grids/input_validation.jl:109
[2] validate_rectilinear_domain(TX::Type, TY::Type, TZ::Type, FT::Type, size::Tuple{Int64, …
```
=> Add validation for array-based coordinates

Project.toml, src/Biogeochemistry.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl, src/Operators/interpolation_utils.jl
There is a bug when trying to auto add bgc tracers when a user has specified a namedtuple of tracers.
@glwagner I recall discussing dropping support for auto adding tracers, I find it quite useful but can't remember where we landed. 
This PR:
- fixes an issue with auto adding bgc tracers
- fixes an issue with auxiliary field dependant forcing in hydrostatic free surface models and boundary conditions
- adds an error when a user tries to define a forcing or functional boundary condition which depends on a field not found in the model, previously this would just raise a mysterious error like the one in https://github.com/OceanBioME/OceanBioME.jl/pull/146#issuecomment-1755771558
=> Fix various bugs in auto adding bgc tracers and setting up field dependant forcing

src/DistributedComputations/distributed_grids.jl, src/Grids/grid_generation.jl, src/Grids/input_validation.jl, src/Grids/latitude_longitude_grid.jl, src/Grids/rectilinear_grid.jl
This PR builds on #3319 to give a slightly more accurate message that checks if a coordinate is sorted (thus checking all values of a coordinate, rather than merely the end points). 
I also moved the location of the error message. Possibly we should remove some of the error messages, @navidcy can you advise?
=> Throw error if nodes given by function/array generators are not sorted

docs/src/model_setup/output_writers.md
replacing `FieldSlicer` in docs to `indices` so that it is up to date.
=> Update Docs/Model/Output Writers to replace `FieldSlicer` -> `indices`

src/Utils/kernel_launching.jl
previously `OffsetNDRange` (in Oceananigans) was assuming that KernelAbstractions' `NDRange` could not have a `Tuple` as the last parameter. 
This PR introduces an Oceananigans-specific `KernelOffsets` type that is necessary to unambiguously identify Oceananigans' offset `NDRange`s from KernelAbstractions' native `NDRange`s
cc @glwagner
=> Explicit `OffsetNDRange` vs `NDRange`

src/OutputWriters/netcdf_output_writer.jl, test/test_netcdf_output_writer.jl
As far as I can tell the property `longname` isn't really standard. According to [CF-coventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch03s03.html) the property should be called `long_name`. This will make several more things work out of box now, like `xarray` plot naming (as expected when sticking to conventions).
=> Changes property "longname" to "long_name" for NetCDFOutputWriter

src/OutputWriters/netcdf_output_writer.jl
This PR converts a few lines to read like English does per our coding style conventions.
=> Tiny conversion of code to English

examples/Spatially_varying_stokes_drift.jl, src/StokesDrifts.jl
@glwagner This PR completes (hopefully!) the implementation of three-dimensional Stokes drift implementation within non-hydrostatic simulations by adding the momentum forcing terms that arise from horizontal gradients of the Stokes drift via $(\nabla \times \mathbf{u^s}) \times \mathbf{v}$. 
I also added an example code that utilizes the new `StokesDrift` function (and retains the previous `UniformStokesDrift` function). It is a little convoluted because I wanted to implement a Stokes drift that varied in all 3 dimensions to ensure that the code was well-behaved. The example is as follows:
- Is based on the Langmuir turbulence example
- The new example imposes a spatially-varying x-aligned Stokes drift that is a separable function of the three spatial dimensions
```math
u^s(x, y, z) = …
```
=> Correction of three-dimensional Stokes drift implementation

Project.toml, src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl, test/test_turbulence_closures.jl
Scalar diffusivity fails on GPU if you use fields for the viscosity/diffusivity since there is no adapt method. 
I've added them in this PR along with a test, feel free to remove the test if its too much.
=> Added adapt method for scalar and scalar biharmonic diffusvity + test

Project.toml
There was a bug in the earlier v4 releases so Oceananigans won't work with them (this has come up as CUDAv4.0 is the final version compatible with CUDA 10.2).
```julia
┌ Warning: The NVIDIA driver on this system only supports up to CUDA 10.2.0.
│ For performance reasons, it is recommended to upgrade to a driver that supports CUDA 11.2 or higher.
└ @ CUDA ~/.julia/packages/CUDA/ZdCxS/src/initialization.jl:71
julia> grid = RectilinearGrid(GPU(); size = (128, 128, 128), extent = (1, 1, 1))
mo128×128×128 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on GPU with 3×3×3 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=0.0078125
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=0.0078125
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with …
```
=> Fix CUDA compat entry

Project.toml, src/TurbulenceClosures/discrete_diffusion_function.jl, src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
This PR fixes a bug that (apparently) crept in on #3401 --- I think. It's hard to know for sure because GPU tests don't pass right now. There may be more to fix.
@jagoosw I believe that `adapt` is missing its first argument. Note the PRs were merged without tests passing... that's why we have this issue.
@wsmoses @jlk9 we may need this to pass for your test PRs to be useful.
@navidcy
=> (0.90.3) Fix bug in adapting `ScalarDiffusivity` and `ScalarBiharmonicDiffusivity`

docs/src/model_setup/buoyancy_and_equation_of_state.md, src/BuoyancyModels/seawater_buoyancy.jl, src/Models/seawater_density.jl
I noticed that the example could be improved a bit by using a grid with z-dependence, and omitting the irrelevant x and y dependence.
Also, the show method for SeawaterBuoyancy needs improvement (underscores are missing from `equation_of_state`).
=> Improve docstring example for seawater density

examples/baroclinic_adjustment.jl, examples/convecting_plankton.jl, examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, examples/two_dimensional_turbulence.jl, src/Oceananigans.jl, src/Simulations/Simulations.jl, src/Simulations/callback.jl, src/Simulations/time_step_wizard.jl
This PR implements two convenience functions that eliminate a line of boilerplate associated with `TimeStepWizard` and `Callback`:
* `conjure_wizard!`
* `add_callback!`
If we like it, I'll modify an example or two to use the convenience functions.
Usage:
```julia
conjure_time_step_wizard!(simulation, IterationInterval(5), cfl=0.5)
```
```julia
progress(sim) = @info string("Iteration ", iteration(sim))
add_callback!(simulation, progress, IterationInterval(10))
```
=> Add convenience functions for conjuring TimeStepWizards and adding `Callback`s

src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
=> Add `@inbounds` to `ab2_step_Gu,v`

Manifest.toml, docs/oceananigans.bib, docs/src/physics/coriolis_forces.md, src/Coriolis/non_traditional_beta_plane.jl, src/Grids/new_data.jl, src/Solvers/batched_tridiagonal_solver.jl, src/StokesDrifts.jl, src/TimeSteppers/runge_kutta_3.jl, src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl, src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl
More usage of DocumenterCitations.jl functionality.
Also, closes #3444.
=> Improve references/citations in docs + enhances 3D Stokes drift example

src/AbstractOperations/metric_field_reductions.jl
This PR fixes the current signature on the docstring for `Average`, which isn't accurate on `main`.
=> Enhance docstring for `Integral`

Project.toml, src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl, validation/vertical_mixing_closures/test_single_column_model.jl
This PR removes argument splatting in intermediate functions that are called to compute the hydrostatic free surface tendencies.
Argument splatting was removed in a prior PR (that'd be great if someone can remember), but was reinstated in #3360.
This PR re-removes splatting. It yields a 2x performance gain for a column model:
```julia
julia> include("test_single_column_model.jl")
┌ Info: Running a simulation of HydrostaticFreeSurfaceModel{CPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
│ ├── grid: 1×1×64 RectilinearGrid{Float64, Flat, Flat, Bounded} on CPU with 0×0×3 halo
│ ├── timestepper: QuasiAdamsBashforth2TimeStepper
│ ├── tracers: (b, e)
│ ├── closure: CATKEVerticalDiffusivity{VerticallyImplicitTimeDiscretization}
│ ├── buoyancy: BuoyancyTracer with ĝ = NegativeZDirection() …
```
=> (0.90.7) Remove argument splatting in hydrostatic free surface tendency kernel entry functions

src/Fields/field.jl, test/test_distributed_hydrostatic_model.jl
This PR removes a comment in fields.jl about needing to implement halo filling of windowed fields as this feature is already implemented and working
=> Remove misleading comment

src/Coriolis/Coriolis.jl, src/Coriolis/hydrostatic_spherical_coriolis.jl, test/regression_tests/hydrostatic_free_turbulence_regression_test.jl, test/test_coriolis.jl
The default should be `ActiveCellEnstrophyConserving` according to @simone-silvestri
=> Change default scheme for `HydrostaticSphericalCoriolis`

docs/src/model_setup/buoyancy_and_equation_of_state.md, src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
Closes #3197
```Julia
julia> grid = RectilinearGrid(size=(2, 2, 2), extent=(1, 1, 1))
2×2×2 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=0.5
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=0.5
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with Δz=0.5
julia> model = HydrostaticFreeSurfaceModel(; grid, momentum_advection=nothing, tracer_advection=nothing, tracers=nothing, buoyancy=nothing)
HydrostaticFreeSurfaceModel{CPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── grid: 2×2×2 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── timestepper: QuasiAdamsBashforth2TimeStepper
├── tracers: ()
├── closure: Nothing
├── buoyancy: Nothing
├── …
```
=> Show method for `HydrostaticFreeSurfaceModel` summarizes advection schemes

src/OutputWriters/netcdf_output_writer.jl, test/test_netcdf_output_writer.jl
This PR aims to allow the user to split netCDF files into smaller files when the filesize exceeds the max_filesize. This addresses https://github.com/CliMA/Oceananigans.jl/issues/2967, and follows the PR https://github.com/CliMA/Oceananigans.jl/pull/3506
=> File splitting in `NetCDFOutputWriter` when `max_filesize` is exceeded

docs/src/contributing.md, test/dependencies_for_runtests.jl, test/runtests.jl
This PR removes the definition of `group` and `test_file` from the `dependencies_for_runtests.lj` otherwise these were redefined with every test file. Now, we are able to set their values and they remain constant for the whole test suite.
Also, now if the test find that `test_file != :none` then they set `group = :none` so that the test suite exits after the `@testset "Single file test"`.
With the current PR we can run a single file test-suite by providing it as an ENV variable. For example:
```Julia
$ TEST_FILE=test_coriolis.jl julia --project -e"using Pkg; Pkg.test()"
Testing Oceananigans
Status `/private/tmp/jl_p57glG/Project.toml`
⌃ [79e6a3ab] Adapt v4.0.2
[6e4b80f9] BenchmarkTools v1.5.0
[052768ef] CUDA v5.2.0
[a2441757] Coverage v1.6.0
[a8cc5b0e] Crayons v4.1.1
[7445602f] …
```
=> Allow testing of just a single file

src/Fields/set!.jl
This is a small nicety for friendliness^TM. For safety^TM we throw a warning if we reshaped. Just in case it wasn't intended.
This allows things like
```julia
julia> grid = RectilinearGrid(size=(2, 3, 4), x=(0, 1), y=(0, 1), z=(0, 1))
2×3×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [0.0, 1.0) regularly spaced with Δx=0.5
├── Periodic y ∈ [0.0, 1.0) regularly spaced with Δy=0.333333
└── Bounded  z ∈ [0.0, 1.0] regularly spaced with Δz=0.25
julia> c = Field{Nothing, Nothing, Center}(grid)
1×1×4 Field{Nothing, Nothing, Center} reduced over dims = (1, 2) on RectilinearGrid on CPU
├── grid: 2×3×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Nothing, …
```
=> Automatically try to reshape arrays when encountering DimensionMismatch

.buildkite/distributed/pipeline.yml
🤖 Beep boop. I am GabrieleBOT. 🤖 Good news! I found a way to reduce unnecessary precompilations! Have you ever noticed that when you move to a GPU node from a CPU one (or viceversa), everything has to be recompiled again? Or sometimes it seems that you are always precompiling... Well, this is partially because the nodes on the Caltech cluster have different architectures, and Julia compiles for the native one, but when you move to a new architecture, the compiled code has to be invalidated and recompiled again. With the latest version of climacommon, I force Julia to always compile for all the possible targets in our cluster. Buildkite pipelines partially do this with the JULIA_TARGET_CPU, but the strings there are incorrect. This PR fixes that too.
=> Update climacommon to 2024_04_05

examples/one_dimensional_diffusion.jl
Fix typo in header for simple diffusion example.
It also fixes crosslinks from quickstart not working.
=> Fix typo in doc @ref in one_dimensional_diffusion.jl

src/Fields/interpolate.jl, src/Models/LagrangianParticleTracking/LagrangianParticleTracking.jl, src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl, test/test_lagrangian_particle_tracking.jl
Fixes #3545 
- Add `truncate_fractional_indices` to handle the truncation of `nothing` indices returned by `fractional_indices` for `Flat` dimensions. `nothing` indices are "truncated" to 1.
- `truncate_fractional_indices` used in `advect_particle` and `bounce_immersed_particle`.
- Add method of `enforce_boundary_conditions` for `Flat` boundaries. This method does not modify the particle position.
=> Fix bug when using Lagrangian particles on Flat topologies

src/Grids/orthogonal_spherical_shell_grid.jl
Before this PR we couldn't create a ConformalCubedSphereGrid on the GPU due to some scalar operations that occur when we fill the metrics. After this PR:
```Julia
julia> grid = ConformalCubedSphereGrid(GPU(), panel_size = (3, 3, 1), z = (0, 1), radius = 1)
ConformalCubedSphereGrid{Float64, FullyConnected, FullyConnected, Bounded} partitioned on GPU(): 
├── grids: 3×3×1 OrthogonalSphericalShellGrid{Float64, FullyConnected, FullyConnected, Bounded} on GPU with 3×3×3 halo and with precomputed metrics 
├── partitioning: CubedSpherePartition with (1 region in each panel) 
├── connectivity: CubedSphereConnectivity 
└── devices: (CUDA.CuDevice(0), CUDA.CuDevice(0), CUDA.CuDevice(0), CUDA.CuDevice(0), CUDA.CuDevice(0), CUDA.CuDevice(0))
julia> grid[3]
3×3×1 …
```
=> Allow creating a `ConformalCubedSphereGrid` on GPU

Project.toml, docs/src/numerical_implementation/pressure_decomposition.md, src/Fields/Fields.jl, src/Fields/field_tuples.jl, src/Models/NonhydrostaticModels/compute_nonhydrostatic_tendencies.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl, src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl, src/Models/NonhydrostaticModels/update_hydrostatic_pressure.jl, test/regression_tests/ocean_large_eddy_simulation_regression_test.jl, test/regression_tests/rayleigh_benard_regression_test.jl, test/regression_tests/thermal_bubble_regression_test.jl, test/test_computed_field.jl, test/test_distributed_models.jl, test/test_jld2_output_writer.jl, test/test_nonhydrostatic_regression.jl, test/test_time_stepping.jl
This PR makes the separation computation of the hydrostatic pressure anomaly an optional feature of `NonhydrostaticModel`. It's also off by default, which hopefully means that triply periodic simulations should work by default (@johnryantaylor a while ago you wanted to do a triply periodic simulation, hopefully this PR makes that possible).
@tomchor ready to review, let me know what you think about the design.
This PR supercedes #3080, where there is an extended description of this change plus a discussion about its pros and cons.
Closes #3364 (I think...)
=> (0.91.0) Make hydrostatic pressure anomaly optional in `NonhydrostaticModel`

docs/src/model_setup/output_writers.md, src/Fields/interpolate.jl, src/OutputWriters/netcdf_output_writer.jl, test/test_output_writers.jl
Related to https://github.com/CliMA/Oceananigans.jl/issues/3460
=> Passes `grid` argument to `NetCDFOutputWriter`

.buildkite/distributed/pipeline.yml
🤖 Beep boop. I am GabrieleBOT. 🤖
I received an update so that I can inform you directly of the changes (but feel free to check the [release notes](https://github.com/CliMA/ClimaModules/blob/main/NEWS.md)).
Over the weekend, a new version of MPITrampoline was released. This version is incompatible with the version of MPIwrapper we were using, so we had to install a new version of MPIwrapper. The most recent version of climacommon uses this updated version of MPIwrapper.
=> Update climacommon to 2024_05_27

.buildkite/pipeline.yml
I think this was needed when we used Plots for docs, and is no longer needed for CairoMakie.
=> Remove `GKSwstype: "100"` from buildkite environment variables

src/OutputWriters/OutputWriters.jl, src/OutputWriters/jld2_output_writer.jl, src/OutputWriters/netcdf_output_writer.jl, src/OutputWriters/output_writer_utils.jl, src/Simulations/callback.jl, src/Simulations/run.jl, src/Utils/schedules.jl, test/test_schedules.jl
This PR modifies `TimeInterval` so that, rather than keeping track of the `previous_actuation_time`, it keeps track of the `first_actuation_time` plus the number of `actuations` (including the initial actuation). The next actuation time is then computed by 
```julia
function next_actuation_time(schedule::TimeInterval)
t₀ = schedule.first_actuation_time
N = schedule.actuations
T = schedule.interval
return = t₀ + N * T
end
```
Note we use `N` instead of `N+1` because the first actuation occurs at `t₀`. So for example, after this first actuation the next actuation time is `t₀ + T`.
This may address #3056.
=> Change `TimeInterval` to avoid roundoff error issue plus some cleanup

src/Grids/orthogonal_spherical_shell_grid.jl
This PR improves the `adapt_structure` method of the `OrthogonalSphericalShellGrid` to allow a more complicated `conformal_mapping` to be transferred to the GPU
=> `Adapt`ing all fields of the `OrthogonalSphericalShellGrid`

Project.toml, src/TurbulenceClosures/velocity_tracer_gradients.jl
I think the interpolation here for the w-terms of the strain-rate tensor hasn't being correctly done. In particular it was assuming  that `w` was a `CenterField`.
Can someone please double-check?
=> (0.91.4) Fix interpolations in off-diagonal components of strain-rate tensor

src/Operators/interpolation_utils.jl, src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
some inline were missing for the general interpolation function. 
This PR fixes it
edit: also corrects a bug in the documentation
=> Add inlines for general interpolation

src/Architectures.jl
updates the creation of a unified memory array following the (new?) CUDA.jl syntax
closes #3664
=> Update unified memory array

src/Fields/function_field.jl
Because the extra docstrings cause confusion, here we want to recommend just one way of building `FunctionField`. See #2515
=> Eliminate extra docstrings for FunctionField

src/ImmersedBoundaries/conditional_fluxes.jl, test/test_immersed_advection.jl
PR #3668 Introduced ambiguity for `TracerAdvection` on `ImmersedBoundaryGrid`s
This PR removes the ambiguity and adds a test to make sure this method is tested
=> Disambiguate tracer fluxes on an immersed boundary

src/BoundaryConditions/boundary_condition.jl
It looks like this constructor was indeed removed by mistake in #3482.
This is a change that breaks several other codes / packages. I reintroduce it here.
On the other hand, if we want to keep it out of the codebase, I will switch this PR to a version bump. 
I vote for reintroducing this convenience constructor.
=> Go back to support `BoundaryCondition(Classification, args...)`

docs/src/grids.md, ext/OceananigansMakieExt.jl
I noticed that there was code in the grids tutorial that could benefit from this feature.
=> Add extension feature for plotting fields when nodes are provided

Project.toml
Patch release including bug fix for biogeochemistry fallbacks (#3685), `mask_immersed_field!` method for `BinaryOperations` (#3683), restricting lat/lon grid topologies (#3694), and more Makie recipe components (#3715).
=> (0.91.9) Bumps patch number

src/OutputReaders/field_time_series_indexing.jl
`target_times` is not passed to the correct architecture before interpolation, leading to errors like [this one](https://buildkite.com/clima/climaocean-ci/builds/1251#0191774b-12c6-4f07-9b7f-35119ef4e639).
This happens when `target_times` is a range, then `map` creates a vector which is not isbits.
This PR corrects this bug.
=> Bugfix in `interpolate!` for `FieldTimeSeries`

Manifest.toml, Project.toml, ext/OceananigansMakieExt.jl
This PR ensures that `Field` do not associated with a "preferred axis" (which will always be `LScene` because they are `AbstractArray{3}`). As a result the axis is determined later, hopefully by the converted form of the args.
Closes #3727, where `lines` was being plotted in an `LScene` if you included both field nodes and a field.
=> Nullify preferred axis for field arg

src/Advection/cell_advection_timescale.jl, test/test_diagnostics.jl
This PR just implements the proposed solution in issue #3679 so that the CFL calculation is correct on flat grids. I also added a test that fails without the fix, and passes with the fix.
Resolves #3679
=> Fix CFL calculation on flat grids

src/Forcings/multiple_forcings.jl, test/test_forcings.jl
=> Test N-tuple `MultipleForcings` and make them work on the GPU

Project.toml, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_equation.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_mixing_length.jl
This PR fixes the values for CATKE parameters:
- the "stability function Ri width" parameter
- all of the `CATKEEquation` parameters
It seems the job of copying these from the optimal set found by [Wagner et al 2024](https://glwagner.github.io/assets/pdf/CATKE.pdf#page=4.67)  was not finished.
=> (0.91.12) Fix non-optimal CATKE parameters

Manifest.toml, Project.toml, src/Models/seawater_density.jl
This PR bumps SeawaterPolynomials 0.3.5 and fixes a doctest. The changes in this PR would remedy the docs built failing in #3766.
=> (0.91.13) Use SeawaterPolynomials 0.3.5

src/OutputReaders/field_dataset.jl, test/test_output_readers.jl
100% bikeshedding. I feel like `FieldDataset` should just use `Symbols` but might be nice to support both for now.
=> Supporting indexing a `FieldDataset` with a `Symbol`

ext/OceananigansMakieExt.jl
This PR changes how the Makie extension works so that `lines` will make a vertical plot for 1D input in y OR z. Previously it only made a vertical plot for z. Typically though, it's only the first dimension "x" that we want to be horizontal (there are exceptions, but this just changes default behavior and can be overrridden).
=> Make vertical line plots in y and z

src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/3795 by changing the default configuration of  `NonhydrostaticModel` to `hydrostatic_pressure_anomaly = CenterField(grid)`. The spurious large-scale flow is developed due to numerical noise in the buoyancy field when the hydrostatic pressure anomaly is treated explicitly. When hydrostatic pressure anomaly is computed using the implicit integral of the buoyancy field, no spurious kinetic energy is introduced.
Here's the MWE as in https://github.com/CliMA/Oceananigans.jl/issues/3795:
```julia
using Oceananigans.Units
using SeawaterPolynomials
using SeawaterPolynomials.TEOS10
using Printf
eos = TEOS10.TEOS10EquationOfState()
arch = CPU()
grid = RectilinearGrid(CPU(), Float64,
topology = (Bounded, Flat, Bounded),
size = …
```
=> Change default `hydrostatic_pressure_anomaly` to `CenterField(grid)` in `NonhydrostaticModel`

examples/tilted_bottom_boundary_layer.jl
The formatting was off in this example:
=> Fix formatting and adds back interior velocity in tilted bottom boundary layer example

ext/OceananigansMakieExt.jl
Kinda cool to be able to do
```julia
heatmap(c^2)
```
and stuff
=> Support AbstractOperations with MakieExtension

src/OutputReaders/field_time_series.jl
I'm not sure why this was added, so we will see if something breaks. But through usage I've realized that its inconvenient (and unexpected) that the length of `FieldTimeSeries` depends on the backend. My intuition is that the length stays the same regardless of _where_ the data is (in memory, or on disk, or a combination of the two). It's also helpful that behavior is the same between backends, which makes switching backends for performance reasons painless.
=> Don't return special length for PartlyInMemory time series

src/Grids/Grids.jl, src/Grids/orthogonal_spherical_shell_grid.jl, src/Operators/vorticity_operators.jl
This PR introduces a new `ConformalMapping` type for the `OrthogonalSphericalShellGrid` and updates the grid construction to incorporate this type as a parameter. The goal is to enable dispatch over various conformal mapping types (e.g., cubed sphere and tripolar) and embed these mappings directly within the `OrthogonalSphericalShellGrid` structure.
=> Add ConformalMapping Type to OrthogonalSphericalShellGrid for Specialized Dispatch

src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl
=> Use generalized coordinate nodes instead of xyz nodes for Lagrangian particle advection

src/Grids/orthogonal_spherical_shell_grid.jl
If a grid is `ConformalCubedSpherePanel` then the horizontal topologies must be FullyConnected.
(this PR stems from https://github.com/CliMA/Oceananigans.jl/pull/3832/files/0eff8a4f24caf55950a3cdb534bb4e196160babb#r1793753375)
=> More specific `ConformalCubedSpherePanel` type

examples/langmuir_turbulence.jl, examples/ocean_wind_mixing_and_convection.jl, validation/vertical_mixing_closures/gpu_tkevd_ensemble.jl, validation/vertical_mixing_closures/heterogeneous_windy_convection.jl
This PR updates the examples to use the notation for fluxes which is used by [Wagner et al 2024](https://glwagner.github.io/assets/pdf/CATKE.pdf) and which we are planning to use for subsequent work as well. In short this is:
* $Q$ for heat flux
* $\tau_x$ and $\tau_y$ for the zonal and meridional _kinematic_ momentum flux. The momentum flux is therefore $\rho_o \tau_x$, where $\rho_o$ is the ocean surface density. This is also consistent with the notation used for Clima's atmosphere model
* $J^c$ for the flux of a tracer $c$.
=> Update examples to use new fluxes notation

src/OutputReaders/field_dataset.jl, src/OutputReaders/field_time_series.jl, test/test_output_readers.jl
=> For output readers, make `reader_kw` default to an empty `NamedTuple`

docs/src/model_setup/boundary_conditions.md, docs/src/model_setup/buoyancy_and_equation_of_state.md, docs/src/model_setup/lagrangian_particles.md, docs/src/model_setup/tracers.md, src/Advection/adapt_advection_order.jl, src/Advection/centered_reconstruction.jl, src/Advection/flux_form_advection.jl, src/Advection/upwind_biased_reconstruction.jl, src/Advection/vector_invariant_advection.jl, src/Advection/weno_reconstruction.jl, src/BuoyancyModels/buoyancy.jl, src/Models/seawater_density.jl
Before this PR, a simple two-dimensional turbulence simulation emits the following display:
```julia
julia> model = NonhydrostaticModel(; grid, advection=WENO(order=5), tracers=:c)
[ Info: Using the advection scheme Upwind Biased reconstruction order 1 in the x-direction because size(grid, 3) = 1
NonhydrostaticModel{CPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── grid: 128×128×1 RectilinearGrid{Float64, Periodic, Periodic, Flat} on CPU with 3×3×0 halo
├── timestepper: RungeKutta3TimeStepper
├── advection scheme: FluxFormAdvection{3, Float64, WENO{3, Float64, Nothing, Nothing, Nothing, Nothing, WENO{2, Float64, Nothing, Nothing, Nothing, Nothing, UpwindBiased{1, Float64, Nothing, Nothing, Nothing, Nothing, Centered{1, Float64, Nothing, Nothing, Nothing, Nothing}}, Centered{1, …
```
=> Dont adapt Flat direction advection scheme plus better summary for FluxFormAdvection

src/Simulations/simulation.jl
=> Fix a typo in `show(io, Simulation)`

src/BoundaryConditions/field_boundary_conditions.jl
Just removing few stray spaces before punctuation.
=> Better message for `regularize_immersed_boundary_condition`

src/Fields/field.jl, src/Operators/Operators.jl, test/test_field_scans.jl
Resolves #3948
`Azᶜᶜᵃ` was defined in the `Operators` module, just not exported, so it couldn't be used in `AbstractOperations`. I'll export some more common metrics.
But now the MWE from #3948 is giving me another error (see below).
Looks like `reduced_dimensions` is not defined for `BinaryOperation`, just `Field`. I'll change the definitions to use `AbstractField` as `AbstractOperation <: AbstractField`.
```
ERROR: MethodError: no method matching reduced_dimensions(::Oceananigans.AbstractOperations.BinaryOperation{Center, Center, Nothing, typeof(*), Field{…}, Oceananigans.AbstractOperations.GridMetricOperation{…}, typeof(Oceananigans.Operators.identity1), typeof(Oceananigans.Operators.identity2), ImmersedBoundaryGrid{…}, Float64})
Closest candidates are: …
```
=> Fix `Integral` reductions on immersed grids

src/BoundaryConditions/BoundaryConditions.jl, src/BoundaryConditions/field_boundary_conditions.jl, src/BoundaryConditions/polar_boundary_condition.jl, test/test_boundary_conditions.jl
This PR implements `PolarBoundaryConditions`. This was originally done in #3953 with `views` of abstract operations (allowing reductions on windowed fields). 
However, two problems arose:
- allowing views of abstract operations might be more complicated than originally thought because we need to pass the topology in the intersect index function (requires a bit of refactoring).
- the `BoundaryConditions` module is loaded before the `Fields` module, requiring quite a mess for a boundary condition which is, in the end, quite simple.
For this reason, I would like to close #3953 and just implement a simple `PolarBoundaryCondition` in this PR with a dedicated kernel to compute the mean of the first / last row.
I can open an issue regarding `views` of `AbstractOperations` so we can tackle it in …
=> Polar boundary conditions

src/Fields/Fields.jl, src/Fields/field_tuples.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_field_tuples.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl, src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl, src/Models/NonhydrostaticModels/nonhydrostatic_model.jl, src/Models/ShallowWaterModels/shallow_water_model.jl, src/TimeSteppers/TimeSteppers.jl, src/TimeSteppers/quasi_adams_bashforth_2.jl, src/TimeSteppers/runge_kutta_3.jl, src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
closes #3967 
Also, the default tendencies in the timestepper constructor should be a copy of the prognostic fields because the very definition of a prognostic field is a field that is evolved in time (requiring a tendency). 
We have no more use for the `TendencyFields` function.
=> Some corrections in the timestepper constructors

src/Advection/flat_advective_fluxes.jl, src/Advection/weno_interpolants.jl, src/Operators/interpolation_operators.jl, test/test_hydrostatic_free_surface_models.jl
I recently encountered a bounds error when trying `WENOVectorInvariant` on a horizontally flat grid. 
The problem was two-fold
- the `Flat` interpolators were not updated to the new syntax
- we were using a wrong signature for interpolations in the WENO stencil that does not account for the grid topology
- (bonus!) there are no tests for `WENOVectorInvariant`
This PR should resolve these issues
edit, I will also remove the "no-grid" interpolation operators to not allow something like this.
=> Fix horizontally `Flat` WENO advection

src/OutputReaders/field_time_series.jl, src/OutputReaders/set_field_time_series.jl
The issue is that the grid cannot be reconstructed. So we add some limited support for doing that.
=> Add support for loading data generated prior to 0.95.0 with FieldTimeSeries

src/Models/Models.jl, src/Simulations/simulation.jl, src/Simulations/time_step_wizard.jl
This PR allows us to remove the grid from the `OceanSeaIceModel` type defined in ClimaOcean.jl
(see https://github.com/CliMA/ClimaOcean.jl/blob/a193aee12de264600dda9ca196acdb52ee3a726d/src/OceanSeaIceModels/ocean_sea_ice_model.jl#L20)
=> Remove grid requirements from a `Model` in a `Simulation`

ext/OceananigansMakieExt.jl
This PR adds plot labels to Makie plots. It only adds them when using the plotting function that creates an axis, eg `heatmap(c)`. It doesn't work for `heatmap!(ax, c)`.
Example:
```julia
using GLMakie
grid = RectilinearGrid(size=(4, 4, 1), extent=(1, 1, 1))
c = CenterField(grid)
set!(c, (x, y, z) -> randn())
heatmap(c)
```
gives 
but
```julia
heatmap(c; axis=(xlabel="yo", ylabel="hi"))
```
preserves the user labels,
and
```julia
fig = Figure()
ax = Axis(fig[1, 1])
heatmap!(ax, c)
```
doesn't add labels.
=> Try to add plot labels automagically within Makie extension

src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
on main we get
```
Candidates:
diffusive_flux_x(i, j, k, grid, ::Oceananigans.TurbulenceClosures.IsopycnalSkewSymmetricDiffusivity{<:Any, <:Oceananigans.TurbulenceClosures.AdvectiveFormulation, <:Any, Nothing}, args...)
@ Oceananigans.TurbulenceClosures ~/.julia/packages/Oceananigans/DC4Ff/src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl:215
diffusive_flux_x(i, j, k, grid, closure::Union{Oceananigans.TurbulenceClosures.IsopycnalSkewSymmetricDiffusivity, AbstractVector{<:Oceananigans.TurbulenceClosures.IsopycnalSkewSymmetricDiffusivity{TD, A}}}, diffusivity_fields, ::Val{tracer_index}, c, clock, fields, buoyancy) where tracer_index
@ Oceananigans.TurbulenceClosures ~/.julia/packages/Oceananigans/DC4Ff/src/TurbulenceClosures/turbulence_closure …
```
=> Disambiguate `diffusive_flux_*` methods for `NoDiffusionISSD`

src/OutputReaders/field_time_series.jl
Specifically if we want to reconstruct grids that are _not_ `ImmersedBoundaryGrid` then we have to deduce the topology, which require a bit of string parsing.
=> More JLD2 shenanigans for reconstructing FieldTimeSeries

src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_mixing_length.jl
This PR changes the default Cb parameter for CATKE to yield a Von Karman constant of 0.4 in near-bottom similarity layers.
Closes #4015
=> Add default Cb for CATKE

src/BoundaryConditions/fill_halo_regions.jl
Like in https://github.com/CliMA/Oceananigans.jl/pull/4029
one might now have a tuple like `::Tuple{OffsetArrays.OffsetArray{Float64, 3, ReactantCUDAExt.CuTracedArray{Float64, 3, 1, (35, 34, 16)}}, OffsetArrays.OffsetArray{Float64, 3, ReactantCUDAExt.CuTracedArray{Float64, 3, 1, (34, 35, 16)}}})` which is not an `ntuple{<:Any, offsetarray}` (since they aren't the same underlying type) but is a `tuple{vararg{offsetarray}}` (since this is a tuple of all offsetarrays)
=> Generalize ntuple type constraints to be tuple{vararg}

src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/dynamic_coefficient.jl
Related to https://github.com/CliMA/Oceananigans.jl/issues/4069#issuecomment-2628752818
=> Improves `DynamicCoefficient` docstring with discussion about `schedule`

src/OutputWriters/checkpointer.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/4080
=> Make checkpointing work when prefix contains non-ascii characters

Project.toml, src/Fields/interpolate.jl, test/test_field.jl
With the recent change in interpolation in #4074, we are hitting an error in ClimaOcean.jl (see https://github.com/CliMA/ClimaOcean.jl/actions/runs/13301013435/job/37142339229).
This is because the convert function
https://github.com/CliMA/Oceananigans.jl/blob/399695072641a53cfa02f8d9bc34c5f2ad54dffa/src/Fields/interpolate.jl#L84 is susceptible to precision errors when the input is small enough:
```julia
julia> convert_to_0_360(-1e-12)
359.999999999999
julia> convert_to_0_360(-1e-13)
359.9999999999999
julia> convert_to_0_360(-1e-14)
0.0
```
This is not acceptable because a negative number should always be on the "left" side of the zero corresponding to values between 359 and 360, i.e. moving to zero from the left side should result in 360 not 0.
In ClimaOcean we were hitting this error …
=> Precision error when converting to 0 - 360

Project.toml, src/Oceananigans.jl
until https://github.com/CliMA/Oceananigans.jl/pull/3836 is resolved
cc @taimoorsohail
=> Add warning for Julia version >= v1.11

src/Simulations/callback.jl, src/Simulations/run.jl, test/test_simulations.jl
Adds `finalize!(callback, sim)`. By default, it does nothing. This gets called after the time-stepping loop is done. It only gets called if using `run!`.
Also actually calls `initialize!` for callbacks which previously was not called.
=> Add `finalize!` for callbacks

src/Simulations/run.jl, src/Simulations/simulation.jl, test/dependencies_for_runtests.jl, test/test_enzyme.jl, test/test_simulations.jl
This PR adds the option to "disable" time-step alignment for simulations. This is useful when creating coupled models with nested simulations. In the scenario of nested simulation, we would like the "main" simulation to manage their child simulations. For this, it's useful to ensure that the child simulations do not align their time-steps.
This PR also simplifies `time_step!` and changes its behavior somewhat. After this PR, calling `time_step!(sim)` will always take a time-step; also, only `run!` will be responsible for "stopping" a simulation.
Note that previously, `time_step!(sim)` would _not_ take a time-step if for some reason `sim.running == false` --- but only for the very first time-step. Even if `sim.running == false`, a simulation with `sim.initialized == true` would take a …
=> Add option to turn off time-step alignment

src/OutputReaders/field_time_series_indexing.jl
This PR implements `InterpolationIndices` for time-interpolation of `FieldTimeSeries`. This is useful when interpolating many fields which all have the same interpolation indices (such as a prescribed atmosphere). In that case we need only compute the interpolation indices once, and pass them into a kernel that does the interpolation.
=> Implement InterpolationIndices for time-interpolating FieldTimeSeries

README.md
Closes #3758
Ideally we should regenerate these benchmarks.
=> Remove wrong statements from README about parallelization

src/Simulations/run.jl, test/test_simulations.jl
This is needed to implement @simone-silvestri's suggested interface for coupling. Leverages the new ability to ensure a constant time-step by setting `sim.align_time_step = false`.
=> Implement `time_step!(sim::Simulation, Δt)`

src/DistributedComputations/distributed_grids.jl, src/Grids/input_validation.jl, test/test_distributed_hydrostatic_model.jl, test/test_distributed_models.jl
Because Distributed tests are currently broken, I found this issue running the tests locally. It might be helpful @simone-silvestri if you can reproduce that the tests pass.
Also there is no specific unit test for `reconstruct_global_grid`. This error is found indirectly by the hydrostatic models test. @simone-silvestri I suggest adding a specific unit test in another PR.
=> Fix reconstruct_global_grid

src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl, test/test_turbulence_closures.jl
Quality of life improvement. Now users can get viscosity and diffusivity of a model simply as
```julia
ν = viscosity(model)
κ = diffusivity(model, Val(:b))
```
instead of having to pass `model.diffusivity_fields` and `model.closure` as separate arguments.
=> Adds `viscosity(model)` method and similarly for `diffusivity`

src/OutputReaders/field_time_series.jl, test/test_output_readers.jl
These were not add originally because they were not needed, but may be needed now @simone-silvestri
=> Add non-trivial default boundary conditions for `FieldTimeSeries`

.github/workflows/ci.yml
* Trigger on pull requests, pushes to `main` and tags
* Add concurrency group to cancel subsequent jobs in PRs. This is particularly useful to cancelling quickly macOS jobs, since there are only 5 concurrent runners available for the entire organisation
* Use `julia-actions/cache` instead of `actions/cache`
* Add timeouts, to avoid hanging jobs hold on to the runners for 6 hours.
=> [CI] Some improvements to GitHub Actions setup

Project.toml, src/Oceananigans.jl, src/OutputReaders/field_time_series_indexing.jl
required for distributed simulations with ECCO restoring in `ClimaOcean`
=> Missing a method for `cpu_interpolating_time_indices`

src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl
I noticed that TKE is not masked because `compute_diffusivities!` follows `mask_immersed_field!` within `update_state!`.
=> Mask CATKE's TKE

src/OutputReaders/field_time_series_indexing.jl
This is needed to have indices that are CuTracedRNumber inside kernels like `interpolate_atmosphere_state` in ClimaOcean.
=> Convert TimeInterpolator indices to Int

src/DistributedComputations/distributed_architectures.jl
@avik-pal asked me "what's RankConnectivity". I was puzzled at first. Then I looked and I said, "oh, it's the neighboring ranks". So we are changing the name of this object to represent the thing that it is.
=> Better name than RankConnectivity

src/Operators/Operators.jl
I think the necessity of this PR possibly implies that we should combine / coalesce the `Operations` and `AbstractOperations` modules. Which by the way have pretty similar names if you didn't notice.
=> Export operators for surface / horizontally-reduced derivatives

src/DistributedComputations/distributed_architectures.jl, src/DistributedComputations/distributed_immersed_boundaries.jl, src/DistributedComputations/halo_communication.jl, src/Grids/orthogonal_spherical_shell_grid.jl, src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/distributed_split_explicit_free_surface.jl, src/Models/interleave_communication_and_computation.jl
in main, the default behavior is defined for an asynchronous distributed architecture and methods are further specialized for a synchronized architecture
in light of #4301, it is a better pattern to have the default behavior being the one of a synchronized architecture and specialize the methods for an asynchronous architecture...
=> Switch default behavior of `Distributed` architecture

src/DistributedComputations/distributed_grids.jl, src/Grids/latitude_longitude_grid.jl
while working on #4293 I noticed that I was filling the metrics incorrectly for the `LatitudeLongitudeGrid`, leading to incorrect solutions.
This error stems from the fact that the same metrics are ordered differently for a `LatitudeLongitudeGrid` and an `OrthogonalSphericalShellGrid`. I think this might be a big source of error if a developer is not very careful (like me), so I think it's a good idea unifying the two grids.
In this PR I am reordering the metrics of the latitude longitude grid to match the ones of the orthogonal spherical shell grid.
We could do also the other way around, however I like having the center-center at the top (just aesthetic personal preference)
=> Swap around latitude longitude metrics

src/BoundaryConditions/field_boundary_conditions.jl, src/BoundaryConditions/polar_boundary_condition.jl, test/test_boundary_conditions.jl
This PR changes the criteria for `PolarBoundaryCondition` to check whether the north/south end of the grid is at the pole. Previously, it checked whether the _center of the first halo_ was "beyond the pole". This "non-polar" criteria produces undesirable behavior; for example, whether or not the polar boundary condition would be applied depended on resolution.
It also reorganizes code so that `polar_boundary_condition.jl` only contains code relevant to applying the `PolarBoundaryCondition`, and `FieldBoundaryCondition` stuff resides in `field_boundary_condition.jl`.
=> Use polar criteria to build PolarBoundaryCondition

src/AbstractOperations/conditional_operations.jl, src/ImmersedBoundaries/immersed_reductions.jl, test/test_field_scans.jl
This PR adds validation for NotImmersed conditions that are Arrays. Continuation from #4266.
=> Add validation for `condition` kwarg in `ConditionalOperation` for immersed boundary grids

src/Utils/schedules.jl
Resolves https://github.com/CliMA/Oceananigans.jl/issues/4369
I am curious what others think. The reason why 86400.0 is valid is because it can be converted to `Int` (which happens under the hood). So if users do math on their iteration interval they will have to manually convert it to `Int`.
=> Require `interval::Int` in IterationInterval?

src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl, src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl, src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
This PR refactors `Oceananigans.fields(::HydrostaticFreeSurfaceModel)` so that it only contains non-nothing fields. To do this we add a function `constructor_field_names` which basically returns the same thing as `keys(fields(model))`, but before the model is constructed.
=> Refactor hydrostatic free surface names

src/Solvers/conjugate_gradient_poisson_solver.jl
This fixes a bug in the `summary` method for `ConjugateGradientPoissonSolver`. It also adds a docstring. @xkykai I believe you coded this, right? Can you take a look at the docstring to make sure it's okay?
=> Fix `summary()` for `ConjugateGradientPoissonSolver`

src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
i noticed that the only example we have of using this in ClimaOcean used the DiffusiveFormulation. Therefore, it should be the default.
=> Change isopycnal_skew_symmetric_diffusivity.jl to use DiffusiveFormulation

src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl, src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
Inside immersed boundaries we should have the diagonal term equal to 1. For this reason, the implicit linear coefficient should be masked
=> Mask implicit linear coefficient if inside an immersed boundary

src/OutputWriters/checkpointer.jl
The `:properties` section of [Checkpointer docstring](https://clima.github.io/OceananigansDocumentation/dev/appendix/library/#Oceananigans.OutputWriters.Checkpointer-Tuple{Any}) was not rendering correctly because of a missing `. This PR adds this.
As well (and if you think unnecessary it can be removed) it elaborates on the default setting for `properties` when building a `Checkpointer`.
=> Fix rendering + reference `default_checkpointed_properties` in `Checkpointer` docstring

examples/tilted_bottom_boundary_layer.jl
probably good to not use vectors in example scripts because they go against our philosophy that "only the architecture should change to run on different backends"
closes #4438
=> Use tuple instead of vector in `tilted_bottom_boundary_layer.jl`

.buildkite/pipeline-benchmarks.yml, test/benchmark_tests.jl
This PR tidies up a bit and puts the benchmarks in a loop.
Also it turns out that from the main branch pipeline we need to save the build number and the job ID if we later want to access them, not the build id. This has to be done in the specific pipeline (`steps`) that generates the artifacts.
=> Improve benchmarks yml

src/AbstractOperations/conditional_operations.jl
I've just modified the condition size check error to be a bit more helpful by outputting both the size of the operand and the size of the condition.
=> Making condition size mismatch error a bit more helpful

docs/src/appendix/library.md, src/Oceananigans.jl, src/TurbulenceClosures/TurbulenceClosures.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl
what do you think @glwagner?
```Julia
julia> using Oceananigans.TurbulenceClosures
help?> CATKEVerticalDiffusivity
search: CATKEVerticalDiffusivity
CATKEVerticalDiffusivity([time_discretization = VerticallyImplicitTimeDiscretization(),
FT = Float64;]
mixing_length = CATKEMixingLength(),
turbulent_kinetic_energy_equation = CATKEEquation(),
maximum_tracer_diffusivity = Inf,
maximum_tke_diffusivity = Inf,
maximum_viscosity = Inf,
minimum_tke = 1e-9,
minimum_convective_buoyancy_flux = 1e-11,
negative_tke_damping_time_scale = 1minute,
tke_time_step = nothing)
Return the CATKEVerticalDiffusivity turbulence closure for vertical mixing by small-scale ocean turbulence based on the
prognostic evolution of subgrid Turbulent Kinetic Energy (TKE).
│ CATKE vertical diffusivity
│
│ …
```
=> Export CATKE and k-ε

src/BoundaryConditions/field_boundary_conditions.jl, test/test_boundary_conditions.jl
for `LatitudeLongitudeGrid`s spanning -90:90 with a `Nothing` location in the latitude direction.
For reference on main:
```julia
julia> grid = LatitudeLongitudeGrid(size = (600, 100, 1), latitude = (-90, 90), longitude = (0, 360), z = (0, 1))
600×100×1 LatitudeLongitudeGrid{Float64, Periodic, Bounded, Bounded} on CPU with 3×3×1 halo and with precomputed metrics
├── longitude: Periodic λ ∈ [0.0, 360.0)  regularly spaced with Δλ=0.6
├── latitude:  Bounded  φ ∈ [-90.0, 90.0] regularly spaced with Δφ=1.8
└── z:         Bounded  z ∈ [0.0, 1.0]    regularly spaced with Δz=1.0
julia> minimum_xspacing(grid)
ERROR: ArgumentError: Cannot specify north boundary condition ValueBoundaryCondition: Oceananigans.BoundaryConditions.PolarValue{OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, …
```
=> Bugfix BC default

src/Grids/input_validation.jl, src/OrthogonalSphericalShellGrids/tripolar_grid.jl, test/test_grids.jl, test/test_tripolar_grid.jl
- Converts the warning about providing too many vertical interfaces (`z` faces) into an error.
- Ensures that this error is properly triggered during the creation of a `TripolarGrid`.
- Adds tests verifying that an error is raised when too many or few `z` faces are passed to:
- `RectilinearGrid`
- `LatitudeLongitudeGrid`
- `TripolarGrid`
=> Improve and test error handling for vertical level specification in grid construction

Project.toml, ext/OceananigansNCDatasetsExt.jl, test/test_netcdf_writer.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/4416
I also changed the metric names from `immersed_boundary_mask` to `peripheral_nodes`, which is what we use in the code.
=> Make `NetCDFWriter` work with `PartialCellBottom` grids

src/BoundaryConditions/field_boundary_conditions.jl, src/BoundaryConditions/polar_boundary_condition.jl, test/test_boundary_conditions.jl
In #4457 we forgot `Face` fields that do not allow `ValueBoundaryConditions`. This PR introduces an equivalent `PolarOpenBoundaryCondition` for fields with `LY == Face` (and a couple more tests).
for reference on main:
```julia
julia> grid = LatitudeLongitudeGrid(size=(10, 10, 10), latitude=(-90, 90), longitude=(-10, 10), z = (0, 1))
10×10×10 LatitudeLongitudeGrid{Float64, Bounded, Bounded, Bounded} on CPU with 3×3×3 halo and with precomputed metrics
├── longitude: Bounded  λ ∈ [-10.0, 10.0] regularly spaced with Δλ=2.0
├── latitude:  Bounded  φ ∈ [-90.0, 90.0] regularly spaced with Δφ=18.0
└── z:         Bounded  z ∈ [0.0, 1.0]    regularly spaced with Δz=0.1
julia> v = YFaceField(grid)
ERROR: ArgumentError: Cannot specify north boundary condition ValueBoundaryCondition: …
```
=> Some more fixing for polar BC

src/Grids/latitude_longitude_grid.jl, test/test_grids.jl
This might prove useful for building bathymetry on RectilinearGrids for a particular place on the Earth, using ClimaOcean's metadata features to automate the process. For example we would do something like
```julia
grid = RectilinearGrid(etc...)
corresponding_lat_lon = LatitudeLongitudeGrid(grid, origin=(210, 45))
bottom_height = ClimaOcean.regrid_bathymetry(corresponding_lat_lon)
ibg = ImmersedBoundaryGrid(grid, GridFittedBottom(bottom_height))
```
I could also see us building this into ClimaOcean's Metadata utilities directly, eg so we can also initialize T, S from datasets. 
cc @tomchor 
Also I just realized that we can construct the _exact_ grid for `OrthogonalSphericalShellGrid` (here, we have to make an approximation when computing the longitudes).
I think this is useful and we have …
=> Add a constructor for LatitudeLongitudeGrid from RectilinearGrid

src/Grids/latitude_longitude_grid.jl
There were some leftover `@show` statements.
=> Clean up `LatitudeLongitudeGrid` from rectilinear grid

src/Fields/field.jl, test/test_field.jl
Currently, `extrema(field)` fails with scalar indexing on CUDA. The reason for this is that `extrema(c::AbstractField)` is not defined, so we fall back to `extrema(a::AbstractArray; dims, kw...)`.
This commit adds `extrema(field)` by calling `minimum(field)` and `maximum(field)` separately. Note that there's an opportunity for optimization here, where both the extrama are found in the same reduction.
=> Add extrema(c::AbstractField)

src/MultiRegion/multi_region_field.jl
This PR resolves a method ambiguity that arises when attempting to set a `MultiRegionField` using a scalar value.
Minimal Working Example:
```
grid = ConformalCubedSphereGrid(CPU(); panel_size=(4, 4, 1), z=(-1, 0), horizontal_direction_halo=2, radius=1)
u = XFaceField(grid)
set!(u, 1)
```
The above code throws the following error:
```
ERROR: MethodError: set!(::Field{...}, ::Int64) is ambiguous.
```
Root Cause: There is a method ambiguity between the following definitions:
```
set!(u::Field, a::Number) (defined in Fields/set!.jl)
set!(mrf::Field{...}, v) (defined in MultiRegion/multi_region_field.jl)
```
To resolve this, we define the following explicit methods:
```
set!(mrf::MultiRegionField, a::Number)  = apply_regionally!(set!,  mrf, a)
fill!(mrf::MultiRegionField, a::Number) = …
```
=> Resolve ambiguity when setting MultiRegionField with a number

src/BoundaryConditions/boundary_condition.jl, src/BoundaryConditions/continuous_boundary_function.jl, src/BoundaryConditions/discrete_boundary_function.jl, src/BoundaryConditions/perturbation_advection_open_boundary_matching_scheme.jl, src/BoundaryConditions/polar_boundary_condition.jl, src/Fields/field.jl, src/OutputReaders/extract_field_time_series.jl, src/OutputReaders/field_time_series.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_top_boundary_condition.jl
This PR refactors the `getbc` interface so that developers can implement methods to extend `bc.condition` directly, rather than having to extend `BoundaryCondition{<:Any, MyNewCondition}`. This simplifies the code and will allow more complex `getbc` cases to be expressed.
=> Refactor `getbc` interface

src/Grids/Grids.jl, src/Grids/conformal_cubed_sphere_panel.jl, src/MultiRegion/cubed_sphere_grid.jl, src/Operators/vorticity_operators.jl, src/OrthogonalSphericalShellGrids/OrthogonalSphericalShellGrids.jl, src/OrthogonalSphericalShellGrids/conformal_cubed_sphere_panel.jl, test/test_biogeochemistry.jl, test/test_grids.jl, test/test_multi_region_cubed_sphere.jl, validation/orthogonal_spherical_shell_grid/splash.jl
This PR fixes a bug in the definitions of `ConformalCubedSpherePanel` and `ConformalCubedSpherePanelGrid` by removing an extra sixth `:Any` type parameter that does not belong in the `OrthogonalSphericalShellGrid` type.
Previously:
```
const ConformalCubedSpherePanel = OrthogonalSphericalShellGrid{<:Any, FullyConnected, FullyConnected,
<:Any, <:Any, <:Any,
<:CubedSphereConformalMapping}
const ConformalCubedSpherePanelGrid = OrthogonalSphericalShellGrid{<:Any,
<:Any,
<:Any,
<:Any,
<:Any,
<:Any,
<:CubedSphereConformalMapping}
```
The sixth `:<Any` parameter was unnecessary and did not correspond to any field in the underlying `OrthogonalSphericalShellGrid` type. This PR removes that extraneous type to ensure correctness and proper method dispatch.
=> Fix incorrect type parameter count in ConformalCubedSpherePanel and ConformalCubedSpherePanelGrid definitions

src/DistributedComputations/distributed_architectures.jl
@tomchor this might help catching incorrectly configured MPI, see #4483
=> Warn if using a `Distributed` architecture using a single rank

src/Utils/kernel_launching.jl
This was the error hit in #4483.
The fact that MPI was not correctly configured was leading to a distributed grid with only one rank. 
This triggers a launch with a zero-tuple, which is the intended behavior in the case we launch a distributed architecture with 1 rank only. 
Generally speaking, launching a kernel with a zero-tuple should be possible but might be an indication that there might be something wrong, so it is good to spit out a warning.
=> Add a warning if trying to launch a kernel with workspec `()` instead of throwing an error

src/DistributedComputations/distributed_macros.jl
Renaming `mpi_initialized` was creating problems when used in other packages.
=> Fix a bug in the handshake macro

src/OutputWriters/checkpointer.jl
The warning message when setting the timestepper assumes that all prognostic fields require an associated tendency field.
However, not all prognostic fields need an associated tendency stored. An example is the free surface field using the `SplitExplicitFreeSurface` that evolves with $$\frac{\partial \eta}{\partial t} = - \nabla  \cdot \int_0^\eta u dz$$ where the tendency is simple enough to be computed on the fly inside the evolution kernel.
This PR updates the warning message to reflect the needs of the model.
Discussed in #4516
=> Fix warning message for set timestepper

src/Models/VarianceDissipationComputations/VarianceDissipationComputations.jl, src/Models/VarianceDissipationComputations/compute_dissipation.jl, src/Models/VarianceDissipationComputations/flatten_dissipation_fields.jl
Docs have been built and the preview shows that the links now work; see https://clima.github.io/OceananigansDocumentation/previews/PR4537/appendix/library/#VarianceDissipationComputations
I suggest we merge this without requiring the rest of the CI to pass (for economy of resources)
=> Fix `VarianceDissipation` docstring links

src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl, src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_equations.jl
This splits the kernel `substep_turbulent_kinetic_energy!` into two separate kernels:
- `substep_turbulent_kinetic_energy_diffusivities!`, which computes `Ke` and `Le`
- `substep_turbulent_kinetic_energy!`, which just computes `e`
This is done to avoid a race condition: computing `Ke` requires use of both `e[i,j,k]` and `e[i,j,k-1]`. The latter can be permuted by another thread in the kernel before it is used for `Ke`.
=> Splitting `substep_turbulent_kinetic_energy!` into two kernels

src/BoundaryConditions/field_boundary_conditions.jl
This code needs to be cleaned up (constructors for objects should not return `nothing`) but in the interim, this may fix the issue on #4547
=> Add constructor for missing FieldBoundaryConditions

src/Utils/multi_region_transformation.jl, test/test_multi_region_unit.jl
which was not supported before, only function calls were supported.
I am also adding a simple test for `@apply_regionally` since it looks like we are missing tests for it. We should populate the tests as we find new bugs.
=> Support assignment `a = b` in `@apply_regionally`

examples/kelvin_helmholtz_instability.jl, src/Models/VarianceDissipationComputations/VarianceDissipationComputations.jl, src/TimeSteppers/TimeSteppers.jl
This PR changes the Kelvin-Helmholtz example to plot Oceananigans fields instead of Arrays and thus utilize the OceananigansMakieExt.
https://clima.github.io/OceananigansDocumentation/previews/PR4569/literated/kelvin_helmholtz_instability/
=> Use Makie extension in Kelvin-Helmholtz example

src/BoundaryConditions/perturbation_advection_open_boundary_matching_scheme.jl, validation/open_boundaries/cylinder.jl, validation/open_boundaries/oscillating_flow.jl
Based on a conversation with @glwagner and @xkykai, this PR removes the use of indices for storage in `PerturbationAdvection` and makes a couple of fixes and improvements. On main, this index sets up a hidden/secret storage for left open boundary conditions at `i=0` that saves the velocity of the previous timestep. This is not done for the right boundary, so this PR will make both left and right `PerturbationAdvectionOBC`s the same.
@jagoosw I'm curious to hear your thoughts here. We went through the code and couldn't find the need for a storage for the velocity at a previous timestep. In fact, if I simply get rid of it (as this PR does) the results basically don't change, with the exception of the initial velocity. Here are two identical simulations, the only difference being the use of …
=> Remove the use of indices for storage in `PerturbationAdvection`

src/Solvers/conjugate_gradient_poisson_solver.jl
Closes https://github.com/CliMA/Oceananigans.jl/issues/4581, and details of the origin of this can also be found https://github.com/CliMA/Oceananigans.jl/pull/4539.
@glwagner @tomchor @amontoison
=> Remove shift in `FFTBasedPoissonSolver` and multiply by negative one in preconditioning for `Conjugate GradientPoissonSolver`

ext/OceananigansNCDatasetsExt.jl, src/OutputWriters/jld2_writer.jl
Use field name `array_type` in show method for OutputWriters instead of `array type`.
=> Minor enhancement to show(io, ::OutputWriters)

Project.toml
The release 1.3.4 added a few fixes for GPU kernel on new AMD GPUs. It fixed a few issues that I got on the new MI250.
=> Bump the compat entry for AMDGPU.jl

src/ImmersedBoundaries/immersed_boundary_condition.jl
I am implementing immersed drag for a `SeaIceModel` [here](https://github.com/CliMA/ClimaSeaIce.jl/pull/84), but I noticed that the regularization for `ImmersedBoundaryCondition` is not correct because it assigns boundary conditions in `nothing` directions, for example, in https://github.com/CliMA/ClimaSeaIce.jl/pull/84 this happens:
```julia
julia> grid = RectilinearGrid(size = (10, 10, 1), x = (0, 1), y = (0, 1), z = (0, 1));
julia> grid = ImmersedBoundaryGrid(grid, GridFittedBottom(rand(10, 10)));
julia> u_bcs = FieldBoundaryConditions(grid, (Face, Center, Nothing); immersed = FluxBoundaryCondition(1));
julia> model = SeaIceModel(grid; boundary_conditions = (; u = u_bcs));
julia> model.velocities.u.boundary_conditions.immersed
ImmersedBoundaryCondition:
├── west: Nothing
├── east: …
```
=> Correct regularization for `ImmersedBoundaryCondition`

src/BoundaryConditions/field_boundary_conditions.jl
Even if `regularize_field_boundary_conditions` is not necessarily thought to be user-facing, it is a bit easier to understand and to use if we pass a location rather than a `field_name`, so that other models can use it without needing to extend the `assumed_field_location` function in oceananigans to add the `field_name` they need.
comes from issue #4702
=> Regularize field boundary conditions with a location rather than a name

Project.toml, src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_rk3_step.jl, src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl, test/test_dynamics.jl
Following discoveries in #4705 it seems like there is some difference in the AB2 and the RK3 timestepper for the hydrostatic free surface model regarding implicit timestepping. This PR is here to try to fix the (possibly) bug in the RK3 timestepper with implicit diffusion
This is a chance to add also dynamics tests for the hydrostatic RK3 timestepper which were lacking.
EDIT: Indeed, the implicit-explicit timestepping was not correctly implemented with RK3. The implicit timestep needs to be applied to the "Forward Euler" evolved variables before averaging, not to the averaged variables that include previous time-step information.
As part of this PR, I also remove the warning on the implicit - explicit stepping with split RK3 since it is tested
=> Correct the implicit Split-RK3 diffusion implementation

src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
I believe the CG solver is always valid (at least, we will find out when it is not). This addresses the issue discussed in #4719
=> Use CG as fallback solver for all cases

src/MultiRegion/multi_region_field.jl
Consider the following MWE:
```
┌ Warning: You are using Julia v1.11 or later!"
│ Oceananigans is currently tested on Julia v1.10."
│ If you find issues with Julia v1.11 or later,"
│ please report at https://github.com/CliMA/Oceananigans.jl/issues/new
└ @ Oceananigans ~/Library/CloudStorage/Dropbox/StudyFolder/PostDocMITDesktop/Codes/Oceananigans/main/src/Oceananigans.jl:124
[ Info: Oceananigans will use 8 threads
julia> arch = CPU()
CPU()
julia> Nx, Ny, Nz = 4, 4, 4
(4, 4, 4)
julia> grid = ConformalCubedSphereGrid(arch; panel_size=(Nx, Ny, Nz), z=(-1, 0), horizontal_direction_halo=2, radius=1)
ConformalCubedSphereGrid{Float64, Oceananigans.Grids.FullyConnected, Oceananigans.Grids.FullyConnected, Bounded} partitioned on CPU():
├── grids: 4×4×4 …
```
=> Extend the interior function to MultiRegionFields

src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
We've fixed it at #4728 but it creeped back in!!
This is because without the "update merge before merging" requirement a new PR can undo changes.
For a typo this is insignificant. But sometimes a new PR can undo a bug fix that was dealt with by a previous PR...
cc @glwagner, @simone-silvestri
=> Once again, fix warning message formatting in SplitRungeKutta3TimeStepper

Project.toml, docs/Project.toml
I see the docs are currently failing in Buildkite. I feel like there are a few issues with CUDA.jl right now (e.g. https://github.com/JuliaGPU/CUDA.jl/issues/2879) so this PR tries to fix things by using CUDA.jl v5.8.2. Hopefully this won't be needed once v5.8.4 is tagged and released.
Not sure why the main tests are okay and just the docs fail...
=> Enforce (temporarily) CUDA.jl < v5.8.3 for Buildkite CI docs

ext/OceananigansReactantExt/Fields.jl
Reactant method of set_to_field produces inconsistent results with the original, and the original now works without erroring.
=> Eliminate Reactant set_to_field

Project.toml, ext/OceananigansNCDatasetsExt.jl, src/OutputWriters/netcdf_writer.jl
The function `convert_for_netcdf()` (which converts objects for use in NetCDFs as attributes) was used only in the `OceananigansNCDatasets.jl` extension to write grid-reconstruction arguments to NetCDF, but I think it would be nice to make it possible for users to use this interface. It can be useful to write all sorts of objects to NetCDF, and this function makes it easy to do it. It requires minimal code changes and no extra maintenance on our part.
=> (0.98.1) Make `convert_for_netcdf()` accesible to users
